// Generated by prism_v2sc
#pragma once

#include <systemc>
#include <string>

using namespace sc_core;
using namespace sc_dt;

#ifndef PRISM_V2SC_MOD_SUB_REGISTER_HPP
#define PRISM_V2SC_MOD_SUB_REGISTER_HPP

SC_MODULE(sub_register) {
  sc_in<bool> clk;
  sc_in<bool> rst_n;
  sc_in<bool> en;
  sc_in<sc_uint<8>> data_in;
  sc_out<sc_uint<8>> data_out;

  void always_ff_0() {
    auto __next_data_out = data_out.read();
    if ((!rst_n.read())) {
      __next_data_out = 0x00;
    } else {
      if (en.read()) {
        __next_data_out = data_in.read();
      }
    }
    data_out.write(__next_data_out);
  }

  SC_CTOR(sub_register) {
    SC_METHOD(always_ff_0);
    sensitive << clk.pos() << rst_n.neg();

  }
};

#endif  // PRISM_V2SC_MOD_SUB_REGISTER_HPP
