// Generated by prism_v2sc
#pragma once

#include <array>
#include <systemc>
#include <string>
#include <type_traits>

#include "../general/sirv_gnrl_dfflr__prism_p_e83a2e89d4.hpp"
#include "../general/sirv_gnrl_dffl__prism_p_eb7df2d8a4.hpp"
#include "../general/sirv_gnrl_dffl__prism_p_2d8e53ea17.hpp"
#include "../general/sirv_gnrl_dffl__prism_p_e83a2e89d4.hpp"

using namespace sc_core;
using namespace sc_dt;

#ifndef PRISM_V2SC_INTEGER_TYPES
#define PRISM_V2SC_INTEGER_TYPES
template <int Width> using prism_v2sc_uint_t = typename std::conditional<(Width <= 64), sc_uint<Width>, sc_biguint<Width>>::type;
template <int Width> using prism_v2sc_int_t = typename std::conditional<(Width <= 64), sc_int<Width>, sc_bigint<Width>>::type;
constexpr int prism_v2sc_clog2(int value) { int result = 0; for (int current = value - 1; current > 0; current >>= 1) ++result; return result; }
#endif

#ifndef PRISM_V2SC_MOD_E203_EXU_OITF_HPP
#define PRISM_V2SC_MOD_E203_EXU_OITF_HPP

SC_MODULE(e203_exu_oitf) {
  sc_out<bool> dis_ready;
  sc_in<bool> dis_ena;
  sc_in<bool> ret_ena;
  sc_out<sc_uint<1>> dis_ptr;
  sc_out<sc_uint<1>> ret_ptr;
  sc_out<sc_uint<5>> ret_rdidx;
  sc_out<bool> ret_rdwen;
  sc_out<bool> ret_rdfpu;
  sc_out<sc_uint<32>> ret_pc;
  sc_in<bool> disp_i_rs1en;
  sc_in<bool> disp_i_rs2en;
  sc_in<bool> disp_i_rs3en;
  sc_in<bool> disp_i_rdwen;
  sc_in<bool> disp_i_rs1fpu;
  sc_in<bool> disp_i_rs2fpu;
  sc_in<bool> disp_i_rs3fpu;
  sc_in<bool> disp_i_rdfpu;
  sc_in<sc_uint<5>> disp_i_rs1idx;
  sc_in<sc_uint<5>> disp_i_rs2idx;
  sc_in<sc_uint<5>> disp_i_rs3idx;
  sc_in<sc_uint<5>> disp_i_rdidx;
  sc_in<sc_uint<32>> disp_i_pc;
  sc_out<bool> oitfrd_match_disprs1;
  sc_out<bool> oitfrd_match_disprs2;
  sc_out<bool> oitfrd_match_disprs3;
  sc_out<bool> oitfrd_match_disprd;
  sc_out<bool> oitf_empty;
  sc_in<bool> clk;
  sc_in<bool> rst_n;

  sc_signal<bool> __shadow_rd_match_rdidx_0;
  sc_signal<bool> __shadow_rd_match_rdidx_1;
  sc_signal<bool> __shadow_rd_match_rs1idx_0;
  sc_signal<bool> __shadow_rd_match_rs1idx_1;
  sc_signal<bool> __shadow_rd_match_rs2idx_0;
  sc_signal<bool> __shadow_rd_match_rs2idx_1;
  sc_signal<bool> __shadow_rd_match_rs3idx_0;
  sc_signal<bool> __shadow_rd_match_rs3idx_1;
  sc_signal<bool> __shadow_vld_clr_0;
  sc_signal<bool> __shadow_vld_clr_1;
  sc_signal<bool> __shadow_vld_ena_0;
  sc_signal<bool> __shadow_vld_ena_1;
  sc_signal<bool> __shadow_vld_nxt_0;
  sc_signal<bool> __shadow_vld_nxt_1;
  sc_signal<bool> __shadow_vld_set_0;
  sc_signal<bool> __shadow_vld_set_1;
  sc_signal<sc_uint<2>> vld_set;
  sc_signal<sc_uint<2>> vld_clr;
  sc_signal<sc_uint<2>> vld_ena;
  sc_signal<sc_uint<2>> vld_nxt;
  sc_signal<sc_uint<2>> vld_r;
  sc_signal<sc_uint<2>> rdwen_r;
  sc_signal<sc_uint<2>> rdfpu_r;
  sc_signal<sc_uint<5>> rdidx_r[2];
  sc_signal<sc_uint<32>> pc_r[2];
  sc_signal<bool> alc_ptr_ena;
  sc_signal<bool> ret_ptr_ena;
  sc_signal<bool> oitf_full;
  sc_signal<sc_uint<1>> alc_ptr_r;
  sc_signal<sc_uint<1>> ret_ptr_r;
  sc_signal<bool> depth_gt1_alc_ptr_flg_r;
  sc_signal<bool> depth_gt1_alc_ptr_flg_nxt;
  sc_signal<bool> depth_gt1_alc_ptr_flg_ena;
  sc_signal<sc_uint<1>> depth_gt1_alc_ptr_nxt;
  sc_signal<bool> depth_gt1_ret_ptr_flg_r;
  sc_signal<bool> depth_gt1_ret_ptr_flg_nxt;
  sc_signal<bool> depth_gt1_ret_ptr_flg_ena;
  sc_signal<sc_uint<1>> depth_gt1_ret_ptr_nxt;
  sc_signal<sc_uint<2>> rd_match_rs1idx;
  sc_signal<sc_uint<2>> rd_match_rs2idx;
  sc_signal<sc_uint<2>> rd_match_rs3idx;
  sc_signal<sc_uint<2>> rd_match_rdidx;

  sirv_gnrl_dfflr__prism_p_e83a2e89d4<1> depth_gt1_alc_ptr_flg_dfflrs;
  sirv_gnrl_dfflr__prism_p_e83a2e89d4<1> depth_gt1_alc_ptr_dfflrs;
  sirv_gnrl_dfflr__prism_p_e83a2e89d4<1> depth_gt1_ret_ptr_flg_dfflrs;
  sirv_gnrl_dfflr__prism_p_e83a2e89d4<1> depth_gt1_ret_ptr_dfflrs;
  sirv_gnrl_dfflr__prism_p_e83a2e89d4<1> oitf_entries_0_vld_dfflrs;
  sirv_gnrl_dffl__prism_p_eb7df2d8a4<5> oitf_entries_0_rdidx_dfflrs;
  sirv_gnrl_dffl__prism_p_2d8e53ea17<32> oitf_entries_0_pc_dfflrs;
  sirv_gnrl_dffl__prism_p_e83a2e89d4<1> oitf_entries_0_rdwen_dfflrs;
  sirv_gnrl_dffl__prism_p_e83a2e89d4<1> oitf_entries_0_rdfpu_dfflrs;
  sirv_gnrl_dfflr__prism_p_e83a2e89d4<1> oitf_entries_1_vld_dfflrs;
  sirv_gnrl_dffl__prism_p_eb7df2d8a4<5> oitf_entries_1_rdidx_dfflrs;
  sirv_gnrl_dffl__prism_p_2d8e53ea17<32> oitf_entries_1_pc_dfflrs;
  sirv_gnrl_dffl__prism_p_e83a2e89d4<1> oitf_entries_1_rdwen_dfflrs;
  sirv_gnrl_dffl__prism_p_e83a2e89d4<1> oitf_entries_1_rdfpu_dfflrs;
  sc_signal<bool> __bridge_oitf_entries_0_vld_dfflrs_lden;
  sc_signal<sc_uint<1>> __bridge_oitf_entries_0_vld_dfflrs_dnxt;
  sc_signal<sc_uint<1>> __bridge_oitf_entries_0_vld_dfflrs_qout;
  sc_signal<bool> __bridge_oitf_entries_0_rdidx_dfflrs_lden;
  sc_signal<bool> __bridge_oitf_entries_0_pc_dfflrs_lden;
  sc_signal<bool> __bridge_oitf_entries_0_rdwen_dfflrs_lden;
  sc_signal<sc_uint<1>> __bridge_oitf_entries_0_rdwen_dfflrs_qout;
  sc_signal<bool> __bridge_oitf_entries_0_rdfpu_dfflrs_lden;
  sc_signal<sc_uint<1>> __bridge_oitf_entries_0_rdfpu_dfflrs_qout;
  sc_signal<bool> __bridge_oitf_entries_1_vld_dfflrs_lden;
  sc_signal<sc_uint<1>> __bridge_oitf_entries_1_vld_dfflrs_dnxt;
  sc_signal<sc_uint<1>> __bridge_oitf_entries_1_vld_dfflrs_qout;
  sc_signal<bool> __bridge_oitf_entries_1_rdidx_dfflrs_lden;
  sc_signal<bool> __bridge_oitf_entries_1_pc_dfflrs_lden;
  sc_signal<bool> __bridge_oitf_entries_1_rdwen_dfflrs_lden;
  sc_signal<sc_uint<1>> __bridge_oitf_entries_1_rdwen_dfflrs_qout;
  sc_signal<bool> __bridge_oitf_entries_1_rdfpu_dfflrs_lden;
  sc_signal<sc_uint<1>> __bridge_oitf_entries_1_rdfpu_dfflrs_qout;
  sc_signal<sc_uint<1>> __bridge_depth_gt1_alc_ptr_flg_dfflrs_dnxt;
  sc_signal<sc_uint<1>> __bridge_depth_gt1_alc_ptr_flg_dfflrs_qout;
  sc_signal<sc_uint<1>> __bridge_depth_gt1_ret_ptr_flg_dfflrs_dnxt;
  sc_signal<sc_uint<1>> __bridge_depth_gt1_ret_ptr_flg_dfflrs_qout;
  sc_signal<sc_uint<5>> __bridge_oitf_entries_0_rdidx_dfflrs_qout;
  sc_signal<sc_uint<32>> __bridge_oitf_entries_0_pc_dfflrs_qout;
  sc_signal<sc_uint<1>> __bridge_oitf_entries_0_rdwen_dfflrs_dnxt;
  sc_signal<sc_uint<1>> __bridge_oitf_entries_0_rdfpu_dfflrs_dnxt;
  sc_signal<sc_uint<5>> __bridge_oitf_entries_1_rdidx_dfflrs_qout;
  sc_signal<sc_uint<32>> __bridge_oitf_entries_1_pc_dfflrs_qout;
  sc_signal<sc_uint<1>> __bridge_oitf_entries_1_rdwen_dfflrs_dnxt;
  sc_signal<sc_uint<1>> __bridge_oitf_entries_1_rdfpu_dfflrs_dnxt;

  void assign_0() {
    alc_ptr_ena.write(dis_ena.read());
  }

  void assign_1() {
    ret_ptr_ena.write(ret_ena.read());
  }

  void assign_2() {
    depth_gt1_alc_ptr_flg_nxt.write((!depth_gt1_alc_ptr_flg_r.read()));
  }

  void assign_3() {
    depth_gt1_alc_ptr_flg_ena.write(((alc_ptr_r.read() == sc_uint<32>((2 - 1))) & alc_ptr_ena.read()));
  }

  void assign_4() {
    depth_gt1_alc_ptr_nxt.write((depth_gt1_alc_ptr_flg_ena.read() ? 0b0 : (alc_ptr_r.read() + 0b1)));
  }

  void assign_5() {
    depth_gt1_ret_ptr_flg_nxt.write((!depth_gt1_ret_ptr_flg_r.read()));
  }

  void assign_6() {
    depth_gt1_ret_ptr_flg_ena.write(((ret_ptr_r.read() == sc_uint<32>((2 - 1))) & ret_ptr_ena.read()));
  }

  void assign_7() {
    depth_gt1_ret_ptr_nxt.write((depth_gt1_ret_ptr_flg_ena.read() ? 0b0 : (ret_ptr_r.read() + 0b1)));
  }

  void assign_8() {
    oitf_empty.write(((ret_ptr_r.read() == alc_ptr_r.read()) & (depth_gt1_ret_ptr_flg_r.read() == depth_gt1_alc_ptr_flg_r.read())));
  }

  void assign_9() {
    oitf_full.write(((ret_ptr_r.read() == alc_ptr_r.read()) & (!(depth_gt1_ret_ptr_flg_r.read() == depth_gt1_alc_ptr_flg_r.read()))));
  }

  void assign_10() {
    ret_ptr.write(ret_ptr_r.read());
  }

  void assign_11() {
    dis_ptr.write(alc_ptr_r.read());
  }

  void assign_12() {
    dis_ready.write((!oitf_full.read()));
  }

  void assign_13() {
    __shadow_vld_set_0.write((alc_ptr_ena.read() & (alc_ptr_r.read() == 0)));
  }

  void assign_14() {
    __shadow_vld_clr_0.write((ret_ptr_ena.read() & (ret_ptr_r.read() == 0)));
  }

  void assign_15() {
    __shadow_vld_ena_0.write((vld_set.read()[0] | vld_clr.read()[0]));
  }

  void assign_16() {
    __shadow_vld_nxt_0.write((vld_set.read()[0] | (!vld_clr.read()[0])));
  }

  void assign_17() {
    __shadow_rd_match_rs1idx_0.write(((((vld_r.read()[0] & rdwen_r.read()[0]) & disp_i_rs1en.read()) & (rdfpu_r.read()[0] == disp_i_rs1fpu.read())) & (rdidx_r[0].read() == disp_i_rs1idx.read())));
  }

  void assign_18() {
    __shadow_rd_match_rs2idx_0.write(((((vld_r.read()[0] & rdwen_r.read()[0]) & disp_i_rs2en.read()) & (rdfpu_r.read()[0] == disp_i_rs2fpu.read())) & (rdidx_r[0].read() == disp_i_rs2idx.read())));
  }

  void assign_19() {
    __shadow_rd_match_rs3idx_0.write(((((vld_r.read()[0] & rdwen_r.read()[0]) & disp_i_rs3en.read()) & (rdfpu_r.read()[0] == disp_i_rs3fpu.read())) & (rdidx_r[0].read() == disp_i_rs3idx.read())));
  }

  void assign_20() {
    __shadow_rd_match_rdidx_0.write(((((vld_r.read()[0] & rdwen_r.read()[0]) & disp_i_rdwen.read()) & (rdfpu_r.read()[0] == disp_i_rdfpu.read())) & (rdidx_r[0].read() == disp_i_rdidx.read())));
  }

  void assign_21() {
    __shadow_vld_set_1.write((alc_ptr_ena.read() & (alc_ptr_r.read() == 1)));
  }

  void assign_22() {
    __shadow_vld_clr_1.write((ret_ptr_ena.read() & (ret_ptr_r.read() == 1)));
  }

  void assign_23() {
    __shadow_vld_ena_1.write((vld_set.read()[1] | vld_clr.read()[1]));
  }

  void assign_24() {
    __shadow_vld_nxt_1.write((vld_set.read()[1] | (!vld_clr.read()[1])));
  }

  void assign_25() {
    __shadow_rd_match_rs1idx_1.write(((((vld_r.read()[1] & rdwen_r.read()[1]) & disp_i_rs1en.read()) & (rdfpu_r.read()[1] == disp_i_rs1fpu.read())) & (rdidx_r[1].read() == disp_i_rs1idx.read())));
  }

  void assign_26() {
    __shadow_rd_match_rs2idx_1.write(((((vld_r.read()[1] & rdwen_r.read()[1]) & disp_i_rs2en.read()) & (rdfpu_r.read()[1] == disp_i_rs2fpu.read())) & (rdidx_r[1].read() == disp_i_rs2idx.read())));
  }

  void assign_27() {
    __shadow_rd_match_rs3idx_1.write(((((vld_r.read()[1] & rdwen_r.read()[1]) & disp_i_rs3en.read()) & (rdfpu_r.read()[1] == disp_i_rs3fpu.read())) & (rdidx_r[1].read() == disp_i_rs3idx.read())));
  }

  void assign_28() {
    __shadow_rd_match_rdidx_1.write(((((vld_r.read()[1] & rdwen_r.read()[1]) & disp_i_rdwen.read()) & (rdfpu_r.read()[1] == disp_i_rdfpu.read())) & (rdidx_r[1].read() == disp_i_rdidx.read())));
  }

  void assign_29() {
    oitfrd_match_disprs1.write(sc_uint<2>(rd_match_rs1idx.read()).or_reduce());
  }

  void assign_30() {
    oitfrd_match_disprs2.write(sc_uint<2>(rd_match_rs2idx.read()).or_reduce());
  }

  void assign_31() {
    oitfrd_match_disprs3.write(sc_uint<2>(rd_match_rs3idx.read()).or_reduce());
  }

  void assign_32() {
    oitfrd_match_disprd.write(sc_uint<2>(rd_match_rdidx.read()).or_reduce());
  }

  void assign_33() {
    ret_rdidx.write(rdidx_r[ret_ptr.read()].read());
  }

  void assign_34() {
    ret_pc.write(pc_r[ret_ptr.read()].read());
  }

  void assign_35() {
    ret_rdwen.write(rdwen_r.read()[ret_ptr.read()]);
  }

  void assign_36() {
    ret_rdfpu.write(rdfpu_r.read()[ret_ptr.read()]);
  }

  void __bridge_method_oitf_entries_0_vld_dfflrs_lden() {
    __bridge_oitf_entries_0_vld_dfflrs_lden.write(vld_ena.read()[0]);
  }

  void __bridge_method_oitf_entries_0_vld_dfflrs_dnxt() {
    __bridge_oitf_entries_0_vld_dfflrs_dnxt.write(sc_uint<1>(vld_nxt.read()[0]));
  }

  void __bridge_method_oitf_entries_0_rdidx_dfflrs_lden() {
    __bridge_oitf_entries_0_rdidx_dfflrs_lden.write(vld_set.read()[0]);
  }

  void __bridge_method_oitf_entries_0_pc_dfflrs_lden() {
    __bridge_oitf_entries_0_pc_dfflrs_lden.write(vld_set.read()[0]);
  }

  void __bridge_method_oitf_entries_0_rdwen_dfflrs_lden() {
    __bridge_oitf_entries_0_rdwen_dfflrs_lden.write(vld_set.read()[0]);
  }

  void __bridge_method_oitf_entries_0_rdfpu_dfflrs_lden() {
    __bridge_oitf_entries_0_rdfpu_dfflrs_lden.write(vld_set.read()[0]);
  }

  void __bridge_method_oitf_entries_1_vld_dfflrs_lden() {
    __bridge_oitf_entries_1_vld_dfflrs_lden.write(vld_ena.read()[1]);
  }

  void __bridge_method_oitf_entries_1_vld_dfflrs_dnxt() {
    __bridge_oitf_entries_1_vld_dfflrs_dnxt.write(sc_uint<1>(vld_nxt.read()[1]));
  }

  void __bridge_method_oitf_entries_1_rdidx_dfflrs_lden() {
    __bridge_oitf_entries_1_rdidx_dfflrs_lden.write(vld_set.read()[1]);
  }

  void __bridge_method_oitf_entries_1_pc_dfflrs_lden() {
    __bridge_oitf_entries_1_pc_dfflrs_lden.write(vld_set.read()[1]);
  }

  void __bridge_method_oitf_entries_1_rdwen_dfflrs_lden() {
    __bridge_oitf_entries_1_rdwen_dfflrs_lden.write(vld_set.read()[1]);
  }

  void __bridge_method_oitf_entries_1_rdfpu_dfflrs_lden() {
    __bridge_oitf_entries_1_rdfpu_dfflrs_lden.write(vld_set.read()[1]);
  }

  void __bridge_assemble_vld_r() {
    auto __tmp = vld_r.read();
    __tmp[0] = __bridge_oitf_entries_0_vld_dfflrs_qout.read()[0];
    __tmp[1] = __bridge_oitf_entries_1_vld_dfflrs_qout.read()[0];
    vld_r.write(__tmp);
  }

  void __bridge_assemble_rdwen_r() {
    auto __tmp = rdwen_r.read();
    __tmp[0] = __bridge_oitf_entries_0_rdwen_dfflrs_qout.read()[0];
    __tmp[1] = __bridge_oitf_entries_1_rdwen_dfflrs_qout.read()[0];
    rdwen_r.write(__tmp);
  }

  void __bridge_assemble_rdfpu_r() {
    auto __tmp = rdfpu_r.read();
    __tmp[0] = __bridge_oitf_entries_0_rdfpu_dfflrs_qout.read()[0];
    __tmp[1] = __bridge_oitf_entries_1_rdfpu_dfflrs_qout.read()[0];
    rdfpu_r.write(__tmp);
  }

  void __bridge_method_depth_gt1_alc_ptr_flg_dfflrs_dnxt() {
    __bridge_depth_gt1_alc_ptr_flg_dfflrs_dnxt.write(depth_gt1_alc_ptr_flg_nxt.read());
  }

  void __bridge_method_depth_gt1_alc_ptr_flg_dfflrs_qout() {
    depth_gt1_alc_ptr_flg_r.write(__bridge_depth_gt1_alc_ptr_flg_dfflrs_qout.read());
  }

  void __bridge_method_depth_gt1_ret_ptr_flg_dfflrs_dnxt() {
    __bridge_depth_gt1_ret_ptr_flg_dfflrs_dnxt.write(depth_gt1_ret_ptr_flg_nxt.read());
  }

  void __bridge_method_depth_gt1_ret_ptr_flg_dfflrs_qout() {
    depth_gt1_ret_ptr_flg_r.write(__bridge_depth_gt1_ret_ptr_flg_dfflrs_qout.read());
  }

  void __bridge_method_oitf_entries_0_rdidx_dfflrs_qout() {
    rdidx_r[0].write(sc_uint<5>(__bridge_oitf_entries_0_rdidx_dfflrs_qout.read()));
  }

  void __bridge_method_oitf_entries_0_pc_dfflrs_qout() {
    pc_r[0].write(sc_uint<32>(__bridge_oitf_entries_0_pc_dfflrs_qout.read()));
  }

  void __bridge_method_oitf_entries_0_rdwen_dfflrs_dnxt() {
    __bridge_oitf_entries_0_rdwen_dfflrs_dnxt.write(disp_i_rdwen.read());
  }

  void __bridge_method_oitf_entries_0_rdfpu_dfflrs_dnxt() {
    __bridge_oitf_entries_0_rdfpu_dfflrs_dnxt.write(disp_i_rdfpu.read());
  }

  void __bridge_method_oitf_entries_1_rdidx_dfflrs_qout() {
    rdidx_r[1].write(sc_uint<5>(__bridge_oitf_entries_1_rdidx_dfflrs_qout.read()));
  }

  void __bridge_method_oitf_entries_1_pc_dfflrs_qout() {
    pc_r[1].write(sc_uint<32>(__bridge_oitf_entries_1_pc_dfflrs_qout.read()));
  }

  void __bridge_method_oitf_entries_1_rdwen_dfflrs_dnxt() {
    __bridge_oitf_entries_1_rdwen_dfflrs_dnxt.write(disp_i_rdwen.read());
  }

  void __bridge_method_oitf_entries_1_rdfpu_dfflrs_dnxt() {
    __bridge_oitf_entries_1_rdfpu_dfflrs_dnxt.write(disp_i_rdfpu.read());
  }

  void __assemble_rd_match_rdidx() {
    auto __tmp = rd_match_rdidx.read();
    __tmp[0] = __shadow_rd_match_rdidx_0.read();
    __tmp[1] = __shadow_rd_match_rdidx_1.read();
    rd_match_rdidx.write(__tmp);
  }

  void __assemble_rd_match_rs1idx() {
    auto __tmp = rd_match_rs1idx.read();
    __tmp[0] = __shadow_rd_match_rs1idx_0.read();
    __tmp[1] = __shadow_rd_match_rs1idx_1.read();
    rd_match_rs1idx.write(__tmp);
  }

  void __assemble_rd_match_rs2idx() {
    auto __tmp = rd_match_rs2idx.read();
    __tmp[0] = __shadow_rd_match_rs2idx_0.read();
    __tmp[1] = __shadow_rd_match_rs2idx_1.read();
    rd_match_rs2idx.write(__tmp);
  }

  void __assemble_rd_match_rs3idx() {
    auto __tmp = rd_match_rs3idx.read();
    __tmp[0] = __shadow_rd_match_rs3idx_0.read();
    __tmp[1] = __shadow_rd_match_rs3idx_1.read();
    rd_match_rs3idx.write(__tmp);
  }

  void __assemble_vld_clr() {
    auto __tmp = vld_clr.read();
    __tmp[0] = __shadow_vld_clr_0.read();
    __tmp[1] = __shadow_vld_clr_1.read();
    vld_clr.write(__tmp);
  }

  void __assemble_vld_ena() {
    auto __tmp = vld_ena.read();
    __tmp[0] = __shadow_vld_ena_0.read();
    __tmp[1] = __shadow_vld_ena_1.read();
    vld_ena.write(__tmp);
  }

  void __assemble_vld_nxt() {
    auto __tmp = vld_nxt.read();
    __tmp[0] = __shadow_vld_nxt_0.read();
    __tmp[1] = __shadow_vld_nxt_1.read();
    vld_nxt.write(__tmp);
  }

  void __assemble_vld_set() {
    auto __tmp = vld_set.read();
    __tmp[0] = __shadow_vld_set_0.read();
    __tmp[1] = __shadow_vld_set_1.read();
    vld_set.write(__tmp);
  }

  SC_CTOR(e203_exu_oitf)
    : depth_gt1_alc_ptr_flg_dfflrs("depth_gt1_alc_ptr_flg_dfflrs"), depth_gt1_alc_ptr_dfflrs("depth_gt1_alc_ptr_dfflrs"), depth_gt1_ret_ptr_flg_dfflrs("depth_gt1_ret_ptr_flg_dfflrs"), depth_gt1_ret_ptr_dfflrs("depth_gt1_ret_ptr_dfflrs"), oitf_entries_0_vld_dfflrs("oitf_entries_0_vld_dfflrs"), oitf_entries_0_rdidx_dfflrs("oitf_entries_0_rdidx_dfflrs"), oitf_entries_0_pc_dfflrs("oitf_entries_0_pc_dfflrs"), oitf_entries_0_rdwen_dfflrs("oitf_entries_0_rdwen_dfflrs"), oitf_entries_0_rdfpu_dfflrs("oitf_entries_0_rdfpu_dfflrs"), oitf_entries_1_vld_dfflrs("oitf_entries_1_vld_dfflrs"), oitf_entries_1_rdidx_dfflrs("oitf_entries_1_rdidx_dfflrs"), oitf_entries_1_pc_dfflrs("oitf_entries_1_pc_dfflrs"), oitf_entries_1_rdwen_dfflrs("oitf_entries_1_rdwen_dfflrs"), oitf_entries_1_rdfpu_dfflrs("oitf_entries_1_rdfpu_dfflrs")
  {
    SC_METHOD(assign_0);
    sensitive << dis_ena;

    SC_METHOD(assign_1);
    sensitive << ret_ena;

    SC_METHOD(assign_2);
    sensitive << depth_gt1_alc_ptr_flg_r;

    SC_METHOD(assign_3);
    sensitive << alc_ptr_r << alc_ptr_ena;

    SC_METHOD(assign_4);
    sensitive << depth_gt1_alc_ptr_flg_ena << alc_ptr_r;

    SC_METHOD(assign_5);
    sensitive << depth_gt1_ret_ptr_flg_r;

    SC_METHOD(assign_6);
    sensitive << ret_ptr_r << ret_ptr_ena;

    SC_METHOD(assign_7);
    sensitive << depth_gt1_ret_ptr_flg_ena << ret_ptr_r;

    SC_METHOD(assign_8);
    sensitive << ret_ptr_r << alc_ptr_r << depth_gt1_ret_ptr_flg_r << depth_gt1_alc_ptr_flg_r;

    SC_METHOD(assign_9);
    sensitive << ret_ptr_r << alc_ptr_r << depth_gt1_ret_ptr_flg_r << depth_gt1_alc_ptr_flg_r;

    SC_METHOD(assign_10);
    sensitive << ret_ptr_r;

    SC_METHOD(assign_11);
    sensitive << alc_ptr_r;

    SC_METHOD(assign_12);
    sensitive << oitf_full;

    SC_METHOD(assign_13);
    sensitive << alc_ptr_ena << alc_ptr_r;

    SC_METHOD(assign_14);
    sensitive << ret_ptr_ena << ret_ptr_r;

    SC_METHOD(assign_15);
    sensitive << vld_set << vld_clr;

    SC_METHOD(assign_16);
    sensitive << vld_set << vld_clr;

    SC_METHOD(assign_17);
    sensitive << vld_r << rdwen_r << disp_i_rs1en << rdfpu_r << disp_i_rs1fpu << rdidx_r[0] << rdidx_r[1] << disp_i_rs1idx;

    SC_METHOD(assign_18);
    sensitive << vld_r << rdwen_r << disp_i_rs2en << rdfpu_r << disp_i_rs2fpu << rdidx_r[0] << rdidx_r[1] << disp_i_rs2idx;

    SC_METHOD(assign_19);
    sensitive << vld_r << rdwen_r << disp_i_rs3en << rdfpu_r << disp_i_rs3fpu << rdidx_r[0] << rdidx_r[1] << disp_i_rs3idx;

    SC_METHOD(assign_20);
    sensitive << vld_r << rdwen_r << disp_i_rdwen << rdfpu_r << disp_i_rdfpu << rdidx_r[0] << rdidx_r[1] << disp_i_rdidx;

    SC_METHOD(assign_21);
    sensitive << alc_ptr_ena << alc_ptr_r;

    SC_METHOD(assign_22);
    sensitive << ret_ptr_ena << ret_ptr_r;

    SC_METHOD(assign_23);
    sensitive << vld_set << vld_clr;

    SC_METHOD(assign_24);
    sensitive << vld_set << vld_clr;

    SC_METHOD(assign_25);
    sensitive << vld_r << rdwen_r << disp_i_rs1en << rdfpu_r << disp_i_rs1fpu << rdidx_r[0] << rdidx_r[1] << disp_i_rs1idx;

    SC_METHOD(assign_26);
    sensitive << vld_r << rdwen_r << disp_i_rs2en << rdfpu_r << disp_i_rs2fpu << rdidx_r[0] << rdidx_r[1] << disp_i_rs2idx;

    SC_METHOD(assign_27);
    sensitive << vld_r << rdwen_r << disp_i_rs3en << rdfpu_r << disp_i_rs3fpu << rdidx_r[0] << rdidx_r[1] << disp_i_rs3idx;

    SC_METHOD(assign_28);
    sensitive << vld_r << rdwen_r << disp_i_rdwen << rdfpu_r << disp_i_rdfpu << rdidx_r[0] << rdidx_r[1] << disp_i_rdidx;

    SC_METHOD(assign_29);
    sensitive << rd_match_rs1idx;

    SC_METHOD(assign_30);
    sensitive << rd_match_rs2idx;

    SC_METHOD(assign_31);
    sensitive << rd_match_rs3idx;

    SC_METHOD(assign_32);
    sensitive << rd_match_rdidx;

    SC_METHOD(assign_33);
    sensitive << rdidx_r[0] << rdidx_r[1] << ret_ptr;

    SC_METHOD(assign_34);
    sensitive << pc_r[0] << pc_r[1] << ret_ptr;

    SC_METHOD(assign_35);
    sensitive << rdwen_r << ret_ptr;

    SC_METHOD(assign_36);
    sensitive << rdfpu_r << ret_ptr;

    depth_gt1_alc_ptr_flg_dfflrs.lden(depth_gt1_alc_ptr_flg_ena);
    depth_gt1_alc_ptr_flg_dfflrs.dnxt(__bridge_depth_gt1_alc_ptr_flg_dfflrs_dnxt);
    depth_gt1_alc_ptr_flg_dfflrs.qout(__bridge_depth_gt1_alc_ptr_flg_dfflrs_qout);
    depth_gt1_alc_ptr_flg_dfflrs.clk(clk);
    depth_gt1_alc_ptr_flg_dfflrs.rst_n(rst_n);
    depth_gt1_alc_ptr_dfflrs.lden(alc_ptr_ena);
    depth_gt1_alc_ptr_dfflrs.dnxt(depth_gt1_alc_ptr_nxt);
    depth_gt1_alc_ptr_dfflrs.qout(alc_ptr_r);
    depth_gt1_alc_ptr_dfflrs.clk(clk);
    depth_gt1_alc_ptr_dfflrs.rst_n(rst_n);
    depth_gt1_ret_ptr_flg_dfflrs.lden(depth_gt1_ret_ptr_flg_ena);
    depth_gt1_ret_ptr_flg_dfflrs.dnxt(__bridge_depth_gt1_ret_ptr_flg_dfflrs_dnxt);
    depth_gt1_ret_ptr_flg_dfflrs.qout(__bridge_depth_gt1_ret_ptr_flg_dfflrs_qout);
    depth_gt1_ret_ptr_flg_dfflrs.clk(clk);
    depth_gt1_ret_ptr_flg_dfflrs.rst_n(rst_n);
    depth_gt1_ret_ptr_dfflrs.lden(ret_ptr_ena);
    depth_gt1_ret_ptr_dfflrs.dnxt(depth_gt1_ret_ptr_nxt);
    depth_gt1_ret_ptr_dfflrs.qout(ret_ptr_r);
    depth_gt1_ret_ptr_dfflrs.clk(clk);
    depth_gt1_ret_ptr_dfflrs.rst_n(rst_n);
    oitf_entries_0_vld_dfflrs.lden(__bridge_oitf_entries_0_vld_dfflrs_lden);
    oitf_entries_0_vld_dfflrs.dnxt(__bridge_oitf_entries_0_vld_dfflrs_dnxt);
    oitf_entries_0_vld_dfflrs.qout(__bridge_oitf_entries_0_vld_dfflrs_qout);
    oitf_entries_0_vld_dfflrs.clk(clk);
    oitf_entries_0_vld_dfflrs.rst_n(rst_n);
    oitf_entries_0_rdidx_dfflrs.lden(__bridge_oitf_entries_0_rdidx_dfflrs_lden);
    oitf_entries_0_rdidx_dfflrs.dnxt(disp_i_rdidx);
    oitf_entries_0_rdidx_dfflrs.qout(__bridge_oitf_entries_0_rdidx_dfflrs_qout);
    oitf_entries_0_rdidx_dfflrs.clk(clk);
    oitf_entries_0_pc_dfflrs.lden(__bridge_oitf_entries_0_pc_dfflrs_lden);
    oitf_entries_0_pc_dfflrs.dnxt(disp_i_pc);
    oitf_entries_0_pc_dfflrs.qout(__bridge_oitf_entries_0_pc_dfflrs_qout);
    oitf_entries_0_pc_dfflrs.clk(clk);
    oitf_entries_0_rdwen_dfflrs.lden(__bridge_oitf_entries_0_rdwen_dfflrs_lden);
    oitf_entries_0_rdwen_dfflrs.dnxt(__bridge_oitf_entries_0_rdwen_dfflrs_dnxt);
    oitf_entries_0_rdwen_dfflrs.qout(__bridge_oitf_entries_0_rdwen_dfflrs_qout);
    oitf_entries_0_rdwen_dfflrs.clk(clk);
    oitf_entries_0_rdfpu_dfflrs.lden(__bridge_oitf_entries_0_rdfpu_dfflrs_lden);
    oitf_entries_0_rdfpu_dfflrs.dnxt(__bridge_oitf_entries_0_rdfpu_dfflrs_dnxt);
    oitf_entries_0_rdfpu_dfflrs.qout(__bridge_oitf_entries_0_rdfpu_dfflrs_qout);
    oitf_entries_0_rdfpu_dfflrs.clk(clk);
    oitf_entries_1_vld_dfflrs.lden(__bridge_oitf_entries_1_vld_dfflrs_lden);
    oitf_entries_1_vld_dfflrs.dnxt(__bridge_oitf_entries_1_vld_dfflrs_dnxt);
    oitf_entries_1_vld_dfflrs.qout(__bridge_oitf_entries_1_vld_dfflrs_qout);
    oitf_entries_1_vld_dfflrs.clk(clk);
    oitf_entries_1_vld_dfflrs.rst_n(rst_n);
    oitf_entries_1_rdidx_dfflrs.lden(__bridge_oitf_entries_1_rdidx_dfflrs_lden);
    oitf_entries_1_rdidx_dfflrs.dnxt(disp_i_rdidx);
    oitf_entries_1_rdidx_dfflrs.qout(__bridge_oitf_entries_1_rdidx_dfflrs_qout);
    oitf_entries_1_rdidx_dfflrs.clk(clk);
    oitf_entries_1_pc_dfflrs.lden(__bridge_oitf_entries_1_pc_dfflrs_lden);
    oitf_entries_1_pc_dfflrs.dnxt(disp_i_pc);
    oitf_entries_1_pc_dfflrs.qout(__bridge_oitf_entries_1_pc_dfflrs_qout);
    oitf_entries_1_pc_dfflrs.clk(clk);
    oitf_entries_1_rdwen_dfflrs.lden(__bridge_oitf_entries_1_rdwen_dfflrs_lden);
    oitf_entries_1_rdwen_dfflrs.dnxt(__bridge_oitf_entries_1_rdwen_dfflrs_dnxt);
    oitf_entries_1_rdwen_dfflrs.qout(__bridge_oitf_entries_1_rdwen_dfflrs_qout);
    oitf_entries_1_rdwen_dfflrs.clk(clk);
    oitf_entries_1_rdfpu_dfflrs.lden(__bridge_oitf_entries_1_rdfpu_dfflrs_lden);
    oitf_entries_1_rdfpu_dfflrs.dnxt(__bridge_oitf_entries_1_rdfpu_dfflrs_dnxt);
    oitf_entries_1_rdfpu_dfflrs.qout(__bridge_oitf_entries_1_rdfpu_dfflrs_qout);
    oitf_entries_1_rdfpu_dfflrs.clk(clk);
    SC_METHOD(__bridge_method_oitf_entries_0_vld_dfflrs_lden);
    sensitive << vld_ena;

    SC_METHOD(__bridge_method_oitf_entries_0_vld_dfflrs_dnxt);
    sensitive << vld_nxt;

    SC_METHOD(__bridge_method_oitf_entries_0_rdidx_dfflrs_lden);
    sensitive << vld_set;

    SC_METHOD(__bridge_method_oitf_entries_0_pc_dfflrs_lden);
    sensitive << vld_set;

    SC_METHOD(__bridge_method_oitf_entries_0_rdwen_dfflrs_lden);
    sensitive << vld_set;

    SC_METHOD(__bridge_method_oitf_entries_0_rdfpu_dfflrs_lden);
    sensitive << vld_set;

    SC_METHOD(__bridge_method_oitf_entries_1_vld_dfflrs_lden);
    sensitive << vld_ena;

    SC_METHOD(__bridge_method_oitf_entries_1_vld_dfflrs_dnxt);
    sensitive << vld_nxt;

    SC_METHOD(__bridge_method_oitf_entries_1_rdidx_dfflrs_lden);
    sensitive << vld_set;

    SC_METHOD(__bridge_method_oitf_entries_1_pc_dfflrs_lden);
    sensitive << vld_set;

    SC_METHOD(__bridge_method_oitf_entries_1_rdwen_dfflrs_lden);
    sensitive << vld_set;

    SC_METHOD(__bridge_method_oitf_entries_1_rdfpu_dfflrs_lden);
    sensitive << vld_set;

    SC_METHOD(__bridge_assemble_vld_r);
    sensitive << __bridge_oitf_entries_0_vld_dfflrs_qout << __bridge_oitf_entries_1_vld_dfflrs_qout;

    SC_METHOD(__bridge_assemble_rdwen_r);
    sensitive << __bridge_oitf_entries_0_rdwen_dfflrs_qout << __bridge_oitf_entries_1_rdwen_dfflrs_qout;

    SC_METHOD(__bridge_assemble_rdfpu_r);
    sensitive << __bridge_oitf_entries_0_rdfpu_dfflrs_qout << __bridge_oitf_entries_1_rdfpu_dfflrs_qout;

    SC_METHOD(__bridge_method_depth_gt1_alc_ptr_flg_dfflrs_dnxt);
    sensitive << depth_gt1_alc_ptr_flg_nxt;

    SC_METHOD(__bridge_method_depth_gt1_alc_ptr_flg_dfflrs_qout);
    sensitive << __bridge_depth_gt1_alc_ptr_flg_dfflrs_qout;

    SC_METHOD(__bridge_method_depth_gt1_ret_ptr_flg_dfflrs_dnxt);
    sensitive << depth_gt1_ret_ptr_flg_nxt;

    SC_METHOD(__bridge_method_depth_gt1_ret_ptr_flg_dfflrs_qout);
    sensitive << __bridge_depth_gt1_ret_ptr_flg_dfflrs_qout;

    SC_METHOD(__bridge_method_oitf_entries_0_rdidx_dfflrs_qout);
    sensitive << __bridge_oitf_entries_0_rdidx_dfflrs_qout;

    SC_METHOD(__bridge_method_oitf_entries_0_pc_dfflrs_qout);
    sensitive << __bridge_oitf_entries_0_pc_dfflrs_qout;

    SC_METHOD(__bridge_method_oitf_entries_0_rdwen_dfflrs_dnxt);
    sensitive << disp_i_rdwen;

    SC_METHOD(__bridge_method_oitf_entries_0_rdfpu_dfflrs_dnxt);
    sensitive << disp_i_rdfpu;

    SC_METHOD(__bridge_method_oitf_entries_1_rdidx_dfflrs_qout);
    sensitive << __bridge_oitf_entries_1_rdidx_dfflrs_qout;

    SC_METHOD(__bridge_method_oitf_entries_1_pc_dfflrs_qout);
    sensitive << __bridge_oitf_entries_1_pc_dfflrs_qout;

    SC_METHOD(__bridge_method_oitf_entries_1_rdwen_dfflrs_dnxt);
    sensitive << disp_i_rdwen;

    SC_METHOD(__bridge_method_oitf_entries_1_rdfpu_dfflrs_dnxt);
    sensitive << disp_i_rdfpu;

    SC_METHOD(__assemble_rd_match_rdidx);
    sensitive << __shadow_rd_match_rdidx_0 << __shadow_rd_match_rdidx_1;

    SC_METHOD(__assemble_rd_match_rs1idx);
    sensitive << __shadow_rd_match_rs1idx_0 << __shadow_rd_match_rs1idx_1;

    SC_METHOD(__assemble_rd_match_rs2idx);
    sensitive << __shadow_rd_match_rs2idx_0 << __shadow_rd_match_rs2idx_1;

    SC_METHOD(__assemble_rd_match_rs3idx);
    sensitive << __shadow_rd_match_rs3idx_0 << __shadow_rd_match_rs3idx_1;

    SC_METHOD(__assemble_vld_clr);
    sensitive << __shadow_vld_clr_0 << __shadow_vld_clr_1;

    SC_METHOD(__assemble_vld_ena);
    sensitive << __shadow_vld_ena_0 << __shadow_vld_ena_1;

    SC_METHOD(__assemble_vld_nxt);
    sensitive << __shadow_vld_nxt_0 << __shadow_vld_nxt_1;

    SC_METHOD(__assemble_vld_set);
    sensitive << __shadow_vld_set_0 << __shadow_vld_set_1;

  }
};

#endif  // PRISM_V2SC_MOD_E203_EXU_OITF_HPP
