// Generated by prism_v2sc
#pragma once

#include <array>
#include <systemc>
#include <string>
#include <type_traits>

#include "../general/sirv_gnrl_fifo__prism_p_4fc96458cb.hpp"

using namespace sc_core;
using namespace sc_dt;

#ifndef PRISM_V2SC_INTEGER_TYPES
#define PRISM_V2SC_INTEGER_TYPES
template <int Width> using prism_v2sc_uint_t = typename std::conditional<(Width <= 64), sc_uint<Width>, sc_biguint<Width>>::type;
template <int Width> using prism_v2sc_int_t = typename std::conditional<(Width <= 64), sc_int<Width>, sc_bigint<Width>>::type;
constexpr int prism_v2sc_clog2(int value) { int result = 0; for (int current = value - 1; current > 0; current >>= 1) ++result; return result; }
#endif

#ifndef PRISM_V2SC_MOD_E203_EXU_NICE_HPP
#define PRISM_V2SC_MOD_E203_EXU_NICE_HPP

SC_MODULE(e203_exu_nice) {
  sc_in<bool> nice_i_xs_off;
  sc_in<bool> nice_i_valid;
  sc_out<bool> nice_i_ready;
  sc_in<sc_uint<32>> nice_i_instr;
  sc_in<sc_uint<32>> nice_i_rs1;
  sc_in<sc_uint<32>> nice_i_rs2;
  sc_in<sc_uint<1>> nice_i_itag;
  sc_out<bool> nice_o_longpipe;
  sc_out<bool> nice_o_valid;
  sc_in<bool> nice_o_ready;
  sc_out<bool> nice_o_itag_valid;
  sc_in<bool> nice_o_itag_ready;
  sc_out<sc_uint<1>> nice_o_itag;
  sc_in<bool> nice_rsp_multicyc_valid;
  sc_out<bool> nice_rsp_multicyc_ready;
  sc_out<bool> nice_req_valid;
  sc_in<bool> nice_req_ready;
  sc_out<sc_uint<32>> nice_req_instr;
  sc_out<sc_uint<32>> nice_req_rs1;
  sc_out<sc_uint<32>> nice_req_rs2;
  sc_in<bool> clk;
  sc_in<bool> rst_n;

  sc_signal<bool> nice_i_hsked;
  sc_signal<bool> nice_req_valid_pos;
  sc_signal<bool> nice_req_ready_pos;
  sc_signal<bool> fifo_o_vld;
  sc_signal<bool> itag_fifo_wen;
  sc_signal<bool> itag_fifo_ren;
  sc_signal<bool> fifo_i_vld;
  sc_signal<bool> fifo_i_rdy;
  sc_signal<sc_uint<1>> fifo_i_dat;
  sc_signal<bool> fifo_o_rdy;
  sc_signal<sc_uint<1>> fifo_o_dat;

  sirv_gnrl_fifo__prism_p_4fc96458cb<1, 0, 4, 1> u_nice_itag_fifo;

  void assign_0() {
    nice_i_hsked.write((nice_i_valid.read() & nice_i_ready.read()));
  }

  void assign_1() {
    nice_req_valid_pos.write((nice_i_valid.read() & nice_o_ready.read()));
  }

  void assign_2() {
    nice_req_valid.write(((!nice_i_xs_off.read()) & nice_req_valid_pos.read()));
  }

  void assign_3() {
    nice_req_ready_pos.write((nice_i_xs_off.read() ? 0b1 : nice_req_ready.read()));
  }

  void assign_4() {
    nice_i_ready.write((nice_req_ready_pos.read() & nice_o_ready.read()));
  }

  void assign_5() {
    nice_o_valid.write((nice_i_valid.read() & nice_req_ready_pos.read()));
  }

  void assign_6() {
    nice_rsp_multicyc_ready.write((nice_o_itag_ready.read() & fifo_o_vld.read()));
  }

  void assign_7() {
    nice_req_instr.write(nice_i_instr.read());
  }

  void assign_8() {
    nice_req_rs1.write(nice_i_rs1.read());
  }

  void assign_9() {
    nice_req_rs2.write(nice_i_rs2.read());
  }

  void assign_10() {
    nice_o_longpipe.write((!nice_i_xs_off.read()));
  }

  void assign_11() {
    itag_fifo_wen.write((nice_o_longpipe.read() & (nice_req_valid.read() & nice_req_ready.read())));
  }

  void assign_12() {
    itag_fifo_ren.write((nice_rsp_multicyc_valid.read() & nice_rsp_multicyc_ready.read()));
  }

  void assign_13() {
    fifo_i_vld.write(itag_fifo_wen.read());
  }

  void assign_14() {
    fifo_i_dat.write(nice_i_itag.read());
  }

  void assign_15() {
    fifo_o_rdy.write(itag_fifo_ren.read());
  }

  void assign_16() {
    nice_o_itag_valid.write((fifo_o_vld.read() & nice_rsp_multicyc_valid.read()));
  }

  void assign_17() {
    nice_o_itag.write(fifo_o_dat.read());
  }

  SC_CTOR(e203_exu_nice)
    : u_nice_itag_fifo("u_nice_itag_fifo")
  {
    SC_METHOD(assign_0);
    sensitive << nice_i_valid << nice_i_ready;

    SC_METHOD(assign_1);
    sensitive << nice_i_valid << nice_o_ready;

    SC_METHOD(assign_2);
    sensitive << nice_i_xs_off << nice_req_valid_pos;

    SC_METHOD(assign_3);
    sensitive << nice_i_xs_off << nice_req_ready;

    SC_METHOD(assign_4);
    sensitive << nice_req_ready_pos << nice_o_ready;

    SC_METHOD(assign_5);
    sensitive << nice_i_valid << nice_req_ready_pos;

    SC_METHOD(assign_6);
    sensitive << nice_o_itag_ready << fifo_o_vld;

    SC_METHOD(assign_7);
    sensitive << nice_i_instr;

    SC_METHOD(assign_8);
    sensitive << nice_i_rs1;

    SC_METHOD(assign_9);
    sensitive << nice_i_rs2;

    SC_METHOD(assign_10);
    sensitive << nice_i_xs_off;

    SC_METHOD(assign_11);
    sensitive << nice_o_longpipe << nice_req_valid << nice_req_ready;

    SC_METHOD(assign_12);
    sensitive << nice_rsp_multicyc_valid << nice_rsp_multicyc_ready;

    SC_METHOD(assign_13);
    sensitive << itag_fifo_wen;

    SC_METHOD(assign_14);
    sensitive << nice_i_itag;

    SC_METHOD(assign_15);
    sensitive << itag_fifo_ren;

    SC_METHOD(assign_16);
    sensitive << fifo_o_vld << nice_rsp_multicyc_valid;

    SC_METHOD(assign_17);
    sensitive << fifo_o_dat;

    u_nice_itag_fifo.i_vld(fifo_i_vld);
    u_nice_itag_fifo.i_rdy(fifo_i_rdy);
    u_nice_itag_fifo.i_dat(fifo_i_dat);
    u_nice_itag_fifo.o_vld(fifo_o_vld);
    u_nice_itag_fifo.o_rdy(fifo_o_rdy);
    u_nice_itag_fifo.o_dat(fifo_o_dat);
    u_nice_itag_fifo.clk(clk);
    u_nice_itag_fifo.rst_n(rst_n);
  }
};

#endif  // PRISM_V2SC_MOD_E203_EXU_NICE_HPP
