// Generated by prism_v2sc
#pragma once

#include <array>
#include <systemc>
#include <string>
#include <type_traits>

#include "../general/sirv_gnrl_dffl__prism_p_2d8e53ea17.hpp"

using namespace sc_core;
using namespace sc_dt;

#ifndef PRISM_V2SC_INTEGER_TYPES
#define PRISM_V2SC_INTEGER_TYPES
template <int Width> using prism_v2sc_uint_t = typename std::conditional<(Width <= 64), sc_uint<Width>, sc_biguint<Width>>::type;
template <int Width> using prism_v2sc_int_t = typename std::conditional<(Width <= 64), sc_int<Width>, sc_bigint<Width>>::type;
constexpr int prism_v2sc_clog2(int value) { int result = 0; for (int current = value - 1; current > 0; current >>= 1) ++result; return result; }
#endif

#ifndef PRISM_V2SC_MOD_E203_EXU_REGFILE_HPP
#define PRISM_V2SC_MOD_E203_EXU_REGFILE_HPP

SC_MODULE(e203_exu_regfile) {
  sc_in<sc_uint<5>> read_src1_idx;
  sc_in<sc_uint<5>> read_src2_idx;
  sc_out<sc_uint<32>> read_src1_dat;
  sc_out<sc_uint<32>> read_src2_dat;
  sc_in<bool> wbck_dest_wen;
  sc_in<sc_uint<5>> wbck_dest_idx;
  sc_in<sc_uint<32>> wbck_dest_dat;
  sc_out<sc_uint<32>> x1_r;
  sc_in<bool> test_mode;
  sc_in<bool> clk;
  sc_in<bool> rst_n;

  sc_signal<bool> __shadow_rf_wen_0;
  sc_signal<bool> __shadow_rf_wen_1;
  sc_signal<bool> __shadow_rf_wen_2;
  sc_signal<bool> __shadow_rf_wen_3;
  sc_signal<bool> __shadow_rf_wen_4;
  sc_signal<bool> __shadow_rf_wen_5;
  sc_signal<bool> __shadow_rf_wen_6;
  sc_signal<bool> __shadow_rf_wen_7;
  sc_signal<bool> __shadow_rf_wen_8;
  sc_signal<bool> __shadow_rf_wen_9;
  sc_signal<bool> __shadow_rf_wen_10;
  sc_signal<bool> __shadow_rf_wen_11;
  sc_signal<bool> __shadow_rf_wen_12;
  sc_signal<bool> __shadow_rf_wen_13;
  sc_signal<bool> __shadow_rf_wen_14;
  sc_signal<bool> __shadow_rf_wen_15;
  sc_signal<bool> __shadow_rf_wen_16;
  sc_signal<bool> __shadow_rf_wen_17;
  sc_signal<bool> __shadow_rf_wen_18;
  sc_signal<bool> __shadow_rf_wen_19;
  sc_signal<bool> __shadow_rf_wen_20;
  sc_signal<bool> __shadow_rf_wen_21;
  sc_signal<bool> __shadow_rf_wen_22;
  sc_signal<bool> __shadow_rf_wen_23;
  sc_signal<bool> __shadow_rf_wen_24;
  sc_signal<bool> __shadow_rf_wen_25;
  sc_signal<bool> __shadow_rf_wen_26;
  sc_signal<bool> __shadow_rf_wen_27;
  sc_signal<bool> __shadow_rf_wen_28;
  sc_signal<bool> __shadow_rf_wen_29;
  sc_signal<bool> __shadow_rf_wen_30;
  sc_signal<bool> __shadow_rf_wen_31;
  sc_signal<sc_uint<32>> rf_r[32];
  sc_signal<sc_uint<32>> rf_wen;

  sirv_gnrl_dffl__prism_p_2d8e53ea17<32> regfile_1_rfno0_rf_dffl;
  sirv_gnrl_dffl__prism_p_2d8e53ea17<32> regfile_2_rfno0_rf_dffl;
  sirv_gnrl_dffl__prism_p_2d8e53ea17<32> regfile_3_rfno0_rf_dffl;
  sirv_gnrl_dffl__prism_p_2d8e53ea17<32> regfile_4_rfno0_rf_dffl;
  sirv_gnrl_dffl__prism_p_2d8e53ea17<32> regfile_5_rfno0_rf_dffl;
  sirv_gnrl_dffl__prism_p_2d8e53ea17<32> regfile_6_rfno0_rf_dffl;
  sirv_gnrl_dffl__prism_p_2d8e53ea17<32> regfile_7_rfno0_rf_dffl;
  sirv_gnrl_dffl__prism_p_2d8e53ea17<32> regfile_8_rfno0_rf_dffl;
  sirv_gnrl_dffl__prism_p_2d8e53ea17<32> regfile_9_rfno0_rf_dffl;
  sirv_gnrl_dffl__prism_p_2d8e53ea17<32> regfile_10_rfno0_rf_dffl;
  sirv_gnrl_dffl__prism_p_2d8e53ea17<32> regfile_11_rfno0_rf_dffl;
  sirv_gnrl_dffl__prism_p_2d8e53ea17<32> regfile_12_rfno0_rf_dffl;
  sirv_gnrl_dffl__prism_p_2d8e53ea17<32> regfile_13_rfno0_rf_dffl;
  sirv_gnrl_dffl__prism_p_2d8e53ea17<32> regfile_14_rfno0_rf_dffl;
  sirv_gnrl_dffl__prism_p_2d8e53ea17<32> regfile_15_rfno0_rf_dffl;
  sirv_gnrl_dffl__prism_p_2d8e53ea17<32> regfile_16_rfno0_rf_dffl;
  sirv_gnrl_dffl__prism_p_2d8e53ea17<32> regfile_17_rfno0_rf_dffl;
  sirv_gnrl_dffl__prism_p_2d8e53ea17<32> regfile_18_rfno0_rf_dffl;
  sirv_gnrl_dffl__prism_p_2d8e53ea17<32> regfile_19_rfno0_rf_dffl;
  sirv_gnrl_dffl__prism_p_2d8e53ea17<32> regfile_20_rfno0_rf_dffl;
  sirv_gnrl_dffl__prism_p_2d8e53ea17<32> regfile_21_rfno0_rf_dffl;
  sirv_gnrl_dffl__prism_p_2d8e53ea17<32> regfile_22_rfno0_rf_dffl;
  sirv_gnrl_dffl__prism_p_2d8e53ea17<32> regfile_23_rfno0_rf_dffl;
  sirv_gnrl_dffl__prism_p_2d8e53ea17<32> regfile_24_rfno0_rf_dffl;
  sirv_gnrl_dffl__prism_p_2d8e53ea17<32> regfile_25_rfno0_rf_dffl;
  sirv_gnrl_dffl__prism_p_2d8e53ea17<32> regfile_26_rfno0_rf_dffl;
  sirv_gnrl_dffl__prism_p_2d8e53ea17<32> regfile_27_rfno0_rf_dffl;
  sirv_gnrl_dffl__prism_p_2d8e53ea17<32> regfile_28_rfno0_rf_dffl;
  sirv_gnrl_dffl__prism_p_2d8e53ea17<32> regfile_29_rfno0_rf_dffl;
  sirv_gnrl_dffl__prism_p_2d8e53ea17<32> regfile_30_rfno0_rf_dffl;
  sirv_gnrl_dffl__prism_p_2d8e53ea17<32> regfile_31_rfno0_rf_dffl;
  sc_signal<bool> __bridge_regfile_1_rfno0_rf_dffl_lden;
  sc_signal<bool> __bridge_regfile_2_rfno0_rf_dffl_lden;
  sc_signal<bool> __bridge_regfile_3_rfno0_rf_dffl_lden;
  sc_signal<bool> __bridge_regfile_4_rfno0_rf_dffl_lden;
  sc_signal<bool> __bridge_regfile_5_rfno0_rf_dffl_lden;
  sc_signal<bool> __bridge_regfile_6_rfno0_rf_dffl_lden;
  sc_signal<bool> __bridge_regfile_7_rfno0_rf_dffl_lden;
  sc_signal<bool> __bridge_regfile_8_rfno0_rf_dffl_lden;
  sc_signal<bool> __bridge_regfile_9_rfno0_rf_dffl_lden;
  sc_signal<bool> __bridge_regfile_10_rfno0_rf_dffl_lden;
  sc_signal<bool> __bridge_regfile_11_rfno0_rf_dffl_lden;
  sc_signal<bool> __bridge_regfile_12_rfno0_rf_dffl_lden;
  sc_signal<bool> __bridge_regfile_13_rfno0_rf_dffl_lden;
  sc_signal<bool> __bridge_regfile_14_rfno0_rf_dffl_lden;
  sc_signal<bool> __bridge_regfile_15_rfno0_rf_dffl_lden;
  sc_signal<bool> __bridge_regfile_16_rfno0_rf_dffl_lden;
  sc_signal<bool> __bridge_regfile_17_rfno0_rf_dffl_lden;
  sc_signal<bool> __bridge_regfile_18_rfno0_rf_dffl_lden;
  sc_signal<bool> __bridge_regfile_19_rfno0_rf_dffl_lden;
  sc_signal<bool> __bridge_regfile_20_rfno0_rf_dffl_lden;
  sc_signal<bool> __bridge_regfile_21_rfno0_rf_dffl_lden;
  sc_signal<bool> __bridge_regfile_22_rfno0_rf_dffl_lden;
  sc_signal<bool> __bridge_regfile_23_rfno0_rf_dffl_lden;
  sc_signal<bool> __bridge_regfile_24_rfno0_rf_dffl_lden;
  sc_signal<bool> __bridge_regfile_25_rfno0_rf_dffl_lden;
  sc_signal<bool> __bridge_regfile_26_rfno0_rf_dffl_lden;
  sc_signal<bool> __bridge_regfile_27_rfno0_rf_dffl_lden;
  sc_signal<bool> __bridge_regfile_28_rfno0_rf_dffl_lden;
  sc_signal<bool> __bridge_regfile_29_rfno0_rf_dffl_lden;
  sc_signal<bool> __bridge_regfile_30_rfno0_rf_dffl_lden;
  sc_signal<bool> __bridge_regfile_31_rfno0_rf_dffl_lden;
  sc_signal<sc_uint<32>> __bridge_regfile_1_rfno0_rf_dffl_qout;
  sc_signal<sc_uint<32>> __bridge_regfile_2_rfno0_rf_dffl_qout;
  sc_signal<sc_uint<32>> __bridge_regfile_3_rfno0_rf_dffl_qout;
  sc_signal<sc_uint<32>> __bridge_regfile_4_rfno0_rf_dffl_qout;
  sc_signal<sc_uint<32>> __bridge_regfile_5_rfno0_rf_dffl_qout;
  sc_signal<sc_uint<32>> __bridge_regfile_6_rfno0_rf_dffl_qout;
  sc_signal<sc_uint<32>> __bridge_regfile_7_rfno0_rf_dffl_qout;
  sc_signal<sc_uint<32>> __bridge_regfile_8_rfno0_rf_dffl_qout;
  sc_signal<sc_uint<32>> __bridge_regfile_9_rfno0_rf_dffl_qout;
  sc_signal<sc_uint<32>> __bridge_regfile_10_rfno0_rf_dffl_qout;
  sc_signal<sc_uint<32>> __bridge_regfile_11_rfno0_rf_dffl_qout;
  sc_signal<sc_uint<32>> __bridge_regfile_12_rfno0_rf_dffl_qout;
  sc_signal<sc_uint<32>> __bridge_regfile_13_rfno0_rf_dffl_qout;
  sc_signal<sc_uint<32>> __bridge_regfile_14_rfno0_rf_dffl_qout;
  sc_signal<sc_uint<32>> __bridge_regfile_15_rfno0_rf_dffl_qout;
  sc_signal<sc_uint<32>> __bridge_regfile_16_rfno0_rf_dffl_qout;
  sc_signal<sc_uint<32>> __bridge_regfile_17_rfno0_rf_dffl_qout;
  sc_signal<sc_uint<32>> __bridge_regfile_18_rfno0_rf_dffl_qout;
  sc_signal<sc_uint<32>> __bridge_regfile_19_rfno0_rf_dffl_qout;
  sc_signal<sc_uint<32>> __bridge_regfile_20_rfno0_rf_dffl_qout;
  sc_signal<sc_uint<32>> __bridge_regfile_21_rfno0_rf_dffl_qout;
  sc_signal<sc_uint<32>> __bridge_regfile_22_rfno0_rf_dffl_qout;
  sc_signal<sc_uint<32>> __bridge_regfile_23_rfno0_rf_dffl_qout;
  sc_signal<sc_uint<32>> __bridge_regfile_24_rfno0_rf_dffl_qout;
  sc_signal<sc_uint<32>> __bridge_regfile_25_rfno0_rf_dffl_qout;
  sc_signal<sc_uint<32>> __bridge_regfile_26_rfno0_rf_dffl_qout;
  sc_signal<sc_uint<32>> __bridge_regfile_27_rfno0_rf_dffl_qout;
  sc_signal<sc_uint<32>> __bridge_regfile_28_rfno0_rf_dffl_qout;
  sc_signal<sc_uint<32>> __bridge_regfile_29_rfno0_rf_dffl_qout;
  sc_signal<sc_uint<32>> __bridge_regfile_30_rfno0_rf_dffl_qout;
  sc_signal<sc_uint<32>> __bridge_regfile_31_rfno0_rf_dffl_qout;

  void assign_0() {
    __shadow_rf_wen_0.write(0b0);
  }

  void assign_1() {
    rf_r[0].write(0b0);
  }

  void assign_2() {
    __shadow_rf_wen_1.write((wbck_dest_wen.read() & (wbck_dest_idx.read() == 1)));
  }

  void assign_3() {
    __shadow_rf_wen_2.write((wbck_dest_wen.read() & (wbck_dest_idx.read() == 2)));
  }

  void assign_4() {
    __shadow_rf_wen_3.write((wbck_dest_wen.read() & (wbck_dest_idx.read() == 3)));
  }

  void assign_5() {
    __shadow_rf_wen_4.write((wbck_dest_wen.read() & (wbck_dest_idx.read() == 4)));
  }

  void assign_6() {
    __shadow_rf_wen_5.write((wbck_dest_wen.read() & (wbck_dest_idx.read() == 5)));
  }

  void assign_7() {
    __shadow_rf_wen_6.write((wbck_dest_wen.read() & (wbck_dest_idx.read() == 6)));
  }

  void assign_8() {
    __shadow_rf_wen_7.write((wbck_dest_wen.read() & (wbck_dest_idx.read() == 7)));
  }

  void assign_9() {
    __shadow_rf_wen_8.write((wbck_dest_wen.read() & (wbck_dest_idx.read() == 8)));
  }

  void assign_10() {
    __shadow_rf_wen_9.write((wbck_dest_wen.read() & (wbck_dest_idx.read() == 9)));
  }

  void assign_11() {
    __shadow_rf_wen_10.write((wbck_dest_wen.read() & (wbck_dest_idx.read() == 10)));
  }

  void assign_12() {
    __shadow_rf_wen_11.write((wbck_dest_wen.read() & (wbck_dest_idx.read() == 11)));
  }

  void assign_13() {
    __shadow_rf_wen_12.write((wbck_dest_wen.read() & (wbck_dest_idx.read() == 12)));
  }

  void assign_14() {
    __shadow_rf_wen_13.write((wbck_dest_wen.read() & (wbck_dest_idx.read() == 13)));
  }

  void assign_15() {
    __shadow_rf_wen_14.write((wbck_dest_wen.read() & (wbck_dest_idx.read() == 14)));
  }

  void assign_16() {
    __shadow_rf_wen_15.write((wbck_dest_wen.read() & (wbck_dest_idx.read() == 15)));
  }

  void assign_17() {
    __shadow_rf_wen_16.write((wbck_dest_wen.read() & (wbck_dest_idx.read() == 16)));
  }

  void assign_18() {
    __shadow_rf_wen_17.write((wbck_dest_wen.read() & (wbck_dest_idx.read() == 17)));
  }

  void assign_19() {
    __shadow_rf_wen_18.write((wbck_dest_wen.read() & (wbck_dest_idx.read() == 18)));
  }

  void assign_20() {
    __shadow_rf_wen_19.write((wbck_dest_wen.read() & (wbck_dest_idx.read() == 19)));
  }

  void assign_21() {
    __shadow_rf_wen_20.write((wbck_dest_wen.read() & (wbck_dest_idx.read() == 20)));
  }

  void assign_22() {
    __shadow_rf_wen_21.write((wbck_dest_wen.read() & (wbck_dest_idx.read() == 21)));
  }

  void assign_23() {
    __shadow_rf_wen_22.write((wbck_dest_wen.read() & (wbck_dest_idx.read() == 22)));
  }

  void assign_24() {
    __shadow_rf_wen_23.write((wbck_dest_wen.read() & (wbck_dest_idx.read() == 23)));
  }

  void assign_25() {
    __shadow_rf_wen_24.write((wbck_dest_wen.read() & (wbck_dest_idx.read() == 24)));
  }

  void assign_26() {
    __shadow_rf_wen_25.write((wbck_dest_wen.read() & (wbck_dest_idx.read() == 25)));
  }

  void assign_27() {
    __shadow_rf_wen_26.write((wbck_dest_wen.read() & (wbck_dest_idx.read() == 26)));
  }

  void assign_28() {
    __shadow_rf_wen_27.write((wbck_dest_wen.read() & (wbck_dest_idx.read() == 27)));
  }

  void assign_29() {
    __shadow_rf_wen_28.write((wbck_dest_wen.read() & (wbck_dest_idx.read() == 28)));
  }

  void assign_30() {
    __shadow_rf_wen_29.write((wbck_dest_wen.read() & (wbck_dest_idx.read() == 29)));
  }

  void assign_31() {
    __shadow_rf_wen_30.write((wbck_dest_wen.read() & (wbck_dest_idx.read() == 30)));
  }

  void assign_32() {
    __shadow_rf_wen_31.write((wbck_dest_wen.read() & (wbck_dest_idx.read() == 31)));
  }

  void assign_33() {
    read_src1_dat.write(rf_r[read_src1_idx.read()].read());
  }

  void assign_34() {
    read_src2_dat.write(rf_r[read_src2_idx.read()].read());
  }

  void assign_35() {
    x1_r.write(rf_r[1].read());
  }

  void __bridge_method_regfile_1_rfno0_rf_dffl_lden() {
    __bridge_regfile_1_rfno0_rf_dffl_lden.write(rf_wen.read()[1]);
  }

  void __bridge_method_regfile_2_rfno0_rf_dffl_lden() {
    __bridge_regfile_2_rfno0_rf_dffl_lden.write(rf_wen.read()[2]);
  }

  void __bridge_method_regfile_3_rfno0_rf_dffl_lden() {
    __bridge_regfile_3_rfno0_rf_dffl_lden.write(rf_wen.read()[3]);
  }

  void __bridge_method_regfile_4_rfno0_rf_dffl_lden() {
    __bridge_regfile_4_rfno0_rf_dffl_lden.write(rf_wen.read()[4]);
  }

  void __bridge_method_regfile_5_rfno0_rf_dffl_lden() {
    __bridge_regfile_5_rfno0_rf_dffl_lden.write(rf_wen.read()[5]);
  }

  void __bridge_method_regfile_6_rfno0_rf_dffl_lden() {
    __bridge_regfile_6_rfno0_rf_dffl_lden.write(rf_wen.read()[6]);
  }

  void __bridge_method_regfile_7_rfno0_rf_dffl_lden() {
    __bridge_regfile_7_rfno0_rf_dffl_lden.write(rf_wen.read()[7]);
  }

  void __bridge_method_regfile_8_rfno0_rf_dffl_lden() {
    __bridge_regfile_8_rfno0_rf_dffl_lden.write(rf_wen.read()[8]);
  }

  void __bridge_method_regfile_9_rfno0_rf_dffl_lden() {
    __bridge_regfile_9_rfno0_rf_dffl_lden.write(rf_wen.read()[9]);
  }

  void __bridge_method_regfile_10_rfno0_rf_dffl_lden() {
    __bridge_regfile_10_rfno0_rf_dffl_lden.write(rf_wen.read()[10]);
  }

  void __bridge_method_regfile_11_rfno0_rf_dffl_lden() {
    __bridge_regfile_11_rfno0_rf_dffl_lden.write(rf_wen.read()[11]);
  }

  void __bridge_method_regfile_12_rfno0_rf_dffl_lden() {
    __bridge_regfile_12_rfno0_rf_dffl_lden.write(rf_wen.read()[12]);
  }

  void __bridge_method_regfile_13_rfno0_rf_dffl_lden() {
    __bridge_regfile_13_rfno0_rf_dffl_lden.write(rf_wen.read()[13]);
  }

  void __bridge_method_regfile_14_rfno0_rf_dffl_lden() {
    __bridge_regfile_14_rfno0_rf_dffl_lden.write(rf_wen.read()[14]);
  }

  void __bridge_method_regfile_15_rfno0_rf_dffl_lden() {
    __bridge_regfile_15_rfno0_rf_dffl_lden.write(rf_wen.read()[15]);
  }

  void __bridge_method_regfile_16_rfno0_rf_dffl_lden() {
    __bridge_regfile_16_rfno0_rf_dffl_lden.write(rf_wen.read()[16]);
  }

  void __bridge_method_regfile_17_rfno0_rf_dffl_lden() {
    __bridge_regfile_17_rfno0_rf_dffl_lden.write(rf_wen.read()[17]);
  }

  void __bridge_method_regfile_18_rfno0_rf_dffl_lden() {
    __bridge_regfile_18_rfno0_rf_dffl_lden.write(rf_wen.read()[18]);
  }

  void __bridge_method_regfile_19_rfno0_rf_dffl_lden() {
    __bridge_regfile_19_rfno0_rf_dffl_lden.write(rf_wen.read()[19]);
  }

  void __bridge_method_regfile_20_rfno0_rf_dffl_lden() {
    __bridge_regfile_20_rfno0_rf_dffl_lden.write(rf_wen.read()[20]);
  }

  void __bridge_method_regfile_21_rfno0_rf_dffl_lden() {
    __bridge_regfile_21_rfno0_rf_dffl_lden.write(rf_wen.read()[21]);
  }

  void __bridge_method_regfile_22_rfno0_rf_dffl_lden() {
    __bridge_regfile_22_rfno0_rf_dffl_lden.write(rf_wen.read()[22]);
  }

  void __bridge_method_regfile_23_rfno0_rf_dffl_lden() {
    __bridge_regfile_23_rfno0_rf_dffl_lden.write(rf_wen.read()[23]);
  }

  void __bridge_method_regfile_24_rfno0_rf_dffl_lden() {
    __bridge_regfile_24_rfno0_rf_dffl_lden.write(rf_wen.read()[24]);
  }

  void __bridge_method_regfile_25_rfno0_rf_dffl_lden() {
    __bridge_regfile_25_rfno0_rf_dffl_lden.write(rf_wen.read()[25]);
  }

  void __bridge_method_regfile_26_rfno0_rf_dffl_lden() {
    __bridge_regfile_26_rfno0_rf_dffl_lden.write(rf_wen.read()[26]);
  }

  void __bridge_method_regfile_27_rfno0_rf_dffl_lden() {
    __bridge_regfile_27_rfno0_rf_dffl_lden.write(rf_wen.read()[27]);
  }

  void __bridge_method_regfile_28_rfno0_rf_dffl_lden() {
    __bridge_regfile_28_rfno0_rf_dffl_lden.write(rf_wen.read()[28]);
  }

  void __bridge_method_regfile_29_rfno0_rf_dffl_lden() {
    __bridge_regfile_29_rfno0_rf_dffl_lden.write(rf_wen.read()[29]);
  }

  void __bridge_method_regfile_30_rfno0_rf_dffl_lden() {
    __bridge_regfile_30_rfno0_rf_dffl_lden.write(rf_wen.read()[30]);
  }

  void __bridge_method_regfile_31_rfno0_rf_dffl_lden() {
    __bridge_regfile_31_rfno0_rf_dffl_lden.write(rf_wen.read()[31]);
  }

  void __bridge_method_regfile_1_rfno0_rf_dffl_qout() {
    rf_r[1].write(sc_uint<32>(__bridge_regfile_1_rfno0_rf_dffl_qout.read()));
  }

  void __bridge_method_regfile_2_rfno0_rf_dffl_qout() {
    rf_r[2].write(sc_uint<32>(__bridge_regfile_2_rfno0_rf_dffl_qout.read()));
  }

  void __bridge_method_regfile_3_rfno0_rf_dffl_qout() {
    rf_r[3].write(sc_uint<32>(__bridge_regfile_3_rfno0_rf_dffl_qout.read()));
  }

  void __bridge_method_regfile_4_rfno0_rf_dffl_qout() {
    rf_r[4].write(sc_uint<32>(__bridge_regfile_4_rfno0_rf_dffl_qout.read()));
  }

  void __bridge_method_regfile_5_rfno0_rf_dffl_qout() {
    rf_r[5].write(sc_uint<32>(__bridge_regfile_5_rfno0_rf_dffl_qout.read()));
  }

  void __bridge_method_regfile_6_rfno0_rf_dffl_qout() {
    rf_r[6].write(sc_uint<32>(__bridge_regfile_6_rfno0_rf_dffl_qout.read()));
  }

  void __bridge_method_regfile_7_rfno0_rf_dffl_qout() {
    rf_r[7].write(sc_uint<32>(__bridge_regfile_7_rfno0_rf_dffl_qout.read()));
  }

  void __bridge_method_regfile_8_rfno0_rf_dffl_qout() {
    rf_r[8].write(sc_uint<32>(__bridge_regfile_8_rfno0_rf_dffl_qout.read()));
  }

  void __bridge_method_regfile_9_rfno0_rf_dffl_qout() {
    rf_r[9].write(sc_uint<32>(__bridge_regfile_9_rfno0_rf_dffl_qout.read()));
  }

  void __bridge_method_regfile_10_rfno0_rf_dffl_qout() {
    rf_r[10].write(sc_uint<32>(__bridge_regfile_10_rfno0_rf_dffl_qout.read()));
  }

  void __bridge_method_regfile_11_rfno0_rf_dffl_qout() {
    rf_r[11].write(sc_uint<32>(__bridge_regfile_11_rfno0_rf_dffl_qout.read()));
  }

  void __bridge_method_regfile_12_rfno0_rf_dffl_qout() {
    rf_r[12].write(sc_uint<32>(__bridge_regfile_12_rfno0_rf_dffl_qout.read()));
  }

  void __bridge_method_regfile_13_rfno0_rf_dffl_qout() {
    rf_r[13].write(sc_uint<32>(__bridge_regfile_13_rfno0_rf_dffl_qout.read()));
  }

  void __bridge_method_regfile_14_rfno0_rf_dffl_qout() {
    rf_r[14].write(sc_uint<32>(__bridge_regfile_14_rfno0_rf_dffl_qout.read()));
  }

  void __bridge_method_regfile_15_rfno0_rf_dffl_qout() {
    rf_r[15].write(sc_uint<32>(__bridge_regfile_15_rfno0_rf_dffl_qout.read()));
  }

  void __bridge_method_regfile_16_rfno0_rf_dffl_qout() {
    rf_r[16].write(sc_uint<32>(__bridge_regfile_16_rfno0_rf_dffl_qout.read()));
  }

  void __bridge_method_regfile_17_rfno0_rf_dffl_qout() {
    rf_r[17].write(sc_uint<32>(__bridge_regfile_17_rfno0_rf_dffl_qout.read()));
  }

  void __bridge_method_regfile_18_rfno0_rf_dffl_qout() {
    rf_r[18].write(sc_uint<32>(__bridge_regfile_18_rfno0_rf_dffl_qout.read()));
  }

  void __bridge_method_regfile_19_rfno0_rf_dffl_qout() {
    rf_r[19].write(sc_uint<32>(__bridge_regfile_19_rfno0_rf_dffl_qout.read()));
  }

  void __bridge_method_regfile_20_rfno0_rf_dffl_qout() {
    rf_r[20].write(sc_uint<32>(__bridge_regfile_20_rfno0_rf_dffl_qout.read()));
  }

  void __bridge_method_regfile_21_rfno0_rf_dffl_qout() {
    rf_r[21].write(sc_uint<32>(__bridge_regfile_21_rfno0_rf_dffl_qout.read()));
  }

  void __bridge_method_regfile_22_rfno0_rf_dffl_qout() {
    rf_r[22].write(sc_uint<32>(__bridge_regfile_22_rfno0_rf_dffl_qout.read()));
  }

  void __bridge_method_regfile_23_rfno0_rf_dffl_qout() {
    rf_r[23].write(sc_uint<32>(__bridge_regfile_23_rfno0_rf_dffl_qout.read()));
  }

  void __bridge_method_regfile_24_rfno0_rf_dffl_qout() {
    rf_r[24].write(sc_uint<32>(__bridge_regfile_24_rfno0_rf_dffl_qout.read()));
  }

  void __bridge_method_regfile_25_rfno0_rf_dffl_qout() {
    rf_r[25].write(sc_uint<32>(__bridge_regfile_25_rfno0_rf_dffl_qout.read()));
  }

  void __bridge_method_regfile_26_rfno0_rf_dffl_qout() {
    rf_r[26].write(sc_uint<32>(__bridge_regfile_26_rfno0_rf_dffl_qout.read()));
  }

  void __bridge_method_regfile_27_rfno0_rf_dffl_qout() {
    rf_r[27].write(sc_uint<32>(__bridge_regfile_27_rfno0_rf_dffl_qout.read()));
  }

  void __bridge_method_regfile_28_rfno0_rf_dffl_qout() {
    rf_r[28].write(sc_uint<32>(__bridge_regfile_28_rfno0_rf_dffl_qout.read()));
  }

  void __bridge_method_regfile_29_rfno0_rf_dffl_qout() {
    rf_r[29].write(sc_uint<32>(__bridge_regfile_29_rfno0_rf_dffl_qout.read()));
  }

  void __bridge_method_regfile_30_rfno0_rf_dffl_qout() {
    rf_r[30].write(sc_uint<32>(__bridge_regfile_30_rfno0_rf_dffl_qout.read()));
  }

  void __bridge_method_regfile_31_rfno0_rf_dffl_qout() {
    rf_r[31].write(sc_uint<32>(__bridge_regfile_31_rfno0_rf_dffl_qout.read()));
  }

  void __assemble_rf_wen() {
    auto __tmp = rf_wen.read();
    __tmp[0] = __shadow_rf_wen_0.read();
    __tmp[1] = __shadow_rf_wen_1.read();
    __tmp[2] = __shadow_rf_wen_2.read();
    __tmp[3] = __shadow_rf_wen_3.read();
    __tmp[4] = __shadow_rf_wen_4.read();
    __tmp[5] = __shadow_rf_wen_5.read();
    __tmp[6] = __shadow_rf_wen_6.read();
    __tmp[7] = __shadow_rf_wen_7.read();
    __tmp[8] = __shadow_rf_wen_8.read();
    __tmp[9] = __shadow_rf_wen_9.read();
    __tmp[10] = __shadow_rf_wen_10.read();
    __tmp[11] = __shadow_rf_wen_11.read();
    __tmp[12] = __shadow_rf_wen_12.read();
    __tmp[13] = __shadow_rf_wen_13.read();
    __tmp[14] = __shadow_rf_wen_14.read();
    __tmp[15] = __shadow_rf_wen_15.read();
    __tmp[16] = __shadow_rf_wen_16.read();
    __tmp[17] = __shadow_rf_wen_17.read();
    __tmp[18] = __shadow_rf_wen_18.read();
    __tmp[19] = __shadow_rf_wen_19.read();
    __tmp[20] = __shadow_rf_wen_20.read();
    __tmp[21] = __shadow_rf_wen_21.read();
    __tmp[22] = __shadow_rf_wen_22.read();
    __tmp[23] = __shadow_rf_wen_23.read();
    __tmp[24] = __shadow_rf_wen_24.read();
    __tmp[25] = __shadow_rf_wen_25.read();
    __tmp[26] = __shadow_rf_wen_26.read();
    __tmp[27] = __shadow_rf_wen_27.read();
    __tmp[28] = __shadow_rf_wen_28.read();
    __tmp[29] = __shadow_rf_wen_29.read();
    __tmp[30] = __shadow_rf_wen_30.read();
    __tmp[31] = __shadow_rf_wen_31.read();
    rf_wen.write(__tmp);
  }

  SC_CTOR(e203_exu_regfile)
    : regfile_1_rfno0_rf_dffl("regfile_1_rfno0_rf_dffl"), regfile_2_rfno0_rf_dffl("regfile_2_rfno0_rf_dffl"), regfile_3_rfno0_rf_dffl("regfile_3_rfno0_rf_dffl"), regfile_4_rfno0_rf_dffl("regfile_4_rfno0_rf_dffl"), regfile_5_rfno0_rf_dffl("regfile_5_rfno0_rf_dffl"), regfile_6_rfno0_rf_dffl("regfile_6_rfno0_rf_dffl"), regfile_7_rfno0_rf_dffl("regfile_7_rfno0_rf_dffl"), regfile_8_rfno0_rf_dffl("regfile_8_rfno0_rf_dffl"), regfile_9_rfno0_rf_dffl("regfile_9_rfno0_rf_dffl"), regfile_10_rfno0_rf_dffl("regfile_10_rfno0_rf_dffl"), regfile_11_rfno0_rf_dffl("regfile_11_rfno0_rf_dffl"), regfile_12_rfno0_rf_dffl("regfile_12_rfno0_rf_dffl"), regfile_13_rfno0_rf_dffl("regfile_13_rfno0_rf_dffl"), regfile_14_rfno0_rf_dffl("regfile_14_rfno0_rf_dffl"), regfile_15_rfno0_rf_dffl("regfile_15_rfno0_rf_dffl"), regfile_16_rfno0_rf_dffl("regfile_16_rfno0_rf_dffl"), regfile_17_rfno0_rf_dffl("regfile_17_rfno0_rf_dffl"), regfile_18_rfno0_rf_dffl("regfile_18_rfno0_rf_dffl"), regfile_19_rfno0_rf_dffl("regfile_19_rfno0_rf_dffl"), regfile_20_rfno0_rf_dffl("regfile_20_rfno0_rf_dffl"), regfile_21_rfno0_rf_dffl("regfile_21_rfno0_rf_dffl"), regfile_22_rfno0_rf_dffl("regfile_22_rfno0_rf_dffl"), regfile_23_rfno0_rf_dffl("regfile_23_rfno0_rf_dffl"), regfile_24_rfno0_rf_dffl("regfile_24_rfno0_rf_dffl"), regfile_25_rfno0_rf_dffl("regfile_25_rfno0_rf_dffl"), regfile_26_rfno0_rf_dffl("regfile_26_rfno0_rf_dffl"), regfile_27_rfno0_rf_dffl("regfile_27_rfno0_rf_dffl"), regfile_28_rfno0_rf_dffl("regfile_28_rfno0_rf_dffl"), regfile_29_rfno0_rf_dffl("regfile_29_rfno0_rf_dffl"), regfile_30_rfno0_rf_dffl("regfile_30_rfno0_rf_dffl"), regfile_31_rfno0_rf_dffl("regfile_31_rfno0_rf_dffl")
  {
    SC_METHOD(assign_0);
    // No inferred sensitivity; method will need manual review.

    SC_METHOD(assign_1);
    // No inferred sensitivity; method will need manual review.

    SC_METHOD(assign_2);
    sensitive << wbck_dest_wen << wbck_dest_idx;

    SC_METHOD(assign_3);
    sensitive << wbck_dest_wen << wbck_dest_idx;

    SC_METHOD(assign_4);
    sensitive << wbck_dest_wen << wbck_dest_idx;

    SC_METHOD(assign_5);
    sensitive << wbck_dest_wen << wbck_dest_idx;

    SC_METHOD(assign_6);
    sensitive << wbck_dest_wen << wbck_dest_idx;

    SC_METHOD(assign_7);
    sensitive << wbck_dest_wen << wbck_dest_idx;

    SC_METHOD(assign_8);
    sensitive << wbck_dest_wen << wbck_dest_idx;

    SC_METHOD(assign_9);
    sensitive << wbck_dest_wen << wbck_dest_idx;

    SC_METHOD(assign_10);
    sensitive << wbck_dest_wen << wbck_dest_idx;

    SC_METHOD(assign_11);
    sensitive << wbck_dest_wen << wbck_dest_idx;

    SC_METHOD(assign_12);
    sensitive << wbck_dest_wen << wbck_dest_idx;

    SC_METHOD(assign_13);
    sensitive << wbck_dest_wen << wbck_dest_idx;

    SC_METHOD(assign_14);
    sensitive << wbck_dest_wen << wbck_dest_idx;

    SC_METHOD(assign_15);
    sensitive << wbck_dest_wen << wbck_dest_idx;

    SC_METHOD(assign_16);
    sensitive << wbck_dest_wen << wbck_dest_idx;

    SC_METHOD(assign_17);
    sensitive << wbck_dest_wen << wbck_dest_idx;

    SC_METHOD(assign_18);
    sensitive << wbck_dest_wen << wbck_dest_idx;

    SC_METHOD(assign_19);
    sensitive << wbck_dest_wen << wbck_dest_idx;

    SC_METHOD(assign_20);
    sensitive << wbck_dest_wen << wbck_dest_idx;

    SC_METHOD(assign_21);
    sensitive << wbck_dest_wen << wbck_dest_idx;

    SC_METHOD(assign_22);
    sensitive << wbck_dest_wen << wbck_dest_idx;

    SC_METHOD(assign_23);
    sensitive << wbck_dest_wen << wbck_dest_idx;

    SC_METHOD(assign_24);
    sensitive << wbck_dest_wen << wbck_dest_idx;

    SC_METHOD(assign_25);
    sensitive << wbck_dest_wen << wbck_dest_idx;

    SC_METHOD(assign_26);
    sensitive << wbck_dest_wen << wbck_dest_idx;

    SC_METHOD(assign_27);
    sensitive << wbck_dest_wen << wbck_dest_idx;

    SC_METHOD(assign_28);
    sensitive << wbck_dest_wen << wbck_dest_idx;

    SC_METHOD(assign_29);
    sensitive << wbck_dest_wen << wbck_dest_idx;

    SC_METHOD(assign_30);
    sensitive << wbck_dest_wen << wbck_dest_idx;

    SC_METHOD(assign_31);
    sensitive << wbck_dest_wen << wbck_dest_idx;

    SC_METHOD(assign_32);
    sensitive << wbck_dest_wen << wbck_dest_idx;

    SC_METHOD(assign_33);
    sensitive << rf_r[0] << rf_r[1] << rf_r[2] << rf_r[3] << rf_r[4] << rf_r[5] << rf_r[6] << rf_r[7] << rf_r[8] << rf_r[9] << rf_r[10] << rf_r[11] << rf_r[12] << rf_r[13] << rf_r[14] << rf_r[15] << rf_r[16] << rf_r[17] << rf_r[18] << rf_r[19] << rf_r[20] << rf_r[21] << rf_r[22] << rf_r[23] << rf_r[24] << rf_r[25] << rf_r[26] << rf_r[27] << rf_r[28] << rf_r[29] << rf_r[30] << rf_r[31] << read_src1_idx;

    SC_METHOD(assign_34);
    sensitive << rf_r[0] << rf_r[1] << rf_r[2] << rf_r[3] << rf_r[4] << rf_r[5] << rf_r[6] << rf_r[7] << rf_r[8] << rf_r[9] << rf_r[10] << rf_r[11] << rf_r[12] << rf_r[13] << rf_r[14] << rf_r[15] << rf_r[16] << rf_r[17] << rf_r[18] << rf_r[19] << rf_r[20] << rf_r[21] << rf_r[22] << rf_r[23] << rf_r[24] << rf_r[25] << rf_r[26] << rf_r[27] << rf_r[28] << rf_r[29] << rf_r[30] << rf_r[31] << read_src2_idx;

    SC_METHOD(assign_35);
    sensitive << rf_r[0] << rf_r[1] << rf_r[2] << rf_r[3] << rf_r[4] << rf_r[5] << rf_r[6] << rf_r[7] << rf_r[8] << rf_r[9] << rf_r[10] << rf_r[11] << rf_r[12] << rf_r[13] << rf_r[14] << rf_r[15] << rf_r[16] << rf_r[17] << rf_r[18] << rf_r[19] << rf_r[20] << rf_r[21] << rf_r[22] << rf_r[23] << rf_r[24] << rf_r[25] << rf_r[26] << rf_r[27] << rf_r[28] << rf_r[29] << rf_r[30] << rf_r[31];

    regfile_1_rfno0_rf_dffl.lden(__bridge_regfile_1_rfno0_rf_dffl_lden);
    regfile_1_rfno0_rf_dffl.dnxt(wbck_dest_dat);
    regfile_1_rfno0_rf_dffl.qout(__bridge_regfile_1_rfno0_rf_dffl_qout);
    regfile_1_rfno0_rf_dffl.clk(clk);
    regfile_2_rfno0_rf_dffl.lden(__bridge_regfile_2_rfno0_rf_dffl_lden);
    regfile_2_rfno0_rf_dffl.dnxt(wbck_dest_dat);
    regfile_2_rfno0_rf_dffl.qout(__bridge_regfile_2_rfno0_rf_dffl_qout);
    regfile_2_rfno0_rf_dffl.clk(clk);
    regfile_3_rfno0_rf_dffl.lden(__bridge_regfile_3_rfno0_rf_dffl_lden);
    regfile_3_rfno0_rf_dffl.dnxt(wbck_dest_dat);
    regfile_3_rfno0_rf_dffl.qout(__bridge_regfile_3_rfno0_rf_dffl_qout);
    regfile_3_rfno0_rf_dffl.clk(clk);
    regfile_4_rfno0_rf_dffl.lden(__bridge_regfile_4_rfno0_rf_dffl_lden);
    regfile_4_rfno0_rf_dffl.dnxt(wbck_dest_dat);
    regfile_4_rfno0_rf_dffl.qout(__bridge_regfile_4_rfno0_rf_dffl_qout);
    regfile_4_rfno0_rf_dffl.clk(clk);
    regfile_5_rfno0_rf_dffl.lden(__bridge_regfile_5_rfno0_rf_dffl_lden);
    regfile_5_rfno0_rf_dffl.dnxt(wbck_dest_dat);
    regfile_5_rfno0_rf_dffl.qout(__bridge_regfile_5_rfno0_rf_dffl_qout);
    regfile_5_rfno0_rf_dffl.clk(clk);
    regfile_6_rfno0_rf_dffl.lden(__bridge_regfile_6_rfno0_rf_dffl_lden);
    regfile_6_rfno0_rf_dffl.dnxt(wbck_dest_dat);
    regfile_6_rfno0_rf_dffl.qout(__bridge_regfile_6_rfno0_rf_dffl_qout);
    regfile_6_rfno0_rf_dffl.clk(clk);
    regfile_7_rfno0_rf_dffl.lden(__bridge_regfile_7_rfno0_rf_dffl_lden);
    regfile_7_rfno0_rf_dffl.dnxt(wbck_dest_dat);
    regfile_7_rfno0_rf_dffl.qout(__bridge_regfile_7_rfno0_rf_dffl_qout);
    regfile_7_rfno0_rf_dffl.clk(clk);
    regfile_8_rfno0_rf_dffl.lden(__bridge_regfile_8_rfno0_rf_dffl_lden);
    regfile_8_rfno0_rf_dffl.dnxt(wbck_dest_dat);
    regfile_8_rfno0_rf_dffl.qout(__bridge_regfile_8_rfno0_rf_dffl_qout);
    regfile_8_rfno0_rf_dffl.clk(clk);
    regfile_9_rfno0_rf_dffl.lden(__bridge_regfile_9_rfno0_rf_dffl_lden);
    regfile_9_rfno0_rf_dffl.dnxt(wbck_dest_dat);
    regfile_9_rfno0_rf_dffl.qout(__bridge_regfile_9_rfno0_rf_dffl_qout);
    regfile_9_rfno0_rf_dffl.clk(clk);
    regfile_10_rfno0_rf_dffl.lden(__bridge_regfile_10_rfno0_rf_dffl_lden);
    regfile_10_rfno0_rf_dffl.dnxt(wbck_dest_dat);
    regfile_10_rfno0_rf_dffl.qout(__bridge_regfile_10_rfno0_rf_dffl_qout);
    regfile_10_rfno0_rf_dffl.clk(clk);
    regfile_11_rfno0_rf_dffl.lden(__bridge_regfile_11_rfno0_rf_dffl_lden);
    regfile_11_rfno0_rf_dffl.dnxt(wbck_dest_dat);
    regfile_11_rfno0_rf_dffl.qout(__bridge_regfile_11_rfno0_rf_dffl_qout);
    regfile_11_rfno0_rf_dffl.clk(clk);
    regfile_12_rfno0_rf_dffl.lden(__bridge_regfile_12_rfno0_rf_dffl_lden);
    regfile_12_rfno0_rf_dffl.dnxt(wbck_dest_dat);
    regfile_12_rfno0_rf_dffl.qout(__bridge_regfile_12_rfno0_rf_dffl_qout);
    regfile_12_rfno0_rf_dffl.clk(clk);
    regfile_13_rfno0_rf_dffl.lden(__bridge_regfile_13_rfno0_rf_dffl_lden);
    regfile_13_rfno0_rf_dffl.dnxt(wbck_dest_dat);
    regfile_13_rfno0_rf_dffl.qout(__bridge_regfile_13_rfno0_rf_dffl_qout);
    regfile_13_rfno0_rf_dffl.clk(clk);
    regfile_14_rfno0_rf_dffl.lden(__bridge_regfile_14_rfno0_rf_dffl_lden);
    regfile_14_rfno0_rf_dffl.dnxt(wbck_dest_dat);
    regfile_14_rfno0_rf_dffl.qout(__bridge_regfile_14_rfno0_rf_dffl_qout);
    regfile_14_rfno0_rf_dffl.clk(clk);
    regfile_15_rfno0_rf_dffl.lden(__bridge_regfile_15_rfno0_rf_dffl_lden);
    regfile_15_rfno0_rf_dffl.dnxt(wbck_dest_dat);
    regfile_15_rfno0_rf_dffl.qout(__bridge_regfile_15_rfno0_rf_dffl_qout);
    regfile_15_rfno0_rf_dffl.clk(clk);
    regfile_16_rfno0_rf_dffl.lden(__bridge_regfile_16_rfno0_rf_dffl_lden);
    regfile_16_rfno0_rf_dffl.dnxt(wbck_dest_dat);
    regfile_16_rfno0_rf_dffl.qout(__bridge_regfile_16_rfno0_rf_dffl_qout);
    regfile_16_rfno0_rf_dffl.clk(clk);
    regfile_17_rfno0_rf_dffl.lden(__bridge_regfile_17_rfno0_rf_dffl_lden);
    regfile_17_rfno0_rf_dffl.dnxt(wbck_dest_dat);
    regfile_17_rfno0_rf_dffl.qout(__bridge_regfile_17_rfno0_rf_dffl_qout);
    regfile_17_rfno0_rf_dffl.clk(clk);
    regfile_18_rfno0_rf_dffl.lden(__bridge_regfile_18_rfno0_rf_dffl_lden);
    regfile_18_rfno0_rf_dffl.dnxt(wbck_dest_dat);
    regfile_18_rfno0_rf_dffl.qout(__bridge_regfile_18_rfno0_rf_dffl_qout);
    regfile_18_rfno0_rf_dffl.clk(clk);
    regfile_19_rfno0_rf_dffl.lden(__bridge_regfile_19_rfno0_rf_dffl_lden);
    regfile_19_rfno0_rf_dffl.dnxt(wbck_dest_dat);
    regfile_19_rfno0_rf_dffl.qout(__bridge_regfile_19_rfno0_rf_dffl_qout);
    regfile_19_rfno0_rf_dffl.clk(clk);
    regfile_20_rfno0_rf_dffl.lden(__bridge_regfile_20_rfno0_rf_dffl_lden);
    regfile_20_rfno0_rf_dffl.dnxt(wbck_dest_dat);
    regfile_20_rfno0_rf_dffl.qout(__bridge_regfile_20_rfno0_rf_dffl_qout);
    regfile_20_rfno0_rf_dffl.clk(clk);
    regfile_21_rfno0_rf_dffl.lden(__bridge_regfile_21_rfno0_rf_dffl_lden);
    regfile_21_rfno0_rf_dffl.dnxt(wbck_dest_dat);
    regfile_21_rfno0_rf_dffl.qout(__bridge_regfile_21_rfno0_rf_dffl_qout);
    regfile_21_rfno0_rf_dffl.clk(clk);
    regfile_22_rfno0_rf_dffl.lden(__bridge_regfile_22_rfno0_rf_dffl_lden);
    regfile_22_rfno0_rf_dffl.dnxt(wbck_dest_dat);
    regfile_22_rfno0_rf_dffl.qout(__bridge_regfile_22_rfno0_rf_dffl_qout);
    regfile_22_rfno0_rf_dffl.clk(clk);
    regfile_23_rfno0_rf_dffl.lden(__bridge_regfile_23_rfno0_rf_dffl_lden);
    regfile_23_rfno0_rf_dffl.dnxt(wbck_dest_dat);
    regfile_23_rfno0_rf_dffl.qout(__bridge_regfile_23_rfno0_rf_dffl_qout);
    regfile_23_rfno0_rf_dffl.clk(clk);
    regfile_24_rfno0_rf_dffl.lden(__bridge_regfile_24_rfno0_rf_dffl_lden);
    regfile_24_rfno0_rf_dffl.dnxt(wbck_dest_dat);
    regfile_24_rfno0_rf_dffl.qout(__bridge_regfile_24_rfno0_rf_dffl_qout);
    regfile_24_rfno0_rf_dffl.clk(clk);
    regfile_25_rfno0_rf_dffl.lden(__bridge_regfile_25_rfno0_rf_dffl_lden);
    regfile_25_rfno0_rf_dffl.dnxt(wbck_dest_dat);
    regfile_25_rfno0_rf_dffl.qout(__bridge_regfile_25_rfno0_rf_dffl_qout);
    regfile_25_rfno0_rf_dffl.clk(clk);
    regfile_26_rfno0_rf_dffl.lden(__bridge_regfile_26_rfno0_rf_dffl_lden);
    regfile_26_rfno0_rf_dffl.dnxt(wbck_dest_dat);
    regfile_26_rfno0_rf_dffl.qout(__bridge_regfile_26_rfno0_rf_dffl_qout);
    regfile_26_rfno0_rf_dffl.clk(clk);
    regfile_27_rfno0_rf_dffl.lden(__bridge_regfile_27_rfno0_rf_dffl_lden);
    regfile_27_rfno0_rf_dffl.dnxt(wbck_dest_dat);
    regfile_27_rfno0_rf_dffl.qout(__bridge_regfile_27_rfno0_rf_dffl_qout);
    regfile_27_rfno0_rf_dffl.clk(clk);
    regfile_28_rfno0_rf_dffl.lden(__bridge_regfile_28_rfno0_rf_dffl_lden);
    regfile_28_rfno0_rf_dffl.dnxt(wbck_dest_dat);
    regfile_28_rfno0_rf_dffl.qout(__bridge_regfile_28_rfno0_rf_dffl_qout);
    regfile_28_rfno0_rf_dffl.clk(clk);
    regfile_29_rfno0_rf_dffl.lden(__bridge_regfile_29_rfno0_rf_dffl_lden);
    regfile_29_rfno0_rf_dffl.dnxt(wbck_dest_dat);
    regfile_29_rfno0_rf_dffl.qout(__bridge_regfile_29_rfno0_rf_dffl_qout);
    regfile_29_rfno0_rf_dffl.clk(clk);
    regfile_30_rfno0_rf_dffl.lden(__bridge_regfile_30_rfno0_rf_dffl_lden);
    regfile_30_rfno0_rf_dffl.dnxt(wbck_dest_dat);
    regfile_30_rfno0_rf_dffl.qout(__bridge_regfile_30_rfno0_rf_dffl_qout);
    regfile_30_rfno0_rf_dffl.clk(clk);
    regfile_31_rfno0_rf_dffl.lden(__bridge_regfile_31_rfno0_rf_dffl_lden);
    regfile_31_rfno0_rf_dffl.dnxt(wbck_dest_dat);
    regfile_31_rfno0_rf_dffl.qout(__bridge_regfile_31_rfno0_rf_dffl_qout);
    regfile_31_rfno0_rf_dffl.clk(clk);
    SC_METHOD(__bridge_method_regfile_1_rfno0_rf_dffl_lden);
    sensitive << rf_wen;

    SC_METHOD(__bridge_method_regfile_2_rfno0_rf_dffl_lden);
    sensitive << rf_wen;

    SC_METHOD(__bridge_method_regfile_3_rfno0_rf_dffl_lden);
    sensitive << rf_wen;

    SC_METHOD(__bridge_method_regfile_4_rfno0_rf_dffl_lden);
    sensitive << rf_wen;

    SC_METHOD(__bridge_method_regfile_5_rfno0_rf_dffl_lden);
    sensitive << rf_wen;

    SC_METHOD(__bridge_method_regfile_6_rfno0_rf_dffl_lden);
    sensitive << rf_wen;

    SC_METHOD(__bridge_method_regfile_7_rfno0_rf_dffl_lden);
    sensitive << rf_wen;

    SC_METHOD(__bridge_method_regfile_8_rfno0_rf_dffl_lden);
    sensitive << rf_wen;

    SC_METHOD(__bridge_method_regfile_9_rfno0_rf_dffl_lden);
    sensitive << rf_wen;

    SC_METHOD(__bridge_method_regfile_10_rfno0_rf_dffl_lden);
    sensitive << rf_wen;

    SC_METHOD(__bridge_method_regfile_11_rfno0_rf_dffl_lden);
    sensitive << rf_wen;

    SC_METHOD(__bridge_method_regfile_12_rfno0_rf_dffl_lden);
    sensitive << rf_wen;

    SC_METHOD(__bridge_method_regfile_13_rfno0_rf_dffl_lden);
    sensitive << rf_wen;

    SC_METHOD(__bridge_method_regfile_14_rfno0_rf_dffl_lden);
    sensitive << rf_wen;

    SC_METHOD(__bridge_method_regfile_15_rfno0_rf_dffl_lden);
    sensitive << rf_wen;

    SC_METHOD(__bridge_method_regfile_16_rfno0_rf_dffl_lden);
    sensitive << rf_wen;

    SC_METHOD(__bridge_method_regfile_17_rfno0_rf_dffl_lden);
    sensitive << rf_wen;

    SC_METHOD(__bridge_method_regfile_18_rfno0_rf_dffl_lden);
    sensitive << rf_wen;

    SC_METHOD(__bridge_method_regfile_19_rfno0_rf_dffl_lden);
    sensitive << rf_wen;

    SC_METHOD(__bridge_method_regfile_20_rfno0_rf_dffl_lden);
    sensitive << rf_wen;

    SC_METHOD(__bridge_method_regfile_21_rfno0_rf_dffl_lden);
    sensitive << rf_wen;

    SC_METHOD(__bridge_method_regfile_22_rfno0_rf_dffl_lden);
    sensitive << rf_wen;

    SC_METHOD(__bridge_method_regfile_23_rfno0_rf_dffl_lden);
    sensitive << rf_wen;

    SC_METHOD(__bridge_method_regfile_24_rfno0_rf_dffl_lden);
    sensitive << rf_wen;

    SC_METHOD(__bridge_method_regfile_25_rfno0_rf_dffl_lden);
    sensitive << rf_wen;

    SC_METHOD(__bridge_method_regfile_26_rfno0_rf_dffl_lden);
    sensitive << rf_wen;

    SC_METHOD(__bridge_method_regfile_27_rfno0_rf_dffl_lden);
    sensitive << rf_wen;

    SC_METHOD(__bridge_method_regfile_28_rfno0_rf_dffl_lden);
    sensitive << rf_wen;

    SC_METHOD(__bridge_method_regfile_29_rfno0_rf_dffl_lden);
    sensitive << rf_wen;

    SC_METHOD(__bridge_method_regfile_30_rfno0_rf_dffl_lden);
    sensitive << rf_wen;

    SC_METHOD(__bridge_method_regfile_31_rfno0_rf_dffl_lden);
    sensitive << rf_wen;

    SC_METHOD(__bridge_method_regfile_1_rfno0_rf_dffl_qout);
    sensitive << __bridge_regfile_1_rfno0_rf_dffl_qout;

    SC_METHOD(__bridge_method_regfile_2_rfno0_rf_dffl_qout);
    sensitive << __bridge_regfile_2_rfno0_rf_dffl_qout;

    SC_METHOD(__bridge_method_regfile_3_rfno0_rf_dffl_qout);
    sensitive << __bridge_regfile_3_rfno0_rf_dffl_qout;

    SC_METHOD(__bridge_method_regfile_4_rfno0_rf_dffl_qout);
    sensitive << __bridge_regfile_4_rfno0_rf_dffl_qout;

    SC_METHOD(__bridge_method_regfile_5_rfno0_rf_dffl_qout);
    sensitive << __bridge_regfile_5_rfno0_rf_dffl_qout;

    SC_METHOD(__bridge_method_regfile_6_rfno0_rf_dffl_qout);
    sensitive << __bridge_regfile_6_rfno0_rf_dffl_qout;

    SC_METHOD(__bridge_method_regfile_7_rfno0_rf_dffl_qout);
    sensitive << __bridge_regfile_7_rfno0_rf_dffl_qout;

    SC_METHOD(__bridge_method_regfile_8_rfno0_rf_dffl_qout);
    sensitive << __bridge_regfile_8_rfno0_rf_dffl_qout;

    SC_METHOD(__bridge_method_regfile_9_rfno0_rf_dffl_qout);
    sensitive << __bridge_regfile_9_rfno0_rf_dffl_qout;

    SC_METHOD(__bridge_method_regfile_10_rfno0_rf_dffl_qout);
    sensitive << __bridge_regfile_10_rfno0_rf_dffl_qout;

    SC_METHOD(__bridge_method_regfile_11_rfno0_rf_dffl_qout);
    sensitive << __bridge_regfile_11_rfno0_rf_dffl_qout;

    SC_METHOD(__bridge_method_regfile_12_rfno0_rf_dffl_qout);
    sensitive << __bridge_regfile_12_rfno0_rf_dffl_qout;

    SC_METHOD(__bridge_method_regfile_13_rfno0_rf_dffl_qout);
    sensitive << __bridge_regfile_13_rfno0_rf_dffl_qout;

    SC_METHOD(__bridge_method_regfile_14_rfno0_rf_dffl_qout);
    sensitive << __bridge_regfile_14_rfno0_rf_dffl_qout;

    SC_METHOD(__bridge_method_regfile_15_rfno0_rf_dffl_qout);
    sensitive << __bridge_regfile_15_rfno0_rf_dffl_qout;

    SC_METHOD(__bridge_method_regfile_16_rfno0_rf_dffl_qout);
    sensitive << __bridge_regfile_16_rfno0_rf_dffl_qout;

    SC_METHOD(__bridge_method_regfile_17_rfno0_rf_dffl_qout);
    sensitive << __bridge_regfile_17_rfno0_rf_dffl_qout;

    SC_METHOD(__bridge_method_regfile_18_rfno0_rf_dffl_qout);
    sensitive << __bridge_regfile_18_rfno0_rf_dffl_qout;

    SC_METHOD(__bridge_method_regfile_19_rfno0_rf_dffl_qout);
    sensitive << __bridge_regfile_19_rfno0_rf_dffl_qout;

    SC_METHOD(__bridge_method_regfile_20_rfno0_rf_dffl_qout);
    sensitive << __bridge_regfile_20_rfno0_rf_dffl_qout;

    SC_METHOD(__bridge_method_regfile_21_rfno0_rf_dffl_qout);
    sensitive << __bridge_regfile_21_rfno0_rf_dffl_qout;

    SC_METHOD(__bridge_method_regfile_22_rfno0_rf_dffl_qout);
    sensitive << __bridge_regfile_22_rfno0_rf_dffl_qout;

    SC_METHOD(__bridge_method_regfile_23_rfno0_rf_dffl_qout);
    sensitive << __bridge_regfile_23_rfno0_rf_dffl_qout;

    SC_METHOD(__bridge_method_regfile_24_rfno0_rf_dffl_qout);
    sensitive << __bridge_regfile_24_rfno0_rf_dffl_qout;

    SC_METHOD(__bridge_method_regfile_25_rfno0_rf_dffl_qout);
    sensitive << __bridge_regfile_25_rfno0_rf_dffl_qout;

    SC_METHOD(__bridge_method_regfile_26_rfno0_rf_dffl_qout);
    sensitive << __bridge_regfile_26_rfno0_rf_dffl_qout;

    SC_METHOD(__bridge_method_regfile_27_rfno0_rf_dffl_qout);
    sensitive << __bridge_regfile_27_rfno0_rf_dffl_qout;

    SC_METHOD(__bridge_method_regfile_28_rfno0_rf_dffl_qout);
    sensitive << __bridge_regfile_28_rfno0_rf_dffl_qout;

    SC_METHOD(__bridge_method_regfile_29_rfno0_rf_dffl_qout);
    sensitive << __bridge_regfile_29_rfno0_rf_dffl_qout;

    SC_METHOD(__bridge_method_regfile_30_rfno0_rf_dffl_qout);
    sensitive << __bridge_regfile_30_rfno0_rf_dffl_qout;

    SC_METHOD(__bridge_method_regfile_31_rfno0_rf_dffl_qout);
    sensitive << __bridge_regfile_31_rfno0_rf_dffl_qout;

    SC_METHOD(__assemble_rf_wen);
    sensitive << __shadow_rf_wen_0 << __shadow_rf_wen_1 << __shadow_rf_wen_2 << __shadow_rf_wen_3 << __shadow_rf_wen_4 << __shadow_rf_wen_5 << __shadow_rf_wen_6 << __shadow_rf_wen_7 << __shadow_rf_wen_8 << __shadow_rf_wen_9 << __shadow_rf_wen_10 << __shadow_rf_wen_11 << __shadow_rf_wen_12 << __shadow_rf_wen_13 << __shadow_rf_wen_14 << __shadow_rf_wen_15 << __shadow_rf_wen_16 << __shadow_rf_wen_17 << __shadow_rf_wen_18 << __shadow_rf_wen_19 << __shadow_rf_wen_20 << __shadow_rf_wen_21 << __shadow_rf_wen_22 << __shadow_rf_wen_23 << __shadow_rf_wen_24 << __shadow_rf_wen_25 << __shadow_rf_wen_26 << __shadow_rf_wen_27 << __shadow_rf_wen_28 << __shadow_rf_wen_29 << __shadow_rf_wen_30 << __shadow_rf_wen_31;

  }
};

#endif  // PRISM_V2SC_MOD_E203_EXU_REGFILE_HPP
