// Generated by prism_v2sc
#pragma once

#include <array>
#include <systemc>
#include <string>
#include <type_traits>

#include "e203_ifu_ifetch.hpp"
#include "e203_ifu_ift2icb.hpp"

using namespace sc_core;
using namespace sc_dt;

#ifndef PRISM_V2SC_INTEGER_TYPES
#define PRISM_V2SC_INTEGER_TYPES
template <int Width> using prism_v2sc_uint_t = typename std::conditional<(Width <= 64), sc_uint<Width>, sc_biguint<Width>>::type;
template <int Width> using prism_v2sc_int_t = typename std::conditional<(Width <= 64), sc_int<Width>, sc_bigint<Width>>::type;
constexpr int prism_v2sc_clog2(int value) { int result = 0; for (int current = value - 1; current > 0; current >>= 1) ++result; return result; }
#endif

#ifndef PRISM_V2SC_MOD_E203_IFU_HPP
#define PRISM_V2SC_MOD_E203_IFU_HPP

SC_MODULE(e203_ifu) {
  sc_out<sc_uint<32>> inspect_pc;
  sc_out<bool> ifu_active;
  sc_in<bool> itcm_nohold;
  sc_in<sc_uint<32>> pc_rtvec;
  sc_in<bool> ifu2itcm_holdup;
  sc_in<sc_uint<32>> itcm_region_indic;
  sc_out<bool> ifu2itcm_icb_cmd_valid;
  sc_in<bool> ifu2itcm_icb_cmd_ready;
  sc_out<sc_uint<16>> ifu2itcm_icb_cmd_addr;
  sc_in<bool> ifu2itcm_icb_rsp_valid;
  sc_out<bool> ifu2itcm_icb_rsp_ready;
  sc_in<bool> ifu2itcm_icb_rsp_err;
  sc_in<sc_uint<64>> ifu2itcm_icb_rsp_rdata;
  sc_out<bool> ifu2biu_icb_cmd_valid;
  sc_in<bool> ifu2biu_icb_cmd_ready;
  sc_out<sc_uint<32>> ifu2biu_icb_cmd_addr;
  sc_in<bool> ifu2biu_icb_rsp_valid;
  sc_out<bool> ifu2biu_icb_rsp_ready;
  sc_in<bool> ifu2biu_icb_rsp_err;
  sc_in<sc_uint<32>> ifu2biu_icb_rsp_rdata;
  sc_out<sc_uint<32>> ifu_o_ir;
  sc_out<sc_uint<32>> ifu_o_pc;
  sc_out<bool> ifu_o_pc_vld;
  sc_out<bool> ifu_o_misalgn;
  sc_out<bool> ifu_o_buserr;
  sc_out<sc_uint<5>> ifu_o_rs1idx;
  sc_out<sc_uint<5>> ifu_o_rs2idx;
  sc_out<bool> ifu_o_prdt_taken;
  sc_out<bool> ifu_o_muldiv_b2b;
  sc_out<bool> ifu_o_valid;
  sc_in<bool> ifu_o_ready;
  sc_out<bool> pipe_flush_ack;
  sc_in<bool> pipe_flush_req;
  sc_in<sc_uint<32>> pipe_flush_add_op1;
  sc_in<sc_uint<32>> pipe_flush_add_op2;
  sc_in<sc_uint<32>> pipe_flush_pc;
  sc_in<bool> ifu_halt_req;
  sc_out<bool> ifu_halt_ack;
  sc_in<bool> oitf_empty;
  sc_in<sc_uint<32>> rf2ifu_x1;
  sc_in<sc_uint<32>> rf2ifu_rs1;
  sc_in<bool> dec2ifu_rden;
  sc_in<bool> dec2ifu_rs1en;
  sc_in<sc_uint<5>> dec2ifu_rdidx;
  sc_in<bool> dec2ifu_mulhsu;
  sc_in<bool> dec2ifu_div;
  sc_in<bool> dec2ifu_rem;
  sc_in<bool> dec2ifu_divu;
  sc_in<bool> dec2ifu_remu;
  sc_in<bool> clk;
  sc_in<bool> rst_n;

  sc_signal<bool> ifu_req_valid;
  sc_signal<bool> ifu_req_ready;
  sc_signal<sc_uint<32>> ifu_req_pc;
  sc_signal<bool> ifu_req_seq;
  sc_signal<bool> ifu_req_seq_rv32;
  sc_signal<sc_uint<32>> ifu_req_last_pc;
  sc_signal<bool> ifu_rsp_valid;
  sc_signal<bool> ifu_rsp_ready;
  sc_signal<bool> ifu_rsp_err;
  sc_signal<sc_uint<32>> ifu_rsp_instr;

  e203_ifu_ifetch u_e203_ifu_ifetch;
  e203_ifu_ift2icb<> u_e203_ifu_ift2icb;

  void assign_0() {
    ifu_active.write(0b1);
  }

  SC_CTOR(e203_ifu)
    : u_e203_ifu_ifetch("u_e203_ifu_ifetch"), u_e203_ifu_ift2icb("u_e203_ifu_ift2icb")
  {
    SC_METHOD(assign_0);
    // No inferred sensitivity; method will need manual review.

    u_e203_ifu_ifetch.inspect_pc(inspect_pc);
    u_e203_ifu_ifetch.pc_rtvec(pc_rtvec);
    u_e203_ifu_ifetch.ifu_req_valid(ifu_req_valid);
    u_e203_ifu_ifetch.ifu_req_ready(ifu_req_ready);
    u_e203_ifu_ifetch.ifu_req_pc(ifu_req_pc);
    u_e203_ifu_ifetch.ifu_req_seq(ifu_req_seq);
    u_e203_ifu_ifetch.ifu_req_seq_rv32(ifu_req_seq_rv32);
    u_e203_ifu_ifetch.ifu_req_last_pc(ifu_req_last_pc);
    u_e203_ifu_ifetch.ifu_rsp_valid(ifu_rsp_valid);
    u_e203_ifu_ifetch.ifu_rsp_ready(ifu_rsp_ready);
    u_e203_ifu_ifetch.ifu_rsp_err(ifu_rsp_err);
    u_e203_ifu_ifetch.ifu_rsp_instr(ifu_rsp_instr);
    u_e203_ifu_ifetch.ifu_o_ir(ifu_o_ir);
    u_e203_ifu_ifetch.ifu_o_pc(ifu_o_pc);
    u_e203_ifu_ifetch.ifu_o_pc_vld(ifu_o_pc_vld);
    u_e203_ifu_ifetch.ifu_o_rs1idx(ifu_o_rs1idx);
    u_e203_ifu_ifetch.ifu_o_rs2idx(ifu_o_rs2idx);
    u_e203_ifu_ifetch.ifu_o_prdt_taken(ifu_o_prdt_taken);
    u_e203_ifu_ifetch.ifu_o_misalgn(ifu_o_misalgn);
    u_e203_ifu_ifetch.ifu_o_buserr(ifu_o_buserr);
    u_e203_ifu_ifetch.ifu_o_muldiv_b2b(ifu_o_muldiv_b2b);
    u_e203_ifu_ifetch.ifu_o_valid(ifu_o_valid);
    u_e203_ifu_ifetch.ifu_o_ready(ifu_o_ready);
    u_e203_ifu_ifetch.pipe_flush_ack(pipe_flush_ack);
    u_e203_ifu_ifetch.pipe_flush_req(pipe_flush_req);
    u_e203_ifu_ifetch.pipe_flush_add_op1(pipe_flush_add_op1);
    u_e203_ifu_ifetch.pipe_flush_add_op2(pipe_flush_add_op2);
    u_e203_ifu_ifetch.pipe_flush_pc(pipe_flush_pc);
    u_e203_ifu_ifetch.ifu_halt_req(ifu_halt_req);
    u_e203_ifu_ifetch.ifu_halt_ack(ifu_halt_ack);
    u_e203_ifu_ifetch.oitf_empty(oitf_empty);
    u_e203_ifu_ifetch.rf2ifu_x1(rf2ifu_x1);
    u_e203_ifu_ifetch.rf2ifu_rs1(rf2ifu_rs1);
    u_e203_ifu_ifetch.dec2ifu_rs1en(dec2ifu_rs1en);
    u_e203_ifu_ifetch.dec2ifu_rden(dec2ifu_rden);
    u_e203_ifu_ifetch.dec2ifu_rdidx(dec2ifu_rdidx);
    u_e203_ifu_ifetch.dec2ifu_mulhsu(dec2ifu_mulhsu);
    u_e203_ifu_ifetch.dec2ifu_div(dec2ifu_div);
    u_e203_ifu_ifetch.dec2ifu_rem(dec2ifu_rem);
    u_e203_ifu_ifetch.dec2ifu_divu(dec2ifu_divu);
    u_e203_ifu_ifetch.dec2ifu_remu(dec2ifu_remu);
    u_e203_ifu_ifetch.clk(clk);
    u_e203_ifu_ifetch.rst_n(rst_n);
    u_e203_ifu_ift2icb.itcm_nohold(itcm_nohold);
    u_e203_ifu_ift2icb.ifu_req_valid(ifu_req_valid);
    u_e203_ifu_ift2icb.ifu_req_ready(ifu_req_ready);
    u_e203_ifu_ift2icb.ifu_req_pc(ifu_req_pc);
    u_e203_ifu_ift2icb.ifu_req_seq(ifu_req_seq);
    u_e203_ifu_ift2icb.ifu_req_seq_rv32(ifu_req_seq_rv32);
    u_e203_ifu_ift2icb.ifu_req_last_pc(ifu_req_last_pc);
    u_e203_ifu_ift2icb.ifu_rsp_valid(ifu_rsp_valid);
    u_e203_ifu_ift2icb.ifu_rsp_ready(ifu_rsp_ready);
    u_e203_ifu_ift2icb.ifu_rsp_err(ifu_rsp_err);
    u_e203_ifu_ift2icb.ifu_rsp_instr(ifu_rsp_instr);
    u_e203_ifu_ift2icb.itcm_region_indic(itcm_region_indic);
    u_e203_ifu_ift2icb.ifu2itcm_icb_cmd_valid(ifu2itcm_icb_cmd_valid);
    u_e203_ifu_ift2icb.ifu2itcm_icb_cmd_ready(ifu2itcm_icb_cmd_ready);
    u_e203_ifu_ift2icb.ifu2itcm_icb_cmd_addr(ifu2itcm_icb_cmd_addr);
    u_e203_ifu_ift2icb.ifu2itcm_icb_rsp_valid(ifu2itcm_icb_rsp_valid);
    u_e203_ifu_ift2icb.ifu2itcm_icb_rsp_ready(ifu2itcm_icb_rsp_ready);
    u_e203_ifu_ift2icb.ifu2itcm_icb_rsp_err(ifu2itcm_icb_rsp_err);
    u_e203_ifu_ift2icb.ifu2itcm_icb_rsp_rdata(ifu2itcm_icb_rsp_rdata);
    u_e203_ifu_ift2icb.ifu2biu_icb_cmd_valid(ifu2biu_icb_cmd_valid);
    u_e203_ifu_ift2icb.ifu2biu_icb_cmd_ready(ifu2biu_icb_cmd_ready);
    u_e203_ifu_ift2icb.ifu2biu_icb_cmd_addr(ifu2biu_icb_cmd_addr);
    u_e203_ifu_ift2icb.ifu2biu_icb_rsp_valid(ifu2biu_icb_rsp_valid);
    u_e203_ifu_ift2icb.ifu2biu_icb_rsp_ready(ifu2biu_icb_rsp_ready);
    u_e203_ifu_ift2icb.ifu2biu_icb_rsp_err(ifu2biu_icb_rsp_err);
    u_e203_ifu_ift2icb.ifu2biu_icb_rsp_rdata(ifu2biu_icb_rsp_rdata);
    u_e203_ifu_ift2icb.ifu2itcm_holdup(ifu2itcm_holdup);
    u_e203_ifu_ift2icb.clk(clk);
    u_e203_ifu_ift2icb.rst_n(rst_n);
  }
};

#endif  // PRISM_V2SC_MOD_E203_IFU_HPP
