// Generated by prism_v2sc
#pragma once

#include <systemc>
#include <string>

#include "../primitives/sub_mux.hpp"
#include "../primitives/sub_register.hpp"

using namespace sc_core;
using namespace sc_dt;

#ifndef PRISM_V2SC_MOD_TOP_DATAPATH_HPP
#define PRISM_V2SC_MOD_TOP_DATAPATH_HPP

SC_MODULE(top_datapath) {
  sc_in<bool> clk;
  sc_in<bool> rst_n;
  sc_in<bool> en;
  sc_in<bool> sel;
  sc_in<sc_uint<(((8 - 1)) - (0) + 1)>> a;
  sc_in<sc_uint<(((8 - 1)) - (0) + 1)>> b;
  sc_out<sc_uint<(((8 - 1)) - (0) + 1)>> y;

  sc_signal<sc_uint<(((8 - 1)) - (0) + 1)>> mux_out;

  sub_mux u_mux;
  sub_register u_reg;

  SC_CTOR(top_datapath)
    : u_mux("u_mux"), u_reg("u_reg")
  {
    u_mux.sel(sel);
    u_mux.a(a);
    u_mux.b(b);
    u_mux.y(mux_out);
    u_reg.clk(clk);
    u_reg.rst_n(rst_n);
    u_reg.en(en);
    u_reg.data_in(mux_out);
    u_reg.data_out(y);
  }
};

#endif  // PRISM_V2SC_MOD_TOP_DATAPATH_HPP
