// Generated by prism_v2sc
#pragma once

#include <array>
#include <systemc>
#include <string>
#include <type_traits>

#include "../soc/e603_sim_ram__prism_p_b4c5e9da54.hpp"

using namespace sc_core;
using namespace sc_dt;

#ifndef PRISM_V2SC_INTEGER_TYPES
#define PRISM_V2SC_INTEGER_TYPES
template <int Width> using prism_v2sc_uint_t = typename std::conditional<(Width <= 64), sc_uint<Width>, sc_biguint<Width>>::type;
template <int Width> using prism_v2sc_int_t = typename std::conditional<(Width <= 64), sc_int<Width>, sc_bigint<Width>>::type;
constexpr int prism_v2sc_clog2(int value) { int result = 0; for (int current = value - 1; current > 0; current >>= 1) ++result; return result; }
#endif

#ifndef PRISM_V2SC_MOD_E603_GNRL_TECH_RAM__PRISM_P_B4C5E9DA54_HPP
#define PRISM_V2SC_MOD_E603_GNRL_TECH_RAM__PRISM_P_B4C5E9DA54_HPP

template <int DP = 128, int FORCE_X2ZERO = 0, int DW = 40, int MW = 1, int AW = 7>
SC_MODULE(e603_gnrl_tech_ram__prism_p_b4c5e9da54) {
  sc_in<bool> sd;
  sc_in<bool> ds;
  sc_in<bool> ls;
  sc_in<bool> rst_n;
  sc_in<bool> clk;
  sc_in<prism_v2sc_uint_t<(((DW-1) >= (0)) ? ((DW-1) - (0) + 1) : ((0) - (DW-1) + 1))>> din;
  sc_in<prism_v2sc_uint_t<(((AW-1) >= (0)) ? ((AW-1) - (0) + 1) : ((0) - (AW-1) + 1))>> addr;
  sc_in<bool> cs;
  sc_in<bool> we;
  sc_in<prism_v2sc_uint_t<(((MW-1) >= (0)) ? ((MW-1) - (0) + 1) : ((0) - (MW-1) + 1))>> wem;
  sc_out<prism_v2sc_uint_t<(((DW-1) >= (0)) ? ((DW-1) - (0) + 1) : ((0) - (DW-1) + 1))>> dout;

  e603_sim_ram__prism_p_b4c5e9da54<128, 0, 40, 1, 7> u_ram;

  SC_CTOR(e603_gnrl_tech_ram__prism_p_b4c5e9da54)
    : u_ram("u_ram")
  {
    u_ram.clk(clk);
    u_ram.din(din);
    u_ram.addr(addr);
    u_ram.cs(cs);
    u_ram.we(we);
    u_ram.wem(wem);
    u_ram.dout(dout);
  }
};

#endif  // PRISM_V2SC_MOD_E603_GNRL_TECH_RAM__PRISM_P_B4C5E9DA54_HPP
