"""SystemC code generation."""

from __future__ import annotations

import re

from prism_v2sc.ir.model import (
    ContinuousAssignIR,
    DesignIR,
    GenerateForIR,
    InstanceIR,
    ModuleIR,
    PortIR,
    ProcessIR,
    SignalIR,
    WidthIR,
)

from .writer import CodeWriter


def banner() -> str:
    """Return the banner used by generated SystemC files."""
    return "// Generated by prism_v2sc\n"


def generate_systemc_header(design: DesignIR) -> str:
    """Generate a single-header SystemC model for the supported subset."""
    writer = CodeWriter()
    guard = f"PRISM_V2SC_{_sanitize_identifier(design.top).upper()}_HPP"

    writer.line(banner().rstrip())
    writer.line("#pragma once")
    writer.line()
    writer.line("#include <systemc>")
    writer.line("#include <string>")
    writer.line()
    writer.line("using namespace sc_core;")
    writer.line("using namespace sc_dt;")
    writer.line()
    writer.line(f"#ifndef {guard}")
    writer.line(f"#define {guard}")
    writer.line()

    for module in design.modules:
        _emit_module(writer, module)
        writer.line()

    writer.line(f"#endif  // {guard}")
    return writer.render()


def _emit_module(writer: CodeWriter, module: ModuleIR) -> None:
    class_name = _sanitize_identifier(module.name)
    if module.parameters:
        template_params = ", ".join(
            f"int {_sanitize_identifier(parameter.name)} = {_cpp_expr(parameter.value)}"
            for parameter in module.parameters
        )
        writer.line(f"template <{template_params}>")
    writer.line(f"SC_MODULE({class_name}) {{")
    writer.indent()

    for port in module.ports:
        writer.line(f"{_port_type(port)} {_sanitize_identifier(port.name)};")
    if module.ports:
        writer.line()

    for signal in module.signals:
        writer.line(f"{_signal_type(signal)} {_sanitize_identifier(signal.name)};")
    if module.signals:
        writer.line()

    for instance in module.instances:
        writer.line(f"{_instance_type(instance)} {_sanitize_identifier(instance.name)};")
    for generate_for in module.generate_fors:
        for instance in generate_for.instances:
            writer.line(
                f"sc_vector<{_instance_type(instance)}> "
                f"{_sanitize_identifier(generate_for.name)}_{_sanitize_identifier(instance.name)};"
            )
    if module.instances or module.generate_fors:
        writer.line()

    methods = _method_specs(module)
    for method_name, body_lines in methods:
        writer.line(f"void {method_name}() {{")
        writer.indent()
        for body_line in body_lines:
            writer.line(body_line)
        writer.dedent()
        writer.line("}")
        writer.line()

    _emit_constructor(writer, module, methods)
    writer.dedent()
    writer.line("};")


def _emit_constructor(
    writer: CodeWriter,
    module: ModuleIR,
    methods: list[tuple[str, list[str]]],
) -> None:
    class_name = _sanitize_identifier(module.name)
    init_list = [f"{_sanitize_identifier(instance.name)}(\"{instance.name}\")" for instance in module.instances]
    for generate_for in module.generate_fors:
        for instance in generate_for.instances:
            vector_name = f"{_sanitize_identifier(generate_for.name)}_{_sanitize_identifier(instance.name)}"
            init_list.append(
                f"{vector_name}(\"{vector_name}\", {_generate_for_count_expr(generate_for)})"
            )
    if init_list:
        writer.line(f"SC_CTOR({class_name})")
        writer.indent()
        writer.line(": " + ", ".join(init_list))
        writer.dedent()
        writer.line("{")
    else:
        writer.line(f"SC_CTOR({class_name}) {{")
    writer.indent()

    for method_name, _body_lines in methods:
        writer.line(f"SC_METHOD({method_name});")
        sensitivity = _method_sensitivity(module, method_name)
        if sensitivity:
            writer.line("sensitive" + "".join(f" << {name}" for name in sensitivity) + ";")
        else:
            writer.line("// No inferred sensitivity; method will need manual review.")
        writer.line()

    for instance in module.instances:
        instance_name = _sanitize_identifier(instance.name)
        _emit_instance_bindings(writer, instance_name, instance)

    for generate_for in module.generate_fors:
        loop_var = _sanitize_identifier(generate_for.var)
        vector_count = _generate_for_count_expr(generate_for)
        writer.line(f"for (int {loop_var} = 0; {loop_var} < {vector_count}; ++{loop_var}) {{")
        writer.indent()
        for instance in generate_for.instances:
            vector_name = f"{_sanitize_identifier(generate_for.name)}_{_sanitize_identifier(instance.name)}"
            _emit_instance_bindings(writer, f"{vector_name}[{loop_var}]", instance, loop_var=loop_var)
        writer.dedent()
        writer.line("}")

    writer.dedent()
    writer.line("}")


def _emit_instance_bindings(
    writer: CodeWriter,
    instance_ref: str,
    instance: InstanceIR,
    loop_var: str | None = None,
) -> None:
    for port in instance.ports:
        if port.name:
            writer.line(
                f"{instance_ref}.{_sanitize_identifier(port.name)}"
                f"({_cpp_binding_expr(port.value, loop_var=loop_var)});"
            )
        else:
            writer.line(f"// Positional port binding not emitted for {instance.name}: {port.value}")


def _method_specs(module: ModuleIR) -> list[tuple[str, list[str]]]:
    specs: list[tuple[str, list[str]]] = []
    for index, assign in enumerate(module.continuous_assigns):
        specs.append((f"assign_{index}", [_emit_assignment(assign.left, assign.right)]))

    comb_index = 0
    ff_index = 0
    for process in module.processes:
        if process.kind == "always_comb":
            specs.append((f"always_comb_{comb_index}", _emit_comb_process(process)))
            comb_index += 1
        elif process.kind == "always_ff":
            specs.append((f"always_ff_{ff_index}", _emit_structured_statements(process)))
            ff_index += 1
    return specs


def _method_sensitivity(module: ModuleIR, method_name: str) -> list[str]:
    if method_name.startswith("assign_"):
        index = int(method_name.removeprefix("assign_"))
        return _identifiers(module.continuous_assigns[index].right)

    if method_name.startswith("always_comb_"):
        index = int(method_name.removeprefix("always_comb_"))
        comb_processes = [process for process in module.processes if process.kind == "always_comb"]
        process = comb_processes[index]
        explicit = [item.signal for item in process.sensitivity if item.edge in {"all", "level"} and item.signal]
        if explicit:
            return [_sanitize_identifier(name) for name in explicit if name != "*"]
        read_names: list[str] = []
        for statement in process.statements:
            if "=" in statement:
                read_names.extend(_identifiers(statement.split("=", maxsplit=1)[1]))
        return _dedupe(read_names)

    if method_name.startswith("always_ff_"):
        index = int(method_name.removeprefix("always_ff_"))
        ff_processes = [process for process in module.processes if process.kind == "always_ff"]
        process = ff_processes[index]
        return [
            f"{_sanitize_identifier(item.signal)}.{_systemc_edge(item.edge)}()"
            for item in process.sensitivity
            if item.edge in {"posedge", "negedge"}
        ]

    return []


def _emit_comb_process(process: ProcessIR) -> list[str]:
    if process.structured_statements:
        return _emit_structured_statements(process)

    lines: list[str] = []
    for statement in process.statements:
        if "<=" in statement:
            left, right = statement.split("<=", maxsplit=1)
            lines.append(_emit_assignment(left.strip(), right.strip()))
        elif "=" in statement:
            left, right = statement.split("=", maxsplit=1)
            lines.append(_emit_assignment(left.strip(), right.strip()))
        else:
            lines.append(f"// Unsupported statement: {statement}")
    return lines


def _emit_structured_statements(process: ProcessIR) -> list[str]:
    if not process.structured_statements:
        return ["// Empty process."]
    lines: list[str] = []
    for statement in process.structured_statements:
        lines.extend(_emit_structured_statement(statement, indent_level=0))
    return lines


def _emit_structured_statement(statement: dict[str, object], indent_level: int) -> list[str]:
    prefix = "  " * indent_level
    kind = statement.get("type")

    if kind in {"blocking_assign", "nonblocking_assign"}:
        return [prefix + _emit_assignment(str(statement["left"]), str(statement["right"]))]

    if kind == "if":
        cond = _cpp_rvalue(str(statement["cond"]))
        lines = [f"{prefix}if ({cond}) {{"]
        for child in _as_statement_list(statement.get("true")):
            lines.extend(_emit_structured_statement(child, indent_level + 1))
        false_branch = _as_statement_list(statement.get("false"))
        if false_branch:
            lines.append(f"{prefix}}} else {{")
            for child in false_branch:
                lines.extend(_emit_structured_statement(child, indent_level + 1))
        lines.append(f"{prefix}}}")
        return lines

    node = statement.get("node", kind)
    return [f"{prefix}// Unsupported statement: {node}"]


def _as_statement_list(value: object) -> list[dict[str, object]]:
    if not isinstance(value, list):
        return []
    return [item for item in value if isinstance(item, dict)]


def _emit_assignment(left: str, right: str) -> str:
    return f"{_cpp_lvalue(left)}.write({_cpp_rvalue(right)});"


def _port_type(port: PortIR) -> str:
    dtype = _sc_type(port.width, port.signed)
    if port.direction == "input":
        return f"sc_in<{dtype}>"
    if port.direction == "output":
        return f"sc_out<{dtype}>"
    if port.direction == "inout":
        return f"sc_inout<{dtype}>"
    return f"sc_signal<{dtype}>"


def _signal_type(signal: SignalIR) -> str:
    return f"sc_signal<{_sc_type(signal.width, signal.signed)}>"


def _sc_type(width: WidthIR | None, signed: bool) -> str:
    width_expr = _width_expr(width)
    if width_expr == "1":
        return "bool"
    return f"sc_{'int' if signed else 'uint'}<{width_expr}>"


def _width_expr(width: WidthIR | None) -> str:
    if width is None:
        return "1"
    msb = _cpp_expr(width.msb)
    lsb = _cpp_expr(width.lsb)
    if msb.isdecimal() and lsb.isdecimal():
        return str(abs(int(msb) - int(lsb)) + 1)
    return f"(({msb}) - ({lsb}) + 1)"


def _instance_type(instance: InstanceIR) -> str:
    base = _sanitize_identifier(instance.module)
    if not instance.parameters:
        return base
    args = ", ".join(_cpp_expr(arg.value) for arg in instance.parameters)
    return f"{base}<{args}>"


def _generate_for_count_expr(generate_for: GenerateForIR) -> str:
    condition = _strip_outer_parens(generate_for.condition)
    match = re.fullmatch(
        rf"{re.escape(generate_for.var)}\s*<\s*(?P<limit>[A-Za-z_][A-Za-z0-9_]*|\d+)",
        condition,
    )
    if match and _is_zero_init(generate_for) and _is_increment_by_one(generate_for):
        return _cpp_expr(match.group("limit"))
    return f"/* unsupported generate count: {generate_for.condition} */ 0"


def _strip_outer_parens(expr: str) -> str:
    stripped = expr.strip()
    while stripped.startswith("(") and stripped.endswith(")"):
        depth = 0
        balanced_outer = True
        for index, char in enumerate(stripped):
            if char == "(":
                depth += 1
            elif char == ")":
                depth -= 1
                if depth == 0 and index != len(stripped) - 1:
                    balanced_outer = False
                    break
        if not balanced_outer:
            break
        stripped = stripped[1:-1].strip()
    return stripped


def _is_zero_init(generate_for: GenerateForIR) -> bool:
    return re.fullmatch(rf"{re.escape(generate_for.var)}\s*=\s*0", generate_for.init) is not None


def _is_increment_by_one(generate_for: GenerateForIR) -> bool:
    return re.fullmatch(
        rf"{re.escape(generate_for.var)}\s*=\s*\({re.escape(generate_for.var)}\s*\+\s*1\)",
        generate_for.step,
    ) is not None


def _cpp_lvalue(expr: str) -> str:
    return _sanitize_identifier(expr)


def _cpp_rvalue(expr: str) -> str:
    rendered = _cpp_expr(expr)
    for name in sorted(_identifiers(expr), key=len, reverse=True):
        rendered = re.sub(rf"\b{re.escape(name)}\b", f"{_sanitize_identifier(name)}.read()", rendered)
    return rendered


def _cpp_expr(expr: str) -> str:
    return _convert_verilog_constants(expr)


def _cpp_binding_expr(expr: str, loop_var: str | None = None) -> str:
    match = re.fullmatch(r"(?P<name>[A-Za-z_][A-Za-z0-9_$]*)\[(?P<index>[A-Za-z_][A-Za-z0-9_$]*|\d+)\]", expr)
    if match:
        name = _sanitize_identifier(match.group("name"))
        index = match.group("index")
        if loop_var is not None and index == loop_var:
            return f"{name} /* TODO: bind bit-select [{loop_var}] via generated scalar signal */"
        return f"{name}[{_sanitize_identifier(index)}]" if not index.isdecimal() else f"{name}[{index}]"
    return _sanitize_identifier(expr)


def _convert_verilog_constants(expr: str) -> str:
    def replace_sized(match: re.Match[str]) -> str:
        base = match.group("base").lower()
        value = match.group("value").replace("_", "")
        if any(char in value.lower() for char in "xz?"):
            return "0"
        if base == "h":
            return f"0x{value}"
        if base == "b":
            return f"0b{value}"
        if base == "o":
            return f"0{value}"
        return value

    def replace_unsized(match: re.Match[str]) -> str:
        base = match.group("base").lower()
        value = match.group("value").replace("_", "")
        if any(char in value.lower() for char in "xz?"):
            return "0"
        if base == "h":
            return f"0x{value}"
        if base == "b":
            return f"0b{value}"
        if base == "o":
            return f"0{value}"
        return value

    rendered = re.sub(
        r"\b\d+'\s*(?P<base>[bodhBODH])(?P<value>[0-9a-fA-F_xXzZ?]+)",
        replace_sized,
        expr,
    )
    rendered = re.sub(
        r"'\s*(?P<base>[bodhBODH])(?P<value>[0-9a-fA-F_xXzZ?]+)",
        replace_unsized,
        rendered,
    )
    return rendered


def _systemc_edge(edge: str) -> str:
    if edge == "negedge":
        return "neg"
    return "pos"


def _identifiers(expr: str) -> list[str]:
    tokens = re.findall(r"\b[A-Za-z_][A-Za-z0-9_$]*\b", expr)
    return _dedupe([token for token in tokens if token not in {"sc_uint", "sc_int"}])


def _dedupe(items: list[str]) -> list[str]:
    seen: set[str] = set()
    result: list[str] = []
    for item in items:
        clean = _sanitize_identifier(item)
        if clean not in seen:
            seen.add(clean)
            result.append(clean)
    return result


def _sanitize_identifier(name: str) -> str:
    cleaned = re.sub(r"\W", "_", name)
    if not cleaned:
        return "unnamed"
    if cleaned[0].isdigit():
        return f"_{cleaned}"
    return cleaned
