// Generated by prism_v2sc
#pragma once

#include <array>
#include <systemc>
#include <string>
#include <type_traits>

#include "sirv_gnrl_dfflr__prism_p_e83a2e89d4.hpp"
#include "sirv_gnrl_dffl__prism_p_e83a2e89d4.hpp"

using namespace sc_core;
using namespace sc_dt;

#ifndef PRISM_V2SC_INTEGER_TYPES
#define PRISM_V2SC_INTEGER_TYPES
template <int Width> using prism_v2sc_uint_t = typename std::conditional<(Width <= 64), sc_uint<Width>, sc_biguint<Width>>::type;
template <int Width> using prism_v2sc_int_t = typename std::conditional<(Width <= 64), sc_int<Width>, sc_bigint<Width>>::type;
constexpr int prism_v2sc_clog2(int value) { int result = 0; for (int current = value - 1; current > 0; current >>= 1) ++result; return result; }
#endif

#ifndef PRISM_V2SC_MOD_SIRV_GNRL_PIPE_STAGE__PRISM_P_FD03E305DB_HPP
#define PRISM_V2SC_MOD_SIRV_GNRL_PIPE_STAGE__PRISM_P_FD03E305DB_HPP

template <int CUT_READY = 0, int DP = 1, int DW = 1>
SC_MODULE(sirv_gnrl_pipe_stage__prism_p_fd03e305db) {
  sc_in<bool> i_vld;
  sc_out<bool> i_rdy;
  sc_in<prism_v2sc_uint_t<(((DW-1) >= (0)) ? ((DW-1) - (0) + 1) : ((0) - (DW-1) + 1))>> i_dat;
  sc_out<bool> o_vld;
  sc_in<bool> o_rdy;
  sc_out<prism_v2sc_uint_t<(((DW-1) >= (0)) ? ((DW-1) - (0) + 1) : ((0) - (DW-1) + 1))>> o_dat;
  sc_in<bool> clk;
  sc_in<bool> rst_n;

  sc_signal<bool> dp_gt_0_vld_set;
  sc_signal<bool> dp_gt_0_vld_clr;
  sc_signal<bool> dp_gt_0_vld_ena;
  sc_signal<bool> dp_gt_0_vld_r;
  sc_signal<bool> dp_gt_0_vld_nxt;

  sirv_gnrl_dfflr__prism_p_e83a2e89d4<1> dp_gt_0_vld_dfflr;
  sirv_gnrl_dffl__prism_p_e83a2e89d4<1> dp_gt_0_dat_dfflr;
  sc_signal<sc_uint<1>> __bridge_dp_gt_0_vld_dfflr_dnxt;
  sc_signal<sc_uint<1>> __bridge_dp_gt_0_vld_dfflr_qout;

  void assign_0() {
    dp_gt_0_vld_set.write((i_vld.read() & i_rdy.read()));
  }

  void assign_1() {
    dp_gt_0_vld_clr.write((o_vld.read() & o_rdy.read()));
  }

  void assign_2() {
    dp_gt_0_vld_ena.write((dp_gt_0_vld_set.read() | dp_gt_0_vld_clr.read()));
  }

  void assign_3() {
    dp_gt_0_vld_nxt.write((dp_gt_0_vld_set.read() | (!dp_gt_0_vld_clr.read())));
  }

  void assign_4() {
    o_vld.write(dp_gt_0_vld_r.read());
  }

  void assign_5() {
    i_rdy.write(((!dp_gt_0_vld_r.read()) | dp_gt_0_vld_clr.read()));
  }

  void __bridge_method_dp_gt_0_vld_dfflr_dnxt() {
    __bridge_dp_gt_0_vld_dfflr_dnxt.write(dp_gt_0_vld_nxt.read());
  }

  void __bridge_method_dp_gt_0_vld_dfflr_qout() {
    dp_gt_0_vld_r.write(__bridge_dp_gt_0_vld_dfflr_qout.read());
  }

  SC_CTOR(sirv_gnrl_pipe_stage__prism_p_fd03e305db)
    : dp_gt_0_vld_dfflr("dp_gt_0_vld_dfflr"), dp_gt_0_dat_dfflr("dp_gt_0_dat_dfflr")
  {
    SC_METHOD(assign_0);
    sensitive << i_vld << i_rdy;

    SC_METHOD(assign_1);
    sensitive << o_vld << o_rdy;

    SC_METHOD(assign_2);
    sensitive << dp_gt_0_vld_set << dp_gt_0_vld_clr;

    SC_METHOD(assign_3);
    sensitive << dp_gt_0_vld_set << dp_gt_0_vld_clr;

    SC_METHOD(assign_4);
    sensitive << dp_gt_0_vld_r;

    SC_METHOD(assign_5);
    sensitive << dp_gt_0_vld_r << dp_gt_0_vld_clr;

    dp_gt_0_vld_dfflr.lden(dp_gt_0_vld_ena);
    dp_gt_0_vld_dfflr.dnxt(__bridge_dp_gt_0_vld_dfflr_dnxt);
    dp_gt_0_vld_dfflr.qout(__bridge_dp_gt_0_vld_dfflr_qout);
    dp_gt_0_vld_dfflr.clk(clk);
    dp_gt_0_vld_dfflr.rst_n(rst_n);
    dp_gt_0_dat_dfflr.lden(dp_gt_0_vld_set);
    dp_gt_0_dat_dfflr.dnxt(i_dat);
    dp_gt_0_dat_dfflr.qout(o_dat);
    dp_gt_0_dat_dfflr.clk(clk);
    SC_METHOD(__bridge_method_dp_gt_0_vld_dfflr_dnxt);
    sensitive << dp_gt_0_vld_nxt;

    SC_METHOD(__bridge_method_dp_gt_0_vld_dfflr_qout);
    sensitive << __bridge_dp_gt_0_vld_dfflr_qout;

  }
};

#endif  // PRISM_V2SC_MOD_SIRV_GNRL_PIPE_STAGE__PRISM_P_FD03E305DB_HPP
