// Generated by prism_v2sc
#pragma once

#include <array>
#include <systemc>
#include <string>
#include <type_traits>

#include "sirv_gnrl_fifo__prism_p_33c9b14979.hpp"
#include "sirv_gnrl_fifo__prism_p_7ce778fcdb.hpp"
#include "sirv_gnrl_dfflr__prism_p_e83a2e89d4.hpp"

using namespace sc_core;
using namespace sc_dt;

#ifndef PRISM_V2SC_INTEGER_TYPES
#define PRISM_V2SC_INTEGER_TYPES
template <int Width> using prism_v2sc_uint_t = typename std::conditional<(Width <= 64), sc_uint<Width>, sc_biguint<Width>>::type;
template <int Width> using prism_v2sc_int_t = typename std::conditional<(Width <= 64), sc_int<Width>, sc_bigint<Width>>::type;
constexpr int prism_v2sc_clog2(int value) { int result = 0; for (int current = value - 1; current > 0; current >>= 1) ++result; return result; }
#endif

#ifndef PRISM_V2SC_MOD_SIRV_GNRL_ICB_BUFFER_HPP
#define PRISM_V2SC_MOD_SIRV_GNRL_ICB_BUFFER_HPP

template <int OUTS_CNT_W = 1, int AW = 32, int DW = 32, int CMD_CUT_READY = 1, int RSP_CUT_READY = 1, int CMD_DP = 1, int RSP_DP = 1, int USR_W = 1, int CMD_PACK_W = (((((((((1 + AW) + DW) + (DW / 8)) + 1) + 1) + 2) + 2) + 2) + USR_W), int RSP_PACK_W = ((2 + DW) + USR_W)>
SC_MODULE(sirv_gnrl_icb_buffer) {
  sc_out<bool> icb_buffer_active;
  sc_in<bool> i_icb_cmd_valid;
  sc_out<bool> i_icb_cmd_ready;
  sc_in<sc_uint<1>> i_icb_cmd_read;
  sc_in<prism_v2sc_uint_t<(((AW-1) >= (0)) ? ((AW-1) - (0) + 1) : ((0) - (AW-1) + 1))>> i_icb_cmd_addr;
  sc_in<prism_v2sc_uint_t<(((DW-1) >= (0)) ? ((DW-1) - (0) + 1) : ((0) - (DW-1) + 1))>> i_icb_cmd_wdata;
  sc_in<prism_v2sc_uint_t<(((DW/8-1) >= (0)) ? ((DW/8-1) - (0) + 1) : ((0) - (DW/8-1) + 1))>> i_icb_cmd_wmask;
  sc_in<bool> i_icb_cmd_lock;
  sc_in<bool> i_icb_cmd_excl;
  sc_in<sc_uint<2>> i_icb_cmd_size;
  sc_in<sc_uint<2>> i_icb_cmd_burst;
  sc_in<sc_uint<2>> i_icb_cmd_beat;
  sc_in<prism_v2sc_uint_t<(((USR_W-1) >= (0)) ? ((USR_W-1) - (0) + 1) : ((0) - (USR_W-1) + 1))>> i_icb_cmd_usr;
  sc_out<bool> i_icb_rsp_valid;
  sc_in<bool> i_icb_rsp_ready;
  sc_out<bool> i_icb_rsp_err;
  sc_out<bool> i_icb_rsp_excl_ok;
  sc_out<prism_v2sc_uint_t<(((DW-1) >= (0)) ? ((DW-1) - (0) + 1) : ((0) - (DW-1) + 1))>> i_icb_rsp_rdata;
  sc_out<prism_v2sc_uint_t<(((USR_W-1) >= (0)) ? ((USR_W-1) - (0) + 1) : ((0) - (USR_W-1) + 1))>> i_icb_rsp_usr;
  sc_out<bool> o_icb_cmd_valid;
  sc_in<bool> o_icb_cmd_ready;
  sc_out<sc_uint<1>> o_icb_cmd_read;
  sc_out<prism_v2sc_uint_t<(((AW-1) >= (0)) ? ((AW-1) - (0) + 1) : ((0) - (AW-1) + 1))>> o_icb_cmd_addr;
  sc_out<prism_v2sc_uint_t<(((DW-1) >= (0)) ? ((DW-1) - (0) + 1) : ((0) - (DW-1) + 1))>> o_icb_cmd_wdata;
  sc_out<prism_v2sc_uint_t<(((DW/8-1) >= (0)) ? ((DW/8-1) - (0) + 1) : ((0) - (DW/8-1) + 1))>> o_icb_cmd_wmask;
  sc_out<bool> o_icb_cmd_lock;
  sc_out<bool> o_icb_cmd_excl;
  sc_out<sc_uint<2>> o_icb_cmd_size;
  sc_out<sc_uint<2>> o_icb_cmd_burst;
  sc_out<sc_uint<2>> o_icb_cmd_beat;
  sc_out<prism_v2sc_uint_t<(((USR_W-1) >= (0)) ? ((USR_W-1) - (0) + 1) : ((0) - (USR_W-1) + 1))>> o_icb_cmd_usr;
  sc_in<bool> o_icb_rsp_valid;
  sc_out<bool> o_icb_rsp_ready;
  sc_in<bool> o_icb_rsp_err;
  sc_in<bool> o_icb_rsp_excl_ok;
  sc_in<prism_v2sc_uint_t<(((DW-1) >= (0)) ? ((DW-1) - (0) + 1) : ((0) - (DW-1) + 1))>> o_icb_rsp_rdata;
  sc_in<prism_v2sc_uint_t<(((USR_W-1) >= (0)) ? ((USR_W-1) - (0) + 1) : ((0) - (USR_W-1) + 1))>> o_icb_rsp_usr;
  sc_in<bool> clk;
  sc_in<bool> rst_n;

  sc_signal<prism_v2sc_uint_t<(((CMD_PACK_W-1) >= (0)) ? ((CMD_PACK_W-1) - (0) + 1) : ((0) - (CMD_PACK_W-1) + 1))>> cmd_fifo_i_dat;
  sc_signal<prism_v2sc_uint_t<(((CMD_PACK_W-1) >= (0)) ? ((CMD_PACK_W-1) - (0) + 1) : ((0) - (CMD_PACK_W-1) + 1))>> cmd_fifo_o_dat;
  sc_signal<prism_v2sc_uint_t<(((RSP_PACK_W-1) >= (0)) ? ((RSP_PACK_W-1) - (0) + 1) : ((0) - (RSP_PACK_W-1) + 1))>> rsp_fifo_i_dat;
  sc_signal<prism_v2sc_uint_t<(((RSP_PACK_W-1) >= (0)) ? ((RSP_PACK_W-1) - (0) + 1) : ((0) - (RSP_PACK_W-1) + 1))>> rsp_fifo_o_dat;
  sc_signal<bool> outs_cnt_inc;
  sc_signal<bool> outs_cnt_dec;
  sc_signal<bool> outs_cnt_ena;
  sc_signal<bool> outs_cnt_r;
  sc_signal<bool> outs_cnt_nxt;

  sirv_gnrl_fifo__prism_p_33c9b14979<1, 0, 1, 78> u_sirv_gnrl_cmd_fifo;
  sirv_gnrl_fifo__prism_p_7ce778fcdb<1, 0, 1, 35> u_sirv_gnrl_rsp_fifo;
  sirv_gnrl_dfflr__prism_p_e83a2e89d4<1> outs_cnt_dfflr;
  sc_signal<sc_uint<1>> __bridge_outs_cnt_dfflr_dnxt;
  sc_signal<sc_uint<1>> __bridge_outs_cnt_dfflr_qout;

  void assign_0() {
    cmd_fifo_i_dat.write(sc_biguint<78>(((sc_biguint<78>(i_icb_cmd_read.read()) << 77) | (sc_biguint<78>(i_icb_cmd_addr.read()) << 45) | (sc_biguint<78>(i_icb_cmd_wdata.read()) << 13) | (sc_biguint<78>(i_icb_cmd_wmask.read()) << 9) | (sc_biguint<78>(i_icb_cmd_lock.read()) << 8) | (sc_biguint<78>(i_icb_cmd_excl.read()) << 7) | (sc_biguint<78>(i_icb_cmd_size.read()) << 5) | (sc_biguint<78>(i_icb_cmd_burst.read()) << 3) | (sc_biguint<78>(i_icb_cmd_beat.read()) << 1) | sc_biguint<78>(i_icb_cmd_usr.read()))));
  }

  void assign_1() {
    auto __concat_rhs = sc_biguint<78>(cmd_fifo_o_dat.read());
    o_icb_cmd_read.write(sc_uint<1>(__concat_rhs[77]));
    o_icb_cmd_addr.write(sc_uint<32>(__concat_rhs.range(76, 45)));
    o_icb_cmd_wdata.write(sc_uint<32>(__concat_rhs.range(44, 13)));
    o_icb_cmd_wmask.write(sc_uint<4>(__concat_rhs.range(12, 9)));
    o_icb_cmd_lock.write(__concat_rhs[8]);
    o_icb_cmd_excl.write(__concat_rhs[7]);
    o_icb_cmd_size.write(sc_uint<2>(__concat_rhs.range(6, 5)));
    o_icb_cmd_burst.write(sc_uint<2>(__concat_rhs.range(4, 3)));
    o_icb_cmd_beat.write(sc_uint<2>(__concat_rhs.range(2, 1)));
    o_icb_cmd_usr.write(sc_uint<1>(__concat_rhs[0]));
  }

  void assign_2() {
    rsp_fifo_i_dat.write(sc_uint<35>(((sc_uint<35>(o_icb_rsp_err.read()) << 34) | (sc_uint<35>(o_icb_rsp_excl_ok.read()) << 33) | (sc_uint<35>(o_icb_rsp_rdata.read()) << 1) | sc_uint<35>(o_icb_rsp_usr.read()))));
  }

  void assign_3() {
    auto __concat_rhs = sc_uint<35>(rsp_fifo_o_dat.read());
    i_icb_rsp_err.write(__concat_rhs[34]);
    i_icb_rsp_excl_ok.write(__concat_rhs[33]);
    i_icb_rsp_rdata.write(sc_uint<32>(__concat_rhs.range(32, 1)));
    i_icb_rsp_usr.write(sc_uint<1>(__concat_rhs[0]));
  }

  void assign_4() {
    outs_cnt_inc.write((i_icb_cmd_valid.read() & i_icb_cmd_ready.read()));
  }

  void assign_5() {
    outs_cnt_dec.write((i_icb_rsp_valid.read() & i_icb_rsp_ready.read()));
  }

  void assign_6() {
    outs_cnt_ena.write((outs_cnt_inc.read() ^ outs_cnt_dec.read()));
  }

  void assign_7() {
    outs_cnt_nxt.write((outs_cnt_inc.read() ? (outs_cnt_r.read() + 0b1) : (outs_cnt_r.read() - 0b1)));
  }

  void assign_8() {
    icb_buffer_active.write((i_icb_cmd_valid.read() | (!(outs_cnt_r.read() == sc_uint<1>((sc_uint<1>(0b0)))))));
  }

  void __bridge_method_outs_cnt_dfflr_dnxt() {
    __bridge_outs_cnt_dfflr_dnxt.write(outs_cnt_nxt.read());
  }

  void __bridge_method_outs_cnt_dfflr_qout() {
    outs_cnt_r.write(__bridge_outs_cnt_dfflr_qout.read());
  }

  SC_CTOR(sirv_gnrl_icb_buffer)
    : u_sirv_gnrl_cmd_fifo("u_sirv_gnrl_cmd_fifo"), u_sirv_gnrl_rsp_fifo("u_sirv_gnrl_rsp_fifo"), outs_cnt_dfflr("outs_cnt_dfflr")
  {
    SC_METHOD(assign_0);
    sensitive << i_icb_cmd_read << i_icb_cmd_addr << i_icb_cmd_wdata << i_icb_cmd_wmask << i_icb_cmd_lock << i_icb_cmd_excl << i_icb_cmd_size << i_icb_cmd_burst << i_icb_cmd_beat << i_icb_cmd_usr;

    SC_METHOD(assign_1);
    sensitive << cmd_fifo_o_dat;

    SC_METHOD(assign_2);
    sensitive << o_icb_rsp_err << o_icb_rsp_excl_ok << o_icb_rsp_rdata << o_icb_rsp_usr;

    SC_METHOD(assign_3);
    sensitive << rsp_fifo_o_dat;

    SC_METHOD(assign_4);
    sensitive << i_icb_cmd_valid << i_icb_cmd_ready;

    SC_METHOD(assign_5);
    sensitive << i_icb_rsp_valid << i_icb_rsp_ready;

    SC_METHOD(assign_6);
    sensitive << outs_cnt_inc << outs_cnt_dec;

    SC_METHOD(assign_7);
    sensitive << outs_cnt_inc << outs_cnt_r;

    SC_METHOD(assign_8);
    sensitive << i_icb_cmd_valid << outs_cnt_r;

    u_sirv_gnrl_cmd_fifo.i_vld(i_icb_cmd_valid);
    u_sirv_gnrl_cmd_fifo.i_rdy(i_icb_cmd_ready);
    u_sirv_gnrl_cmd_fifo.i_dat(cmd_fifo_i_dat);
    u_sirv_gnrl_cmd_fifo.o_vld(o_icb_cmd_valid);
    u_sirv_gnrl_cmd_fifo.o_rdy(o_icb_cmd_ready);
    u_sirv_gnrl_cmd_fifo.o_dat(cmd_fifo_o_dat);
    u_sirv_gnrl_cmd_fifo.clk(clk);
    u_sirv_gnrl_cmd_fifo.rst_n(rst_n);
    u_sirv_gnrl_rsp_fifo.i_vld(o_icb_rsp_valid);
    u_sirv_gnrl_rsp_fifo.i_rdy(o_icb_rsp_ready);
    u_sirv_gnrl_rsp_fifo.i_dat(rsp_fifo_i_dat);
    u_sirv_gnrl_rsp_fifo.o_vld(i_icb_rsp_valid);
    u_sirv_gnrl_rsp_fifo.o_rdy(i_icb_rsp_ready);
    u_sirv_gnrl_rsp_fifo.o_dat(rsp_fifo_o_dat);
    u_sirv_gnrl_rsp_fifo.clk(clk);
    u_sirv_gnrl_rsp_fifo.rst_n(rst_n);
    outs_cnt_dfflr.lden(outs_cnt_ena);
    outs_cnt_dfflr.dnxt(__bridge_outs_cnt_dfflr_dnxt);
    outs_cnt_dfflr.qout(__bridge_outs_cnt_dfflr_qout);
    outs_cnt_dfflr.clk(clk);
    outs_cnt_dfflr.rst_n(rst_n);
    SC_METHOD(__bridge_method_outs_cnt_dfflr_dnxt);
    sensitive << outs_cnt_nxt;

    SC_METHOD(__bridge_method_outs_cnt_dfflr_qout);
    sensitive << __bridge_outs_cnt_dfflr_qout;

  }
};

#endif  // PRISM_V2SC_MOD_SIRV_GNRL_ICB_BUFFER_HPP
