// Generated by prism_v2sc
#pragma once

#include <array>
#include <systemc>
#include <string>
#include <type_traits>

#include "sirv_gnrl_dffr.hpp"

using namespace sc_core;
using namespace sc_dt;

#ifndef PRISM_V2SC_INTEGER_TYPES
#define PRISM_V2SC_INTEGER_TYPES
template <int Width> using prism_v2sc_uint_t = typename std::conditional<(Width <= 64), sc_uint<Width>, sc_biguint<Width>>::type;
template <int Width> using prism_v2sc_int_t = typename std::conditional<(Width <= 64), sc_int<Width>, sc_bigint<Width>>::type;
constexpr int prism_v2sc_clog2(int value) { int result = 0; for (int current = value - 1; current > 0; current >>= 1) ++result; return result; }
#endif

#ifndef PRISM_V2SC_MOD_SIRV_GNRL_SYNC_HPP
#define PRISM_V2SC_MOD_SIRV_GNRL_SYNC_HPP

template <int DP = 2, int DW = 1>
SC_MODULE(sirv_gnrl_sync) {
  sc_in<prism_v2sc_uint_t<(((DW-1) >= (0)) ? ((DW-1) - (0) + 1) : ((0) - (DW-1) + 1))>> din_a;
  sc_out<prism_v2sc_uint_t<(((DW-1) >= (0)) ? ((DW-1) - (0) + 1) : ((0) - (DW-1) + 1))>> dout;
  sc_in<bool> rst_n;
  sc_in<bool> clk;

  sc_signal<prism_v2sc_uint_t<(((DW-1) >= (0)) ? ((DW-1) - (0) + 1) : ((0) - (DW-1) + 1))>> sync_dat[(((DP-1) >= (0)) ? ((DP-1) - (0) + 1) : ((0) - (DP-1) + 1))];

  sirv_gnrl_dffr<1> sync_gen_0_i_is_0_sync_dffr;
  sirv_gnrl_dffr<1> sync_gen_1_i_is_not_0_sync_dffr;
  sc_signal<sc_uint<1>> __bridge_sync_gen_0_i_is_0_sync_dffr_qout;
  sc_signal<sc_uint<1>> __bridge_sync_gen_1_i_is_not_0_sync_dffr_dnxt;
  sc_signal<sc_uint<1>> __bridge_sync_gen_1_i_is_not_0_sync_dffr_qout;

  void assign_0() {
    dout.write(sync_dat[(DP - 1)].read());
  }

  void __bridge_method_sync_gen_0_i_is_0_sync_dffr_qout() {
    sync_dat[0].write(sc_uint<1>(__bridge_sync_gen_0_i_is_0_sync_dffr_qout.read()));
  }

  void __bridge_method_sync_gen_1_i_is_not_0_sync_dffr_dnxt() {
    __bridge_sync_gen_1_i_is_not_0_sync_dffr_dnxt.write(sync_dat[(1 - 1)].read());
  }

  void __bridge_method_sync_gen_1_i_is_not_0_sync_dffr_qout() {
    sync_dat[1].write(sc_uint<1>(__bridge_sync_gen_1_i_is_not_0_sync_dffr_qout.read()));
  }

  SC_CTOR(sirv_gnrl_sync)
    : sync_gen_0_i_is_0_sync_dffr("sync_gen_0_i_is_0_sync_dffr"), sync_gen_1_i_is_not_0_sync_dffr("sync_gen_1_i_is_not_0_sync_dffr")
  {
    SC_METHOD(assign_0);
    sensitive << sync_dat[0] << sync_dat[1];

    sync_gen_0_i_is_0_sync_dffr.dnxt(din_a);
    sync_gen_0_i_is_0_sync_dffr.qout(__bridge_sync_gen_0_i_is_0_sync_dffr_qout);
    sync_gen_0_i_is_0_sync_dffr.clk(clk);
    sync_gen_0_i_is_0_sync_dffr.rst_n(rst_n);
    sync_gen_1_i_is_not_0_sync_dffr.dnxt(__bridge_sync_gen_1_i_is_not_0_sync_dffr_dnxt);
    sync_gen_1_i_is_not_0_sync_dffr.qout(__bridge_sync_gen_1_i_is_not_0_sync_dffr_qout);
    sync_gen_1_i_is_not_0_sync_dffr.clk(clk);
    sync_gen_1_i_is_not_0_sync_dffr.rst_n(rst_n);
    SC_METHOD(__bridge_method_sync_gen_0_i_is_0_sync_dffr_qout);
    sensitive << __bridge_sync_gen_0_i_is_0_sync_dffr_qout;

    SC_METHOD(__bridge_method_sync_gen_1_i_is_not_0_sync_dffr_dnxt);
    sensitive << sync_dat[0] << sync_dat[1];

    SC_METHOD(__bridge_method_sync_gen_1_i_is_not_0_sync_dffr_qout);
    sensitive << __bridge_sync_gen_1_i_is_not_0_sync_dffr_qout;

  }
};

#endif  // PRISM_V2SC_MOD_SIRV_GNRL_SYNC_HPP
