// Generated by prism_v2sc
#pragma once

#include <array>
#include <systemc>
#include <string>
#include <type_traits>

#include "sirv_gnrl_xchecker.hpp"

using namespace sc_core;
using namespace sc_dt;

#ifndef PRISM_V2SC_INTEGER_TYPES
#define PRISM_V2SC_INTEGER_TYPES
template <int Width> using prism_v2sc_uint_t = typename std::conditional<(Width <= 64), sc_uint<Width>, sc_biguint<Width>>::type;
template <int Width> using prism_v2sc_int_t = typename std::conditional<(Width <= 64), sc_int<Width>, sc_bigint<Width>>::type;
constexpr int prism_v2sc_clog2(int value) { int result = 0; for (int current = value - 1; current > 0; current >>= 1) ++result; return result; }
#endif

#ifndef PRISM_V2SC_MOD_SIRV_GNRL_DFFL__PRISM_P_E83A2E89D4_HPP
#define PRISM_V2SC_MOD_SIRV_GNRL_DFFL__PRISM_P_E83A2E89D4_HPP

template <int DW = 1>
SC_MODULE(sirv_gnrl_dffl__prism_p_e83a2e89d4) {
  sc_in<bool> lden;
  sc_in<prism_v2sc_uint_t<(((DW-1) >= (0)) ? ((DW-1) - (0) + 1) : ((0) - (DW-1) + 1))>> dnxt;
  sc_out<prism_v2sc_uint_t<(((DW-1) >= (0)) ? ((DW-1) - (0) + 1) : ((0) - (DW-1) + 1))>> qout;
  sc_in<bool> clk;

  sc_signal<prism_v2sc_uint_t<(((DW-1) >= (0)) ? ((DW-1) - (0) + 1) : ((0) - (DW-1) + 1))>> qout_r;

  sirv_gnrl_xchecker<1> sirv_gnrl_xchecker__inst;
  sc_signal<sc_uint<1>> __bridge_sirv_gnrl_xchecker__inst_i_dat;

  void assign_0() {
    qout.write(qout_r.read());
  }

  void always_ff_0() {
    auto __next_qout_r = qout_r.read();
    if ((lden.read() == 0b1)) {
      __next_qout_r = dnxt.read();
    }
    qout_r.write(__next_qout_r);
  }

  void __bridge_method_sirv_gnrl_xchecker__inst_i_dat() {
    __bridge_sirv_gnrl_xchecker__inst_i_dat.write(lden.read());
  }

  SC_CTOR(sirv_gnrl_dffl__prism_p_e83a2e89d4)
    : sirv_gnrl_xchecker__inst("sirv_gnrl_xchecker__inst")
  {
    SC_METHOD(assign_0);
    sensitive << qout_r;

    SC_METHOD(always_ff_0);
    sensitive << clk.pos();

    sirv_gnrl_xchecker__inst.i_dat(__bridge_sirv_gnrl_xchecker__inst_i_dat);
    sirv_gnrl_xchecker__inst.clk(clk);
    SC_METHOD(__bridge_method_sirv_gnrl_xchecker__inst_i_dat);
    sensitive << lden;

  }
};

#endif  // PRISM_V2SC_MOD_SIRV_GNRL_DFFL__PRISM_P_E83A2E89D4_HPP
