// Generated by prism_v2sc
#pragma once

#include <array>
#include <systemc>
#include <string>
#include <type_traits>

#include "e603_core_wrapper.hpp"
#include "e603_rams_wrapper.hpp"

using namespace sc_core;
using namespace sc_dt;

#ifndef PRISM_V2SC_INTEGER_TYPES
#define PRISM_V2SC_INTEGER_TYPES
template <int Width> using prism_v2sc_uint_t = typename std::conditional<(Width <= 64), sc_uint<Width>, sc_biguint<Width>>::type;
template <int Width> using prism_v2sc_int_t = typename std::conditional<(Width <= 64), sc_int<Width>, sc_bigint<Width>>::type;
constexpr int prism_v2sc_clog2(int value) { int result = 0; for (int current = value - 1; current > 0; current >>= 1) ++result; return result; }
#endif

#ifndef PRISM_V2SC_MOD_E603_CORE_RAMS_HPP
#define PRISM_V2SC_MOD_E603_CORE_RAMS_HPP

SC_MODULE(e603_core_rams) {
  sc_in<bool> jtag_TCK;
  sc_in<bool> jtag_TMS_in;
  sc_in<bool> jtag_TDI;
  sc_out<bool> jtag_TDO;
  sc_out<bool> jtag_DRV_TDO;
  sc_out<bool> jtag_TMS_out;
  sc_out<bool> jtag_DRV_TMS;
  sc_out<bool> jtag_BK_TMS;
  sc_out<bool> jtag_dwen;
  sc_in<bool> jtag_dwbypass;
  sc_in<bool> i_dbg_stop;
  sc_in<bool> override_dm_sleep;
  sc_out<bool> hart_halted;
  sc_out<bool> dbg_stoptime;
  sc_in<bool> mem_arready;
  sc_out<bool> mem_arvalid;
  sc_out<sc_uint<32>> mem_araddr;
  sc_out<sc_uint<8>> mem_arlen;
  sc_out<sc_uint<3>> mem_arsize;
  sc_out<sc_uint<2>> mem_arburst;
  sc_out<bool> mem_arlock;
  sc_out<sc_uint<4>> mem_arcache;
  sc_out<sc_uint<3>> mem_arprot;
  sc_out<sc_uint<3>> mem_arid;
  sc_in<bool> mem_awready;
  sc_out<bool> mem_awvalid;
  sc_out<sc_uint<32>> mem_awaddr;
  sc_out<sc_uint<8>> mem_awlen;
  sc_out<sc_uint<3>> mem_awsize;
  sc_out<sc_uint<2>> mem_awburst;
  sc_out<bool> mem_awlock;
  sc_out<sc_uint<4>> mem_awcache;
  sc_out<sc_uint<3>> mem_awprot;
  sc_out<sc_uint<3>> mem_awid;
  sc_in<bool> mem_wready;
  sc_out<bool> mem_wvalid;
  sc_out<sc_uint<64>> mem_wdata;
  sc_out<sc_uint<8>> mem_wstrb;
  sc_out<bool> mem_wlast;
  sc_out<bool> mem_rready;
  sc_in<bool> mem_rvalid;
  sc_in<sc_uint<64>> mem_rdata;
  sc_in<sc_uint<2>> mem_rresp;
  sc_in<bool> mem_rlast;
  sc_in<sc_uint<3>> mem_rid;
  sc_out<bool> mem_bready;
  sc_in<bool> mem_bvalid;
  sc_in<sc_uint<2>> mem_bresp;
  sc_in<sc_uint<3>> mem_bid;
  sc_in<bool> mem_clk_en;
  sc_out<bool> tx_evt;
  sc_in<bool> rx_evt;
  sc_in<sc_uint<10>> hart_id;
  sc_in<sc_uint<40>> reset_vector;
  sc_out<bool> core_wfi_mode;
  sc_out<bool> core_sleep_value;
  sc_in<bool> nice_mem_holdup;
  sc_out<bool> nice_req_valid;
  sc_in<bool> nice_req_ready;
  sc_out<sc_uint<32>> nice_req_instr;
  sc_out<sc_uint<64>> nice_req_rs1;
  sc_out<sc_uint<64>> nice_req_rs2;
  sc_out<bool> nice_req_mmode;
  sc_out<bool> nice_req_smode;
  sc_in<bool> nice_rsp_1cyc_type;
  sc_in<sc_uint<64>> nice_rsp_1cyc_dat;
  sc_in<bool> nice_rsp_multicyc_valid;
  sc_out<bool> nice_rsp_multicyc_ready;
  sc_in<sc_uint<64>> nice_rsp_multicyc_dat;
  sc_in<bool> nice_rsp_multicyc_err;
  sc_in<bool> nice_icb_cmd_valid;
  sc_out<bool> nice_icb_cmd_ready;
  sc_in<sc_uint<32>> nice_icb_cmd_addr;
  sc_in<bool> nice_icb_cmd_read;
  sc_in<sc_uint<64>> nice_icb_cmd_wdata;
  sc_in<sc_uint<8>> nice_icb_cmd_wmask;
  sc_in<sc_uint<3>> nice_icb_cmd_size;
  sc_in<bool> nice_icb_cmd_mmode;
  sc_in<bool> nice_icb_cmd_smode;
  sc_out<bool> nice_icb_rsp_valid;
  sc_in<bool> nice_icb_rsp_ready;
  sc_out<sc_uint<64>> nice_icb_rsp_rdata;
  sc_out<bool> nice_icb_rsp_err;
  sc_in<bool> dbg_toggle_a;
  sc_in<bool> dcache_disable_init;
  sc_in<bool> icache_disable_init;
  sc_in<bool> mmu_tlb_disable_init;
  sc_out<bool> sysrstreq;
  sc_in<bool> mtime_toggle_a;
  sc_in<bool> nmi;
  sc_in<sc_uint<64>> irq_i;
  sc_out<bool> i0_trace_ivalid;
  sc_out<bool> i0_trace_iexception;
  sc_out<bool> i0_trace_interrupt;
  sc_out<sc_uint<64>> i0_trace_cause;
  sc_out<sc_uint<64>> i0_trace_tval;
  sc_out<sc_uint<64>> i0_trace_iaddr;
  sc_out<sc_uint<32>> i0_trace_instr;
  sc_out<sc_uint<2>> i0_trace_priv;
  sc_out<bool> i0_trace_bjp_taken;
  sc_out<bool> i0_trace_dmode;
  sc_out<bool> i0_trace_cmt_ena;
  sc_in<bool> core_clk_aon;
  sc_in<bool> clkgate_bypass;
  sc_in<bool> stop_on_reset;
  sc_in<bool> core_reset_n;
  sc_in<bool> por_reset_n;
  sc_in<bool> reset_bypass;

  sc_signal<bool> icache_tag0_cs;
  sc_signal<bool> icache_tag0_we;
  sc_signal<sc_uint<8>> icache_tag0_addr;
  sc_signal<sc_uint<22>> icache_tag0_din;
  sc_signal<sc_uint<22>> icache_tag0_dout;
  sc_signal<bool> clk_icache_tag0;
  sc_signal<bool> icache_data0_cs;
  sc_signal<bool> icache_data0_we;
  sc_signal<sc_uint<11>> icache_data0_addr;
  sc_signal<sc_uint<64>> icache_data0_din;
  sc_signal<sc_uint<64>> icache_data0_dout;
  sc_signal<bool> clk_icache_data0;
  sc_signal<bool> icache_tag1_cs;
  sc_signal<bool> icache_tag1_we;
  sc_signal<sc_uint<8>> icache_tag1_addr;
  sc_signal<sc_uint<22>> icache_tag1_din;
  sc_signal<sc_uint<22>> icache_tag1_dout;
  sc_signal<bool> clk_icache_tag1;
  sc_signal<bool> icache_data1_cs;
  sc_signal<bool> icache_data1_we;
  sc_signal<sc_uint<11>> icache_data1_addr;
  sc_signal<sc_uint<64>> icache_data1_din;
  sc_signal<sc_uint<64>> icache_data1_dout;
  sc_signal<bool> clk_icache_data1;
  sc_signal<bool> dcache_w0_tram_cs;
  sc_signal<bool> dcache_w0_tram_we;
  sc_signal<sc_uint<8>> dcache_w0_tram_addr;
  sc_signal<sc_uint<21>> dcache_w0_tram_din;
  sc_signal<sc_uint<21>> dcache_w0_tram_dout;
  sc_signal<bool> clk_dcache_w0_tram;
  sc_signal<bool> dcache_w1_tram_cs;
  sc_signal<bool> dcache_w1_tram_we;
  sc_signal<sc_uint<8>> dcache_w1_tram_addr;
  sc_signal<sc_uint<21>> dcache_w1_tram_din;
  sc_signal<sc_uint<21>> dcache_w1_tram_dout;
  sc_signal<bool> clk_dcache_w1_tram;
  sc_signal<bool> dcache_dram_b0_cs;
  sc_signal<bool> dcache_dram_b0_we;
  sc_signal<sc_uint<4>> dcache_dram_b0_wem;
  sc_signal<sc_uint<10>> dcache_dram_b0_addr;
  sc_signal<sc_uint<32>> dcache_dram_b0_din;
  sc_signal<sc_uint<32>> dcache_dram_b0_dout;
  sc_signal<bool> clk_dcache_dram_b0;
  sc_signal<bool> dcache_dram_b1_cs;
  sc_signal<bool> dcache_dram_b1_we;
  sc_signal<sc_uint<4>> dcache_dram_b1_wem;
  sc_signal<sc_uint<10>> dcache_dram_b1_addr;
  sc_signal<sc_uint<32>> dcache_dram_b1_din;
  sc_signal<sc_uint<32>> dcache_dram_b1_dout;
  sc_signal<bool> clk_dcache_dram_b1;
  sc_signal<bool> dcache_dram_b2_cs;
  sc_signal<bool> dcache_dram_b2_we;
  sc_signal<sc_uint<4>> dcache_dram_b2_wem;
  sc_signal<sc_uint<10>> dcache_dram_b2_addr;
  sc_signal<sc_uint<32>> dcache_dram_b2_din;
  sc_signal<sc_uint<32>> dcache_dram_b2_dout;
  sc_signal<bool> clk_dcache_dram_b2;
  sc_signal<bool> dcache_dram_b3_cs;
  sc_signal<bool> dcache_dram_b3_we;
  sc_signal<sc_uint<4>> dcache_dram_b3_wem;
  sc_signal<sc_uint<10>> dcache_dram_b3_addr;
  sc_signal<sc_uint<32>> dcache_dram_b3_din;
  sc_signal<sc_uint<32>> dcache_dram_b3_dout;
  sc_signal<bool> clk_dcache_dram_b3;
  sc_signal<bool> dcache_dram_b4_cs;
  sc_signal<bool> dcache_dram_b4_we;
  sc_signal<sc_uint<4>> dcache_dram_b4_wem;
  sc_signal<sc_uint<10>> dcache_dram_b4_addr;
  sc_signal<sc_uint<32>> dcache_dram_b4_din;
  sc_signal<sc_uint<32>> dcache_dram_b4_dout;
  sc_signal<bool> clk_dcache_dram_b4;
  sc_signal<bool> dcache_dram_b5_cs;
  sc_signal<bool> dcache_dram_b5_we;
  sc_signal<sc_uint<4>> dcache_dram_b5_wem;
  sc_signal<sc_uint<10>> dcache_dram_b5_addr;
  sc_signal<sc_uint<32>> dcache_dram_b5_din;
  sc_signal<sc_uint<32>> dcache_dram_b5_dout;
  sc_signal<bool> clk_dcache_dram_b5;
  sc_signal<bool> dcache_dram_b6_cs;
  sc_signal<bool> dcache_dram_b6_we;
  sc_signal<sc_uint<4>> dcache_dram_b6_wem;
  sc_signal<sc_uint<10>> dcache_dram_b6_addr;
  sc_signal<sc_uint<32>> dcache_dram_b6_din;
  sc_signal<sc_uint<32>> dcache_dram_b6_dout;
  sc_signal<bool> clk_dcache_dram_b6;
  sc_signal<bool> dcache_dram_b7_cs;
  sc_signal<bool> dcache_dram_b7_we;
  sc_signal<sc_uint<4>> dcache_dram_b7_wem;
  sc_signal<sc_uint<10>> dcache_dram_b7_addr;
  sc_signal<sc_uint<32>> dcache_dram_b7_din;
  sc_signal<sc_uint<32>> dcache_dram_b7_dout;
  sc_signal<bool> clk_dcache_dram_b7;
  sc_signal<bool> tlb_tram_way0_cs;
  sc_signal<bool> tlb_tram_way0_we;
  sc_signal<sc_uint<7>> tlb_tram_way0_addr;
  sc_signal<sc_uint<40>> tlb_tram_way0_din;
  sc_signal<sc_uint<40>> tlb_tram_way0_dout;
  sc_signal<bool> clk_tlb_tram_way0;
  sc_signal<bool> tlb_tram_way1_cs;
  sc_signal<bool> tlb_tram_way1_we;
  sc_signal<sc_uint<7>> tlb_tram_way1_addr;
  sc_signal<sc_uint<40>> tlb_tram_way1_din;
  sc_signal<sc_uint<40>> tlb_tram_way1_dout;
  sc_signal<bool> clk_tlb_tram_way1;
  sc_signal<bool> tlb_dram_way0_cs;
  sc_signal<bool> tlb_dram_way0_we;
  sc_signal<sc_uint<7>> tlb_dram_way0_addr;
  sc_signal<sc_uint<25>> tlb_dram_way0_din;
  sc_signal<sc_uint<25>> tlb_dram_way0_dout;
  sc_signal<bool> clk_tlb_dram_way0;
  sc_signal<bool> tlb_dram_way1_cs;
  sc_signal<bool> tlb_dram_way1_we;
  sc_signal<sc_uint<7>> tlb_dram_way1_addr;
  sc_signal<sc_uint<25>> tlb_dram_way1_din;
  sc_signal<sc_uint<25>> tlb_dram_way1_dout;
  sc_signal<bool> clk_tlb_dram_way1;

  e603_core_wrapper u_core;
  e603_rams_wrapper u_rams;
  sc_signal<sc_uint<64>> __bridge_u_core_trace_cause;
  sc_signal<sc_uint<64>> __bridge_u_core_trace_tval;
  sc_signal<sc_uint<64>> __bridge_u_core_trace_iaddr;
  sc_signal<sc_uint<32>> __bridge_u_core_trace_instr;
  sc_signal<sc_uint<2>> __bridge_u_core_trace_priv;
  sc_signal<sc_uint<64>> __bridge_u_core_irq_i;
  sc_signal<sc_uint<8>> __bridge_u_core_icache_tag0_addr;
  sc_signal<sc_uint<22>> __bridge_u_core_icache_tag0_din;
  sc_signal<sc_uint<22>> __bridge_u_core_icache_tag0_dout;
  sc_signal<sc_uint<11>> __bridge_u_core_icache_data0_addr;
  sc_signal<sc_uint<64>> __bridge_u_core_icache_data0_din;
  sc_signal<sc_uint<64>> __bridge_u_core_icache_data0_dout;
  sc_signal<sc_uint<8>> __bridge_u_core_icache_tag1_addr;
  sc_signal<sc_uint<22>> __bridge_u_core_icache_tag1_din;
  sc_signal<sc_uint<22>> __bridge_u_core_icache_tag1_dout;
  sc_signal<sc_uint<11>> __bridge_u_core_icache_data1_addr;
  sc_signal<sc_uint<64>> __bridge_u_core_icache_data1_din;
  sc_signal<sc_uint<64>> __bridge_u_core_icache_data1_dout;
  sc_signal<sc_uint<8>> __bridge_u_core_dcache_w0_tram_addr;
  sc_signal<sc_uint<21>> __bridge_u_core_dcache_w0_tram_din;
  sc_signal<sc_uint<21>> __bridge_u_core_dcache_w0_tram_dout;
  sc_signal<sc_uint<8>> __bridge_u_core_dcache_w1_tram_addr;
  sc_signal<sc_uint<21>> __bridge_u_core_dcache_w1_tram_din;
  sc_signal<sc_uint<21>> __bridge_u_core_dcache_w1_tram_dout;
  sc_signal<sc_uint<4>> __bridge_u_core_dcache_dram_b0_wem;
  sc_signal<sc_uint<10>> __bridge_u_core_dcache_dram_b0_addr;
  sc_signal<sc_uint<32>> __bridge_u_core_dcache_dram_b0_din;
  sc_signal<sc_uint<32>> __bridge_u_core_dcache_dram_b0_dout;
  sc_signal<sc_uint<4>> __bridge_u_core_dcache_dram_b1_wem;
  sc_signal<sc_uint<10>> __bridge_u_core_dcache_dram_b1_addr;
  sc_signal<sc_uint<32>> __bridge_u_core_dcache_dram_b1_din;
  sc_signal<sc_uint<32>> __bridge_u_core_dcache_dram_b1_dout;
  sc_signal<sc_uint<4>> __bridge_u_core_dcache_dram_b2_wem;
  sc_signal<sc_uint<10>> __bridge_u_core_dcache_dram_b2_addr;
  sc_signal<sc_uint<32>> __bridge_u_core_dcache_dram_b2_din;
  sc_signal<sc_uint<32>> __bridge_u_core_dcache_dram_b2_dout;
  sc_signal<sc_uint<4>> __bridge_u_core_dcache_dram_b3_wem;
  sc_signal<sc_uint<10>> __bridge_u_core_dcache_dram_b3_addr;
  sc_signal<sc_uint<32>> __bridge_u_core_dcache_dram_b3_din;
  sc_signal<sc_uint<32>> __bridge_u_core_dcache_dram_b3_dout;
  sc_signal<sc_uint<4>> __bridge_u_core_dcache_dram_b4_wem;
  sc_signal<sc_uint<10>> __bridge_u_core_dcache_dram_b4_addr;
  sc_signal<sc_uint<32>> __bridge_u_core_dcache_dram_b4_din;
  sc_signal<sc_uint<32>> __bridge_u_core_dcache_dram_b4_dout;
  sc_signal<sc_uint<4>> __bridge_u_core_dcache_dram_b5_wem;
  sc_signal<sc_uint<10>> __bridge_u_core_dcache_dram_b5_addr;
  sc_signal<sc_uint<32>> __bridge_u_core_dcache_dram_b5_din;
  sc_signal<sc_uint<32>> __bridge_u_core_dcache_dram_b5_dout;
  sc_signal<sc_uint<4>> __bridge_u_core_dcache_dram_b6_wem;
  sc_signal<sc_uint<10>> __bridge_u_core_dcache_dram_b6_addr;
  sc_signal<sc_uint<32>> __bridge_u_core_dcache_dram_b6_din;
  sc_signal<sc_uint<32>> __bridge_u_core_dcache_dram_b6_dout;
  sc_signal<sc_uint<4>> __bridge_u_core_dcache_dram_b7_wem;
  sc_signal<sc_uint<10>> __bridge_u_core_dcache_dram_b7_addr;
  sc_signal<sc_uint<32>> __bridge_u_core_dcache_dram_b7_din;
  sc_signal<sc_uint<32>> __bridge_u_core_dcache_dram_b7_dout;
  sc_signal<sc_uint<7>> __bridge_u_core_tlb_tram_way0_addr;
  sc_signal<sc_uint<40>> __bridge_u_core_tlb_tram_way0_din;
  sc_signal<sc_uint<40>> __bridge_u_core_tlb_tram_way0_dout;
  sc_signal<sc_uint<7>> __bridge_u_core_tlb_tram_way1_addr;
  sc_signal<sc_uint<40>> __bridge_u_core_tlb_tram_way1_din;
  sc_signal<sc_uint<40>> __bridge_u_core_tlb_tram_way1_dout;
  sc_signal<sc_uint<7>> __bridge_u_core_tlb_dram_way0_addr;
  sc_signal<sc_uint<25>> __bridge_u_core_tlb_dram_way0_din;
  sc_signal<sc_uint<25>> __bridge_u_core_tlb_dram_way0_dout;
  sc_signal<sc_uint<7>> __bridge_u_core_tlb_dram_way1_addr;
  sc_signal<sc_uint<25>> __bridge_u_core_tlb_dram_way1_din;
  sc_signal<sc_uint<25>> __bridge_u_core_tlb_dram_way1_dout;
  sc_signal<sc_uint<32>> __bridge_u_core_mem_araddr;
  sc_signal<sc_uint<8>> __bridge_u_core_mem_arlen;
  sc_signal<sc_uint<3>> __bridge_u_core_mem_arsize;
  sc_signal<sc_uint<2>> __bridge_u_core_mem_arburst;
  sc_signal<sc_uint<4>> __bridge_u_core_mem_arcache;
  sc_signal<sc_uint<3>> __bridge_u_core_mem_arprot;
  sc_signal<sc_uint<3>> __bridge_u_core_mem_arid;
  sc_signal<sc_uint<32>> __bridge_u_core_mem_awaddr;
  sc_signal<sc_uint<8>> __bridge_u_core_mem_awlen;
  sc_signal<sc_uint<3>> __bridge_u_core_mem_awsize;
  sc_signal<sc_uint<2>> __bridge_u_core_mem_awburst;
  sc_signal<sc_uint<4>> __bridge_u_core_mem_awcache;
  sc_signal<sc_uint<3>> __bridge_u_core_mem_awprot;
  sc_signal<sc_uint<3>> __bridge_u_core_mem_awid;
  sc_signal<sc_uint<64>> __bridge_u_core_mem_wdata;
  sc_signal<sc_uint<8>> __bridge_u_core_mem_wstrb;
  sc_signal<sc_uint<64>> __bridge_u_core_mem_rdata;
  sc_signal<sc_uint<2>> __bridge_u_core_mem_rresp;
  sc_signal<sc_uint<3>> __bridge_u_core_mem_rid;
  sc_signal<sc_uint<2>> __bridge_u_core_mem_bresp;
  sc_signal<sc_uint<3>> __bridge_u_core_mem_bid;
  sc_signal<sc_uint<64>> __bridge_u_core_hart_id;
  sc_signal<sc_uint<64>> __bridge_u_core_reset_vector;
  sc_signal<sc_uint<32>> __bridge_u_core_nice_req_instr;
  sc_signal<sc_uint<64>> __bridge_u_core_nice_req_rs1;
  sc_signal<sc_uint<64>> __bridge_u_core_nice_req_rs2;
  sc_signal<sc_uint<64>> __bridge_u_core_nice_rsp_1cyc_dat;
  sc_signal<bool> __bridge_u_core_nice_rsp_1cyc_err;
  sc_signal<sc_uint<64>> __bridge_u_core_nice_rsp_multicyc_dat;
  sc_signal<sc_uint<32>> __bridge_u_core_nice_icb_cmd_addr;
  sc_signal<sc_uint<64>> __bridge_u_core_nice_icb_cmd_wdata;
  sc_signal<sc_uint<8>> __bridge_u_core_nice_icb_cmd_wmask;
  sc_signal<sc_uint<2>> __bridge_u_core_nice_icb_cmd_size;
  sc_signal<sc_uint<64>> __bridge_u_core_nice_icb_rsp_rdata;
  sc_signal<sc_uint<8>> __bridge_u_rams_icache_tag0_addr;
  sc_signal<sc_uint<22>> __bridge_u_rams_icache_tag0_din;
  sc_signal<sc_uint<22>> __bridge_u_rams_icache_tag0_dout;
  sc_signal<sc_uint<11>> __bridge_u_rams_icache_data0_addr;
  sc_signal<sc_uint<64>> __bridge_u_rams_icache_data0_din;
  sc_signal<sc_uint<64>> __bridge_u_rams_icache_data0_dout;
  sc_signal<sc_uint<8>> __bridge_u_rams_icache_tag1_addr;
  sc_signal<sc_uint<22>> __bridge_u_rams_icache_tag1_din;
  sc_signal<sc_uint<22>> __bridge_u_rams_icache_tag1_dout;
  sc_signal<sc_uint<11>> __bridge_u_rams_icache_data1_addr;
  sc_signal<sc_uint<64>> __bridge_u_rams_icache_data1_din;
  sc_signal<sc_uint<64>> __bridge_u_rams_icache_data1_dout;
  sc_signal<sc_uint<8>> __bridge_u_rams_dcache_w0_tram_addr;
  sc_signal<sc_uint<21>> __bridge_u_rams_dcache_w0_tram_din;
  sc_signal<sc_uint<21>> __bridge_u_rams_dcache_w0_tram_dout;
  sc_signal<sc_uint<8>> __bridge_u_rams_dcache_w1_tram_addr;
  sc_signal<sc_uint<21>> __bridge_u_rams_dcache_w1_tram_din;
  sc_signal<sc_uint<21>> __bridge_u_rams_dcache_w1_tram_dout;
  sc_signal<sc_uint<4>> __bridge_u_rams_dcache_dram_b0_wem;
  sc_signal<sc_uint<10>> __bridge_u_rams_dcache_dram_b0_addr;
  sc_signal<sc_uint<32>> __bridge_u_rams_dcache_dram_b0_din;
  sc_signal<sc_uint<32>> __bridge_u_rams_dcache_dram_b0_dout;
  sc_signal<sc_uint<4>> __bridge_u_rams_dcache_dram_b1_wem;
  sc_signal<sc_uint<10>> __bridge_u_rams_dcache_dram_b1_addr;
  sc_signal<sc_uint<32>> __bridge_u_rams_dcache_dram_b1_din;
  sc_signal<sc_uint<32>> __bridge_u_rams_dcache_dram_b1_dout;
  sc_signal<sc_uint<4>> __bridge_u_rams_dcache_dram_b2_wem;
  sc_signal<sc_uint<10>> __bridge_u_rams_dcache_dram_b2_addr;
  sc_signal<sc_uint<32>> __bridge_u_rams_dcache_dram_b2_din;
  sc_signal<sc_uint<32>> __bridge_u_rams_dcache_dram_b2_dout;
  sc_signal<sc_uint<4>> __bridge_u_rams_dcache_dram_b3_wem;
  sc_signal<sc_uint<10>> __bridge_u_rams_dcache_dram_b3_addr;
  sc_signal<sc_uint<32>> __bridge_u_rams_dcache_dram_b3_din;
  sc_signal<sc_uint<32>> __bridge_u_rams_dcache_dram_b3_dout;
  sc_signal<sc_uint<4>> __bridge_u_rams_dcache_dram_b4_wem;
  sc_signal<sc_uint<10>> __bridge_u_rams_dcache_dram_b4_addr;
  sc_signal<sc_uint<32>> __bridge_u_rams_dcache_dram_b4_din;
  sc_signal<sc_uint<32>> __bridge_u_rams_dcache_dram_b4_dout;
  sc_signal<sc_uint<4>> __bridge_u_rams_dcache_dram_b5_wem;
  sc_signal<sc_uint<10>> __bridge_u_rams_dcache_dram_b5_addr;
  sc_signal<sc_uint<32>> __bridge_u_rams_dcache_dram_b5_din;
  sc_signal<sc_uint<32>> __bridge_u_rams_dcache_dram_b5_dout;
  sc_signal<sc_uint<4>> __bridge_u_rams_dcache_dram_b6_wem;
  sc_signal<sc_uint<10>> __bridge_u_rams_dcache_dram_b6_addr;
  sc_signal<sc_uint<32>> __bridge_u_rams_dcache_dram_b6_din;
  sc_signal<sc_uint<32>> __bridge_u_rams_dcache_dram_b6_dout;
  sc_signal<sc_uint<4>> __bridge_u_rams_dcache_dram_b7_wem;
  sc_signal<sc_uint<10>> __bridge_u_rams_dcache_dram_b7_addr;
  sc_signal<sc_uint<32>> __bridge_u_rams_dcache_dram_b7_din;
  sc_signal<sc_uint<32>> __bridge_u_rams_dcache_dram_b7_dout;
  sc_signal<sc_uint<7>> __bridge_u_rams_tlb_tram_way0_addr;
  sc_signal<sc_uint<40>> __bridge_u_rams_tlb_tram_way0_din;
  sc_signal<sc_uint<40>> __bridge_u_rams_tlb_tram_way0_dout;
  sc_signal<sc_uint<7>> __bridge_u_rams_tlb_tram_way1_addr;
  sc_signal<sc_uint<40>> __bridge_u_rams_tlb_tram_way1_din;
  sc_signal<sc_uint<40>> __bridge_u_rams_tlb_tram_way1_dout;
  sc_signal<sc_uint<7>> __bridge_u_rams_tlb_dram_way0_addr;
  sc_signal<sc_uint<25>> __bridge_u_rams_tlb_dram_way0_din;
  sc_signal<sc_uint<25>> __bridge_u_rams_tlb_dram_way0_dout;
  sc_signal<sc_uint<7>> __bridge_u_rams_tlb_dram_way1_addr;
  sc_signal<sc_uint<25>> __bridge_u_rams_tlb_dram_way1_din;
  sc_signal<sc_uint<25>> __bridge_u_rams_tlb_dram_way1_dout;

  void __bridge_method_u_core_irq_i();

  void __bridge_method_u_core_icache_tag0_dout();

  void __bridge_method_u_core_icache_data0_dout();

  void __bridge_method_u_core_icache_tag1_dout();

  void __bridge_method_u_core_icache_data1_dout();

  void __bridge_method_u_core_dcache_w0_tram_dout();

  void __bridge_method_u_core_dcache_w1_tram_dout();

  void __bridge_method_u_core_dcache_dram_b0_dout();

  void __bridge_method_u_core_dcache_dram_b1_dout();

  void __bridge_method_u_core_dcache_dram_b2_dout();

  void __bridge_method_u_core_dcache_dram_b3_dout();

  void __bridge_method_u_core_dcache_dram_b4_dout();

  void __bridge_method_u_core_dcache_dram_b5_dout();

  void __bridge_method_u_core_dcache_dram_b6_dout();

  void __bridge_method_u_core_dcache_dram_b7_dout();

  void __bridge_method_u_core_tlb_tram_way0_dout();

  void __bridge_method_u_core_tlb_tram_way1_dout();

  void __bridge_method_u_core_tlb_dram_way0_dout();

  void __bridge_method_u_core_tlb_dram_way1_dout();

  void __bridge_method_u_core_mem_rdata();

  void __bridge_method_u_core_mem_rresp();

  void __bridge_method_u_core_mem_rid();

  void __bridge_method_u_core_mem_bresp();

  void __bridge_method_u_core_mem_bid();

  void __bridge_method_u_core_hart_id();

  void __bridge_method_u_core_reset_vector();

  void __bridge_method_u_core_nice_rsp_1cyc_dat();

  void __bridge_method_u_core_nice_rsp_1cyc_err();

  void __bridge_method_u_core_nice_rsp_multicyc_dat();

  void __bridge_method_u_core_nice_icb_cmd_addr();

  void __bridge_method_u_core_nice_icb_cmd_wdata();

  void __bridge_method_u_core_nice_icb_cmd_wmask();

  void __bridge_method_u_core_nice_icb_cmd_size();

  void __bridge_method_u_rams_icache_tag0_addr();

  void __bridge_method_u_rams_icache_tag0_din();

  void __bridge_method_u_rams_icache_data0_addr();

  void __bridge_method_u_rams_icache_data0_din();

  void __bridge_method_u_rams_icache_tag1_addr();

  void __bridge_method_u_rams_icache_tag1_din();

  void __bridge_method_u_rams_icache_data1_addr();

  void __bridge_method_u_rams_icache_data1_din();

  void __bridge_method_u_rams_dcache_w0_tram_addr();

  void __bridge_method_u_rams_dcache_w0_tram_din();

  void __bridge_method_u_rams_dcache_w1_tram_addr();

  void __bridge_method_u_rams_dcache_w1_tram_din();

  void __bridge_method_u_rams_dcache_dram_b0_wem();

  void __bridge_method_u_rams_dcache_dram_b0_addr();

  void __bridge_method_u_rams_dcache_dram_b0_din();

  void __bridge_method_u_rams_dcache_dram_b1_wem();

  void __bridge_method_u_rams_dcache_dram_b1_addr();

  void __bridge_method_u_rams_dcache_dram_b1_din();

  void __bridge_method_u_rams_dcache_dram_b2_wem();

  void __bridge_method_u_rams_dcache_dram_b2_addr();

  void __bridge_method_u_rams_dcache_dram_b2_din();

  void __bridge_method_u_rams_dcache_dram_b3_wem();

  void __bridge_method_u_rams_dcache_dram_b3_addr();

  void __bridge_method_u_rams_dcache_dram_b3_din();

  void __bridge_method_u_rams_dcache_dram_b4_wem();

  void __bridge_method_u_rams_dcache_dram_b4_addr();

  void __bridge_method_u_rams_dcache_dram_b4_din();

  void __bridge_method_u_rams_dcache_dram_b5_wem();

  void __bridge_method_u_rams_dcache_dram_b5_addr();

  void __bridge_method_u_rams_dcache_dram_b5_din();

  void __bridge_method_u_rams_dcache_dram_b6_wem();

  void __bridge_method_u_rams_dcache_dram_b6_addr();

  void __bridge_method_u_rams_dcache_dram_b6_din();

  void __bridge_method_u_rams_dcache_dram_b7_wem();

  void __bridge_method_u_rams_dcache_dram_b7_addr();

  void __bridge_method_u_rams_dcache_dram_b7_din();

  void __bridge_method_u_rams_tlb_tram_way0_addr();

  void __bridge_method_u_rams_tlb_tram_way0_din();

  void __bridge_method_u_rams_tlb_tram_way1_addr();

  void __bridge_method_u_rams_tlb_tram_way1_din();

  void __bridge_method_u_rams_tlb_dram_way0_addr();

  void __bridge_method_u_rams_tlb_dram_way0_din();

  void __bridge_method_u_rams_tlb_dram_way1_addr();

  void __bridge_method_u_rams_tlb_dram_way1_din();

  void __bridge_assemble_i0_trace_cause();

  void __bridge_assemble_i0_trace_tval();

  void __bridge_assemble_i0_trace_iaddr();

  void __bridge_assemble_i0_trace_instr();

  void __bridge_assemble_i0_trace_priv();

  void __bridge_assemble_icache_tag0_addr();

  void __bridge_assemble_icache_tag0_din();

  void __bridge_assemble_icache_data0_addr();

  void __bridge_assemble_icache_data0_din();

  void __bridge_assemble_icache_tag1_addr();

  void __bridge_assemble_icache_tag1_din();

  void __bridge_assemble_icache_data1_addr();

  void __bridge_assemble_icache_data1_din();

  void __bridge_assemble_dcache_w0_tram_addr();

  void __bridge_assemble_dcache_w0_tram_din();

  void __bridge_assemble_dcache_w1_tram_addr();

  void __bridge_assemble_dcache_w1_tram_din();

  void __bridge_assemble_dcache_dram_b0_wem();

  void __bridge_assemble_dcache_dram_b0_addr();

  void __bridge_assemble_dcache_dram_b0_din();

  void __bridge_assemble_dcache_dram_b1_wem();

  void __bridge_assemble_dcache_dram_b1_addr();

  void __bridge_assemble_dcache_dram_b1_din();

  void __bridge_assemble_dcache_dram_b2_wem();

  void __bridge_assemble_dcache_dram_b2_addr();

  void __bridge_assemble_dcache_dram_b2_din();

  void __bridge_assemble_dcache_dram_b3_wem();

  void __bridge_assemble_dcache_dram_b3_addr();

  void __bridge_assemble_dcache_dram_b3_din();

  void __bridge_assemble_dcache_dram_b4_wem();

  void __bridge_assemble_dcache_dram_b4_addr();

  void __bridge_assemble_dcache_dram_b4_din();

  void __bridge_assemble_dcache_dram_b5_wem();

  void __bridge_assemble_dcache_dram_b5_addr();

  void __bridge_assemble_dcache_dram_b5_din();

  void __bridge_assemble_dcache_dram_b6_wem();

  void __bridge_assemble_dcache_dram_b6_addr();

  void __bridge_assemble_dcache_dram_b6_din();

  void __bridge_assemble_dcache_dram_b7_wem();

  void __bridge_assemble_dcache_dram_b7_addr();

  void __bridge_assemble_dcache_dram_b7_din();

  void __bridge_assemble_tlb_tram_way0_addr();

  void __bridge_assemble_tlb_tram_way0_din();

  void __bridge_assemble_tlb_tram_way1_addr();

  void __bridge_assemble_tlb_tram_way1_din();

  void __bridge_assemble_tlb_dram_way0_addr();

  void __bridge_assemble_tlb_dram_way0_din();

  void __bridge_assemble_tlb_dram_way1_addr();

  void __bridge_assemble_tlb_dram_way1_din();

  void __bridge_assemble_mem_araddr();

  void __bridge_assemble_mem_arlen();

  void __bridge_assemble_mem_arsize();

  void __bridge_assemble_mem_arburst();

  void __bridge_assemble_mem_arcache();

  void __bridge_assemble_mem_arprot();

  void __bridge_assemble_mem_arid();

  void __bridge_assemble_mem_awaddr();

  void __bridge_assemble_mem_awlen();

  void __bridge_assemble_mem_awsize();

  void __bridge_assemble_mem_awburst();

  void __bridge_assemble_mem_awcache();

  void __bridge_assemble_mem_awprot();

  void __bridge_assemble_mem_awid();

  void __bridge_assemble_mem_wdata();

  void __bridge_assemble_mem_wstrb();

  void __bridge_assemble_nice_req_instr();

  void __bridge_assemble_nice_req_rs1();

  void __bridge_assemble_nice_req_rs2();

  void __bridge_assemble_nice_icb_rsp_rdata();

  void __bridge_assemble_icache_tag0_dout();

  void __bridge_assemble_icache_data0_dout();

  void __bridge_assemble_icache_tag1_dout();

  void __bridge_assemble_icache_data1_dout();

  void __bridge_assemble_dcache_w0_tram_dout();

  void __bridge_assemble_dcache_w1_tram_dout();

  void __bridge_assemble_dcache_dram_b0_dout();

  void __bridge_assemble_dcache_dram_b1_dout();

  void __bridge_assemble_dcache_dram_b2_dout();

  void __bridge_assemble_dcache_dram_b3_dout();

  void __bridge_assemble_dcache_dram_b4_dout();

  void __bridge_assemble_dcache_dram_b5_dout();

  void __bridge_assemble_dcache_dram_b6_dout();

  void __bridge_assemble_dcache_dram_b7_dout();

  void __bridge_assemble_tlb_tram_way0_dout();

  void __bridge_assemble_tlb_tram_way1_dout();

  void __bridge_assemble_tlb_dram_way0_dout();

  void __bridge_assemble_tlb_dram_way1_dout();

  SC_HAS_PROCESS(e603_core_rams);
  e603_core_rams(sc_module_name name);
};

#endif  // PRISM_V2SC_MOD_E603_CORE_RAMS_HPP
