// Generated by prism_v2sc
#pragma once

#include <array>
#include <systemc>
#include <string>
#include <type_traits>

#include "e603_reset_sync.hpp"
#include "e603_gnrl_dffrs__prism_p_3b88fa35c9.hpp"

using namespace sc_core;
using namespace sc_dt;

#ifndef PRISM_V2SC_INTEGER_TYPES
#define PRISM_V2SC_INTEGER_TYPES
template <int Width> using prism_v2sc_uint_t = typename std::conditional<(Width <= 64), sc_uint<Width>, sc_biguint<Width>>::type;
template <int Width> using prism_v2sc_int_t = typename std::conditional<(Width <= 64), sc_int<Width>, sc_bigint<Width>>::type;
constexpr int prism_v2sc_clog2(int value) { int result = 0; for (int current = value - 1; current > 0; current >>= 1) ++result; return result; }
#endif

#ifndef PRISM_V2SC_MOD_E603_RST_CTRL_HPP
#define PRISM_V2SC_MOD_E603_RST_CTRL_HPP

SC_MODULE(e603_rst_ctrl) {
  sc_out<bool> hart_under_reset;
  sc_in<bool> clk_aon;
  sc_in<bool> por_reset_n;
  sc_in<bool> core_reset_n;
  sc_in<bool> reset_bypass;
  sc_out<bool> rst_core;
  sc_out<bool> rst_por;
  sc_out<bool> rst_aon;

  sc_signal<bool> rst_n_a;
  sc_signal<bool> rst_n_por_a;
  sc_signal<bool> byp_core_reset_n;
  sc_signal<bool> rst_n_sync;
  sc_signal<bool> rst_n_por_sync;
  sc_signal<bool> reset_flag_r;

  e603_reset_sync<2> u_reset_sync;
  e603_reset_sync<2> u_reset_por_sync;
  e603_gnrl_dffrs__prism_p_3b88fa35c9<1, 0b1> reset_flag_dffrs;
  sc_signal<sc_uint<1>> __bridge_reset_flag_dffrs_dnxt;
  sc_signal<sc_uint<1>> __bridge_reset_flag_dffrs_qout;

  void assign_0() {
    byp_core_reset_n.write((reset_bypass.read() ? 0b1 : core_reset_n.read()));
  }

  void assign_1() {
    rst_n_a.write((por_reset_n.read() & byp_core_reset_n.read()));
  }

  void assign_2() {
    rst_n_por_a.write(por_reset_n.read());
  }

  void assign_3() {
    rst_core.write(rst_n_sync.read());
  }

  void assign_4() {
    rst_aon.write(rst_n_sync.read());
  }

  void assign_5() {
    rst_por.write(rst_n_por_sync.read());
  }

  void assign_6() {
    hart_under_reset.write(reset_flag_r.read());
  }

  void __bridge_method_reset_flag_dffrs_dnxt() {
    __bridge_reset_flag_dffrs_dnxt.write(sc_uint<1>(0b0));
  }

  void __bridge_method_reset_flag_dffrs_qout() {
    reset_flag_r.write(__bridge_reset_flag_dffrs_qout.read());
  }

  SC_CTOR(e603_rst_ctrl)
    : u_reset_sync("u_reset_sync"), u_reset_por_sync("u_reset_por_sync"), reset_flag_dffrs("reset_flag_dffrs")
  {
    SC_METHOD(assign_0);
    sensitive << reset_bypass << core_reset_n;

    SC_METHOD(assign_1);
    sensitive << por_reset_n << byp_core_reset_n;

    SC_METHOD(assign_2);
    sensitive << por_reset_n;

    SC_METHOD(assign_3);
    sensitive << rst_n_sync;

    SC_METHOD(assign_4);
    sensitive << rst_n_sync;

    SC_METHOD(assign_5);
    sensitive << rst_n_por_sync;

    SC_METHOD(assign_6);
    sensitive << reset_flag_r;

    u_reset_sync.clk(clk_aon);
    u_reset_sync.rst_n_a(rst_n_a);
    u_reset_sync.reset_bypass(reset_bypass);
    u_reset_sync.rst_n_sync(rst_n_sync);
    u_reset_por_sync.clk(clk_aon);
    u_reset_por_sync.rst_n_a(rst_n_por_a);
    u_reset_por_sync.reset_bypass(reset_bypass);
    u_reset_por_sync.rst_n_sync(rst_n_por_sync);
    reset_flag_dffrs.dnxt(__bridge_reset_flag_dffrs_dnxt);
    reset_flag_dffrs.qout(__bridge_reset_flag_dffrs_qout);
    reset_flag_dffrs.clk(clk_aon);
    reset_flag_dffrs.rst_n(rst_core);
    __bridge_method_reset_flag_dffrs_dnxt();

    SC_METHOD(__bridge_method_reset_flag_dffrs_qout);
    sensitive << __bridge_reset_flag_dffrs_qout;

  }
};

#endif  // PRISM_V2SC_MOD_E603_RST_CTRL_HPP
